/-
  LAYER 0: The Distributive Coupling — Algebraic Infrastructure

  This layer establishes the algebraic properties of ℤ that underlie
  the entire chain. Everything here is provable from Mathlib's existing
  algebra library — no sorry's should be needed.

  Key facts:
  - The distributive law couples + and × perfectly (ring axiom)
  - ℤ is a PID (class number 1 — no hidden multiplicative structure)
  - ℤ is a UFD (unique factorization into primes)
  - ℤ is a Euclidean domain (division algorithm exists)
-/

import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.UniqueFactorizationDomain
import Mathlib.RingTheory.EuclideanDomain
import Mathlib.RingTheory.Int.Basic
import Mathlib.Data.Int.Basic
import Mathlib.Algebra.Ring.Basic

namespace ArithmeticHodge.Algebra

-- ============================================================
-- The Distributive Law as the Coupling of + and ×
-- ============================================================

/-- The distributive law is the sole axiom coupling addition and multiplication.
    In a commutative ring, it holds perfectly and symmetrically.
    This is the "Markov blanket" between additive and multiplicative structure. -/
theorem perfect_distribution {R : Type*} [CommRing R] (a b c : R) :
    a * (b + c) = a * b + a * c :=
  mul_add a b c

/-- Right distribution follows from commutativity + left distribution.
    Both directions work: the coupling is symmetric. -/
theorem perfect_distribution_right {R : Type*} [CommRing R] (a b c : R) :
    (a + b) * c = a * c + b * c :=
  add_mul a b c

/-- Distribution over subtraction — the coupling respects negation. -/
theorem distribution_sub {R : Type*} [CommRing R] (a b c : R) :
    a * (b - c) = a * b - a * c :=
  mul_sub a b c

-- ============================================================
-- Structural Properties of ℤ
-- ============================================================

/-- ℤ is a principal ideal domain: class number 1.
    Every ideal is generated by a single element.
    The multiplicative structure has no hidden degrees of freedom. -/
instance : IsPrincipalIdealRing ℤ := inferInstance

/-- ℤ is a unique factorization domain.
    Every nonzero non-unit factors uniquely into irreducibles (primes). -/
instance : UniqueFactorizationMonoid ℤ := inferInstance

/-- ℤ is a Euclidean domain: there exists a division algorithm.
    This gives the interplay of + and × a computational form. -/
instance : EuclideanDomain ℤ := inferInstance

-- ============================================================
-- The Ring Axioms Are Complete
-- ============================================================

/-- The distributive law is an *identity* — it holds for ALL triples.
    This means the coupling between + and × is "perfect" in the sense
    that there are no exceptional inputs where distribution fails. -/
theorem distribution_universal (R : Type*) [CommRing R] :
    ∀ a b c : R, a * (b + c) = a * b + a * c :=
  fun a b c => mul_add a b c

/-- Commutativity of multiplication: a * b = b * a.
    Combined with distribution, this gives the full coupling symmetry. -/
theorem mul_comm_Z : ∀ a b : ℤ, a * b = b * a :=
  fun a b => mul_comm a b

end ArithmeticHodge.Algebra
