import ArithmeticHodge.Analysis.MultiplicativeWeilCoherentCompensatedCutoffCompanionStructural
import ArithmeticHodge.Analysis.MultiplicativeWeilCoherentCutoffCompanionObstructionStructural

set_option autoImplicit false

open Complex MeasureTheory Real Set
open scoped ContDiff

namespace ArithmeticHodge.Analysis.MultiplicativeWeilCoherentCompensatedCutoffCrossStructural

noncomputable section

open MultiplicativeWeil
open MultiplicativeWeilCorrectedChebyshevPotentialStructural
open MultiplicativeWeilDirectedCorrelationDerivativeStructural

/-!
# The separated cross of a compensated coherent cutoff

A compact companion for the first-slot coherent cutoff derivative requires a
zero-mass correction.  This module carries that correction through the
conjugated directed correlation and the separated corrected-potential formula.
The conjugation changes the correction coefficient from `mass` to
`starRingEnd ℂ mass`.
-/

/-- The first-slot cutoff boundary from a coherent pair. -/
def coherentCutoffBoundaryIntegrand
    (parent : BombieriTest) (eta theta : ℝ → ℝ)
    (x y : ℝ) : ℂ :=
  (((y * deriv eta (x * y) * theta y : ℝ) : ℂ) *
    (starRingEnd ℂ (parent (x * y)) * parent y))

/-- The derivative-source correlation generated by the compensating bump.
This is not `bombieriTwoBlockGlobalCrossSymbol rho h`: that symbol contains
the derivative of `rho`, while the correction source here is `rho` itself. -/
def rankOneSourceIntegrand
    (rho h : BombieriTest) (x y : ℝ) : ℂ :=
  ((y : ℂ) * starRingEnd ℂ (rho (x * y))) * h y

private theorem derivCompanionIntegrand_integrableOn
    (U h : BombieriTest) (x : ℝ) :
    IntegrableOn
      (fun y : ℝ ↦
        ((y : ℂ) * starRingEnd ℂ (deriv U (x * y))) * h y)
      (Set.Ioi 0) := by
  have hcontinuous : Continuous (fun y : ℝ ↦
      ((y : ℂ) * starRingEnd ℂ (deriv U (x * y))) * h y) := by
    have hderiv : Continuous (deriv U) :=
      U.contDiff.continuous_deriv (by simp)
    fun_prop
  have hcompact : HasCompactSupport (fun y : ℝ ↦
      ((y : ℂ) * starRingEnd ℂ (deriv U (x * y))) * h y) := by
    simpa only [Pi.mul_apply] using h.hasCompactSupport.mul_left
      (f := fun y : ℝ ↦
        (y : ℂ) * starRingEnd ℂ (deriv U (x * y)))
  exact (hcontinuous.integrable_of_hasCompactSupport hcompact).integrableOn

private theorem rankOneSourceIntegrand_integrableOn
    (rho h : BombieriTest) (x : ℝ) :
    IntegrableOn (rankOneSourceIntegrand rho h x) (Set.Ioi 0) := by
  have hcontinuous : Continuous (rankOneSourceIntegrand rho h x) := by
    unfold rankOneSourceIntegrand
    fun_prop
  have hcompact : HasCompactSupport (rankOneSourceIntegrand rho h x) := by
    unfold rankOneSourceIntegrand
    simpa only [Pi.mul_apply] using h.hasCompactSupport.mul_left
      (f := fun y : ℝ ↦
        (y : ℂ) * starRingEnd ℂ (rho (x * y)))
  exact (hcontinuous.integrable_of_hasCompactSupport hcompact).integrableOn

/-- Exact pointwise compensation identity.  The scalar is conjugated because
the separated formula differentiates a conjugated directed correlation. -/
theorem coherentCutoffBoundaryIntegrand_eq_companion_add_rankOne
    (parent rho h U : BombieriTest) (eta theta : ℝ → ℝ)
    (mass : ℂ)
    (hh : ∀ z : ℝ, h z = (theta z : ℂ) * parent z)
    (hU : ∀ z : ℝ,
      deriv U z =
        ((deriv eta z : ℝ) : ℂ) * parent z - mass * rho z)
    (x y : ℝ) :
    coherentCutoffBoundaryIntegrand parent eta theta x y =
      ((y : ℂ) * starRingEnd ℂ (deriv U (x * y))) * h y +
        starRingEnd ℂ mass * rankOneSourceIntegrand rho h x y := by
  unfold coherentCutoffBoundaryIntegrand rankOneSourceIntegrand
  rw [hU, hh]
  simp only [map_sub, map_mul, starRingEnd_apply]
  simp only [RCLike.star_def, Complex.conj_ofReal]
  push_cast
  ring

/-- The integrated coherent cutoff derivative is the companion correlation
derivative plus the explicit conjugated-mass rank-one source correlation. -/
theorem integral_coherentCutoffBoundary_eq_companion_add_rankOne
    (parent rho h U : BombieriTest) (eta theta : ℝ → ℝ)
    (mass : ℂ)
    (hh : ∀ z : ℝ, h z = (theta z : ℂ) * parent z)
    (hU : ∀ z : ℝ,
      deriv U z =
        ((deriv eta z : ℝ) : ℂ) * parent z - mass * rho z)
    (x : ℝ) :
    (∫ y : ℝ in Set.Ioi 0,
      coherentCutoffBoundaryIntegrand parent eta theta x y) =
      deriv (fun z : ℝ ↦
        starRingEnd ℂ (bombieriDirectedCorrelation U h z)) x +
      starRingEnd ℂ mass *
        ∫ y : ℝ in Set.Ioi 0, rankOneSourceIntegrand rho h x y := by
  rw [deriv_star_bombieriDirectedCorrelation_eq_integral]
  have hderiv := derivCompanionIntegrand_integrableOn U h x
  have hrank := rankOneSourceIntegrand_integrableOn rho h x
  calc
    (∫ y : ℝ in Set.Ioi 0,
        coherentCutoffBoundaryIntegrand parent eta theta x y) =
      ∫ y : ℝ in Set.Ioi 0,
        (((y : ℂ) * starRingEnd ℂ (deriv U (x * y))) * h y +
          starRingEnd ℂ mass * rankOneSourceIntegrand rho h x y) := by
            apply setIntegral_congr_fun measurableSet_Ioi
            intro y _hy
            exact coherentCutoffBoundaryIntegrand_eq_companion_add_rankOne
              parent rho h U eta theta mass hh hU x y
    _ = (∫ y : ℝ in Set.Ioi 0,
          ((y : ℂ) * starRingEnd ℂ (deriv U (x * y))) * h y) +
        ∫ y : ℝ in Set.Ioi 0,
          starRingEnd ℂ mass * rankOneSourceIntegrand rho h x y := by
            exact integral_add hderiv (hrank.const_mul _)
    _ = _ := by
      have hmul :
          (∫ y : ℝ in Set.Ioi 0,
            starRingEnd ℂ mass * rankOneSourceIntegrand rho h x y) =
          starRingEnd ℂ mass *
            ∫ y : ℝ in Set.Ioi 0,
              rankOneSourceIntegrand rho h x y := by
        exact integral_const_mul (starRingEnd ℂ mass)
          (rankOneSourceIntegrand rho h x)
      rw [hmul]

/-- Under strict support separation, the actual Bombieri global cross of the
companion and the lower cell is the full corrected-potential representation
of the coherent cutoff after subtracting its explicit rank-one source. -/
theorem bombieriTwoBlockGlobalCrossSymbol_eq_compensatedCutoff
    (parent rho h U : BombieriTest) (eta theta : ℝ → ℝ)
    (mass : ℂ)
    (hh : ∀ z : ℝ, h z = (theta z : ℂ) * parent z)
    (hU : ∀ z : ℝ,
      deriv U z =
        ((deriv eta z : ℝ) : ℂ) * parent z - mass * rho z)
    {aU bU ah bh : ℝ}
    (hah : 0 < ah) (hbh : 0 < bh)
    (hUsupport : tsupport U ⊆ Set.Icc aU bU)
    (hhsupport : tsupport h ⊆ Set.Icc ah bh)
    (hsep : bh < aU) :
    bombieriTwoBlockGlobalCrossSymbol U h =
      (∫ x : ℝ in Set.Ioi 0,
        ((Chebyshev.psi x - x : ℝ) : ℂ) *
          ((∫ y : ℝ in Set.Ioi 0,
              coherentCutoffBoundaryIntegrand parent eta theta x y) -
            starRingEnd ℂ mass *
              ∫ y : ℝ in Set.Ioi 0,
                rankOneSourceIntegrand rho h x y)) +
      ∫ x : ℝ in Set.Ioi 0,
        ((correctedChebyshevPotential x : ℝ) : ℂ) *
          ((∫ y : ℝ in Set.Ioi 0,
              coherentCutoffBoundaryIntegrand parent eta theta x y) -
            starRingEnd ℂ mass *
              ∫ y : ℝ in Set.Ioi 0,
                rankOneSourceIntegrand rho h x y) := by
  have haU : 0 < aU := hbh.trans hsep
  have hratio : bh / aU < 1 := by
    rw [div_lt_one haU]
    exact hsep
  have H :=
    sqrt_mul_bombieriTwoBlockGlobalCrossSymbol_normalizedDilation_eq_chebyshevError_add_correctedPotential
      U h (r := 1) (by norm_num) haU hah hbh
      hUsupport hhsupport hratio
  simp only [Real.sqrt_one, Complex.ofReal_one, one_mul,
    normalizedDilation_one] at H
  rw [H]
  congr 1
  · apply setIntegral_congr_fun measurableSet_Ioi
    intro x _hx
    simp only
    congr 1
    have hxid := integral_coherentCutoffBoundary_eq_companion_add_rankOne
      parent rho h U eta theta mass hh hU x
    exact (eq_sub_iff_add_eq).2 hxid.symm
  · apply setIntegral_congr_fun measurableSet_Ioi
    intro x _hx
    simp only
    congr 1
    have hxid := integral_coherentCutoffBoundary_eq_companion_add_rankOne
      parent rho h U eta theta mass hh hU x
    exact (eq_sub_iff_add_eq).2 hxid.symm

end

end ArithmeticHodge.Analysis.MultiplicativeWeilCoherentCompensatedCutoffCrossStructural
