import ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedRowStructural
import ArithmeticHodge.Analysis.YoshidaFourCellEvenZeroCoshCoupledCoreStructural

set_option autoImplicit false

open MeasureTheory Polynomial Real Set

namespace ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedCutoffEightBridgeStructural

noncomputable section

open MultiplicativeWeilFourCellRealRescaleStructural
open ShiftedLegendreOrthogonality
open ShiftedLegendreLogEnergyOrthogonalProjection
open YoshidaEndpointEvenStructuralReduction
open YoshidaEndpointPotentialBound
open YoshidaFactorTwoEndpointBilinear
open YoshidaFactorTwoContinuousLagRepresenterStructural
open YoshidaFactorTwoIntegrableLagRepresenterStructural
open YoshidaFactorTwoPhaseIntrinsicNineP6EvenProfileCorrelationStructural
open YoshidaFactorTwoPhaseIntrinsicNineP6EvenCleanPolynomialGramStructural
open YoshidaFactorTwoPhaseIntrinsicNineCanonicalProjectionStructural
open YoshidaFactorTwoPhaseIntrinsicHigherResidual
open YoshidaFactorTwoPhaseIntrinsicSixP4EndpointProfile
open YoshidaFactorTwoPhaseIntrinsicSixSchurReduction
open YoshidaFactorTwoPhaseLegendreFourFiveStructural
open YoshidaFactorTwoPhaseLegendreSixSevenStructuralPositive
open YoshidaFactorTwoPhaseHigherLegendreDecomposition
open YoshidaFactorTwoPhaseLowSchur
open YoshidaFourCellEvenEndpointCapacityCauchyStructural
open YoshidaFourCellEvenEndpointCoshSchurStructural
open YoshidaFourCellEvenEndpointSeedRowStructural
open YoshidaFourCellEvenPolarSchurStructural
open YoshidaFourCellParityHalfFoldStructural
open YoshidaFourCellParityOperatorStructural
open YoshidaFourCellEvenZeroCoshCoupledCoreStructural
open YoshidaFourCellEvenZeroCoshRegularStructural
open YoshidaRegularKernelBound

/-!
# The endpoint seed in the cutoff-eight coordinates

The fixed outer Schur row uses the endpoint-zero seed `1 - x^2`.  The
cutoff-eight core proof uses the first four even Legendre coordinates.  This
file identifies the seed with its exact `P0/P2/P4/P6` vector and shows that
its mixed coupled-core row against a `P8+` residual is precisely the retained
endpoint-capacity row.  Thus no raw-log tail term survives in the outer
determinant.
-/

/-- The endpoint-zero seed is the exact low vector
`(2/3, -2/3, 0, 0)` in the cutoff-eight even Legendre basis. -/
theorem fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile :
    fourCellEvenEndpointCoshSeed =
      factorTwoIntrinsicEvenP0246Profile (2 / 3) (-2 / 3) 0 0 := by
  funext x
  unfold fourCellEvenEndpointCoshSeed
    factorTwoIntrinsicEvenP0246Profile
    factorTwoIntrinsicEvenP024Profile
    factorTwoEvenStructuralLowProfile
    factorTwoIntrinsicSixEvenTail centeredEvenP0 centeredEvenP2
  simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
  ring

/-- Symmetry of the retained endpoint-capacity polarization. -/
theorem fourCellEvenEndpointCapacityPolarization_comm
    (u v : ℝ → ℝ) :
    fourCellEvenEndpointCapacityPolarization u v =
      fourCellEvenEndpointCapacityPolarization v u := by
  have hpotential :
      (∫ x : ℝ in -1..1, yoshidaEndpointPotential x * u x * v x) =
        ∫ x : ℝ in -1..1,
          yoshidaEndpointPotential x * v x * u x := by
    apply intervalIntegral.integral_congr
    intro x _hx
    ring
  unfold fourCellEvenEndpointCapacityPolarization
  rw [hpotential, factorTwoCenteredCorrelationBilinear_comm]

/-- The one-variable Riesz representer of the smooth regular-kernel row
generated by the endpoint-zero seed. -/
def fourCellEvenEndpointSeedRegularTailRepresenter (x : ℝ) : ℝ :=
  factorTwoContinuousLagK
    (fun t : ℝ ↦ yoshidaRegularKernel (fourCellOperatorHalfWidth * t))
    fourCellEvenEndpointCoshSeed x

/-- A projected representer of the complete surviving endpoint-seed tail
row.  The capacity and smooth regular pieces stay combined pointwise. -/
def fourCellEvenEndpointSeedProjectedTailRowRepresenter
    (q : ℝ[X]) (x : ℝ) : ℝ :=
  fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
      (2 / 3) (-2 / 3) 0 0 q x -
    fourCellOperatorHalfWidth *
      fourCellEvenEndpointSeedRegularTailRepresenter x

private theorem fourCellRegularLag_abs_le_quarter
    (t : ℝ) (ht : t ∈ Icc (0 : ℝ) 2) :
    |yoshidaRegularKernel (fourCellOperatorHalfWidth * t)| ≤ 1 / 4 := by
  have ha0 : 0 ≤ fourCellOperatorHalfWidth := by
    unfold fourCellOperatorHalfWidth
    positivity
  have harg0 : 0 ≤ fourCellOperatorHalfWidth * t :=
    mul_nonneg ha0 ht.1
  have harg4 : fourCellOperatorHalfWidth * t ≤
      5 * Real.log 2 / 4 := by
    calc
      fourCellOperatorHalfWidth * t ≤ fourCellOperatorHalfWidth * 2 :=
        mul_le_mul_of_nonneg_left ht.2 ha0
      _ = 5 * Real.log 2 / 4 := by
        unfold fourCellOperatorHalfWidth
        ring
  have hk0 := yoshidaRegularKernel_nonneg_fourCellRange harg0 harg4
  rw [abs_of_nonneg hk0]
  exact yoshidaRegularKernel_le_quarter harg0

private theorem endpointSeedProfile_add_intrinsicEvenP0246
    (c0 c2 c4 c6 : ℝ) :
    factorTwoIntrinsicEvenP0246Profile (2 / 3) (-2 / 3) 0 0 +
        factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 =
      factorTwoIntrinsicEvenP0246Profile
        (2 / 3 + c0) (-2 / 3 + c2) c4 c6 := by
  funext x
  unfold factorTwoIntrinsicEvenP0246Profile
    factorTwoIntrinsicEvenP024Profile
    factorTwoEvenStructuralLowProfile
    factorTwoIntrinsicSixEvenTail centeredEvenP0 centeredEvenP2
  simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
  ring

/-- The exact four-coordinate coupled-core row of the endpoint seed on the
finite cutoff-eight block. -/
def fourCellEvenEndpointSeedP0246CoreRow
    (c0 c2 c4 c6 : ℝ) : ℝ :=
  ((10 / 9 : ℝ) - (4 / 3) * Real.log 2 -
      (52 / 375) * Real.sqrt 2 * Real.log 2) * c0 +
    (-(122 / 225 : ℝ) + (4 / 15) * Real.log 2 -
      (4076 / 46875) * Real.sqrt 2 * Real.log 2) * c2 +
    (-(1 / 35 : ℝ) -
      (4544 / 234375) * Real.sqrt 2 * Real.log 2) * c4 +
    (-(1 / 189 : ℝ) +
      (16576 / 1953125) * Real.sqrt 2 * Real.log 2) * c6

/-- The complete finite endpoint-seed row on the `P0/P2/P4/P6` block. -/
def fourCellEvenEndpointSeedP0246CompleteLowRow
    (c0 c2 c4 c6 : ℝ) : ℝ :=
  fourCellEvenEndpointSeedP0246CoreRow c0 c2 c4 c6 -
    fourCellEvenSignedMassRegularPolarization
      fourCellEvenEndpointCoshSeed
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6)

/-- Exact evaluation of the finite endpoint-seed coupled-core row.  This
turns the outer low block into one explicit four-vector; no interval or
analytic estimate enters the identity. -/
theorem fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_P0246_eq
    (c0 c2 c4 c6 : ℝ) :
    fourCellEvenZeroCoshCoupledCorePolarization
        fourCellEvenEndpointCoshSeed
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) =
      fourCellEvenEndpointSeedP0246CoreRow c0 c2 c4 c6 := by
  rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
  unfold fourCellEvenZeroCoshCoupledCorePolarization
  rw [endpointSeedProfile_add_intrinsicEvenP0246,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246Profile_eq_gram,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246Profile_eq_gram,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246Profile_eq_gram]
  unfold fourCellEvenEndpointSeedP0246CoreRow
    factorTwoP6EvenRawLogGram factorTwoP6EvenPotentialGram
  ring

/-- Against a genuine `P8+` tail, the endpoint seed has no raw-log mixed
entry.  Its complete coupled-core polarization is exactly the retained
endpoint-potential/prime capacity polarization. -/
theorem
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_tail_eq_capacity
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenZeroCoshCoupledCorePolarization
        fourCellEvenEndpointCoshSeed r =
      fourCellEvenEndpointCapacityPolarization
        fourCellEvenEndpointCoshSeed r := by
  rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
  unfold fourCellEvenZeroCoshCoupledCorePolarization
  rw [fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246_add_tail
    (2 / 3) (-2 / 3) 0 0 r hr hlocal hlow]
  ring

/-- Orthogonality removes the scalar-mass part of the signed endpoint-seed
row on a `P8+` tail.  Only the smooth regular-kernel row survives. -/
theorem fourCellEvenSignedMassRegularPolarization_endpointSeed_tail_eq_regular
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenSignedMassRegularPolarization
        fourCellEvenEndpointCoshSeed r =
      2 * fourCellOperatorHalfWidth *
        (∫ t : ℝ in 0..2,
          yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
            factorTwoCenteredCorrelationBilinear
              fourCellEvenEndpointCoshSeed r t) := by
  rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
  have hmass := intervalIntegral_intrinsicEvenP0246_mul_tail_eq_zero
    (2 / 3) (-2 / 3) 0 0 r hr hlow
  unfold fourCellEvenSignedMassRegularPolarization
  rw [hmass]
  ring

/-- Exact projected-representer identity for the complete endpoint-seed tail
row.  The arbitrary selector has degree below eight, so the tail annihilates
it; the remaining smooth correlation is converted by Fubini to its symmetric
one-variable lag representer. -/
theorem fourCellEvenEndpointSeedTailRow_eq_projectedRepresenterPairing
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlow : centeredLegendreMomentsVanishBelow r 8)
    (q : ℝ[X]) (hq : q.natDegree < 8) :
    fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed r t) =
      ∫ x : ℝ in -1..1,
        fourCellEvenEndpointSeedProjectedTailRowRepresenter q x * r x := by
  let k : ℝ → ℝ := fun t ↦
    yoshidaRegularKernel (fourCellOperatorHalfWidth * t)
  have hk : Measurable k := by
    dsimp only [k]
    exact measurable_yoshidaRegularKernel.comp
      (measurable_const.mul measurable_id)
  have hkbound : ∀ t ∈ Icc (0 : ℝ) 2, |k t| ≤ 1 / 4 := by
    intro t ht
    simpa only [k] using fourCellRegularLag_abs_le_quarter t ht
  have hcap :
      fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r =
        ∫ x : ℝ in -1..1,
          fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
            (2 / 3) (-2 / 3) 0 0 q x * r x := by
    rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
    exact
      fourCellEvenEndpointCapacityPolarization_P0246_eq_projectedRepresenterPairing
        (2 / 3) (-2 / 3) 0 0 r hr hlow q hq
  have hregular := integral_boundedLag_mul_correlationBilinear_eq_K
    k fourCellEvenEndpointCoshSeed r hk
      fourCellEvenEndpointCoshSeed_continuous hr (1 / 4) hkbound
  have hcapBase :=
    intervalIntegrable_fourCellEvenP0246CutoffEightCapacityRepresenter_mul
      (2 / 3) (-2 / 3) 0 0 r hr
  have hpoly : IntervalIntegrable
      (fun x : ℝ ↦ centeredPolynomialLift q x * r x) volume (-1) 1 :=
    ((by
      unfold centeredPolynomialLift
      fun_prop : Continuous (centeredPolynomialLift q)).mul hr).intervalIntegrable
        (-1) 1
  have hcapInt : IntervalIntegrable
      (fun x : ℝ ↦
        fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
          (2 / 3) (-2 / 3) 0 0 q x * r x) volume (-1) 1 := by
    apply (hcapBase.sub hpoly).congr
    intro x _hx
    unfold fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
    ring
  have hright :=
    intervalIntegrable_mul_factorTwoContinuousLagRightRepresenter_of_bounded
      k fourCellEvenEndpointCoshSeed r hk
        fourCellEvenEndpointCoshSeed_continuous hr (1 / 4) hkbound
  have hleft :=
    intervalIntegrable_mul_factorTwoContinuousLagLeftRepresenter_of_bounded
      k r fourCellEvenEndpointCoshSeed hk hr
        fourCellEvenEndpointCoshSeed_continuous (1 / 4) hkbound
  have hK : IntervalIntegrable
      (fun x : ℝ ↦ r x *
        factorTwoContinuousLagK k fourCellEvenEndpointCoshSeed x)
      volume (-1) 1 := by
    apply (hright.add hleft).congr
    intro x _hx
    unfold factorTwoContinuousLagK
    ring
  rw [hcap, hregular]
  rw [show (fun x : ℝ ↦
      fourCellEvenEndpointSeedProjectedTailRowRepresenter q x * r x) =
      fun x ↦
        fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
            (2 / 3) (-2 / 3) 0 0 q x * r x -
          fourCellOperatorHalfWidth *
            (r x * factorTwoContinuousLagK
              k fourCellEvenEndpointCoshSeed x) by
    funext x
    unfold fourCellEvenEndpointSeedProjectedTailRowRepresenter
      fourCellEvenEndpointSeedRegularTailRepresenter
    dsimp only [k]
    ring,
    intervalIntegral.integral_sub hcapInt
      (hK.const_mul fourCellOperatorHalfWidth),
    intervalIntegral.integral_const_mul]
  ring

/-- Exact mixed-row decomposition for the complete cutoff-eight split.  The
seed-to-low term is finite-dimensional, while the seed-to-tail term is the
single retained endpoint-capacity row. -/
theorem
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_P0246_add_tail
    (c0 c2 c4 c6 : ℝ) (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenZeroCoshCoupledCorePolarization
        fourCellEvenEndpointCoshSeed
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) =
      fourCellEvenZeroCoshCoupledCorePolarization
          fourCellEvenEndpointCoshSeed
          (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r := by
  let s : ℝ → ℝ :=
    factorTwoIntrinsicEvenP0246Profile (2 / 3) (-2 / 3) 0 0
  let p : ℝ → ℝ :=
    factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  let q : ℝ → ℝ :=
    factorTwoIntrinsicEvenP0246Profile
      (2 / 3 + c0) (-2 / 3 + c2) c4 c6
  have hs : Continuous s := by
    simpa only [s] using
      continuous_factorTwoIntrinsicEvenP0246Profile
        (2 / 3) (-2 / 3) 0 0
  have hp : Continuous p := by
    simpa only [p] using
      continuous_factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  have hsp : s + p = q := by
    simpa only [s, p, q] using
      endpointSeedProfile_add_intrinsicEvenP0246 c0 c2 c4 c6
  have hsall : s + (p + r) = q + r := by
    rw [← hsp]
    exact (add_assoc s p r).symm
  have hcapacity :
      fourCellEvenEndpointCapacityPolarization q r =
        fourCellEvenEndpointCapacityPolarization s r +
          fourCellEvenEndpointCapacityPolarization p r := by
    rw [← hsp,
      fourCellEvenEndpointCapacityPolarization_comm (s + p) r,
      fourCellEvenEndpointCapacityPolarization_add_right r s p hr hs hp,
      fourCellEvenEndpointCapacityPolarization_comm r s,
      fourCellEvenEndpointCapacityPolarization_comm r p]
  rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
  change fourCellEvenZeroCoshCoupledCorePolarization s (p + r) =
    fourCellEvenZeroCoshCoupledCorePolarization s p +
      fourCellEvenEndpointCapacityPolarization s r
  unfold fourCellEvenZeroCoshCoupledCorePolarization
  rw [hsall,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246_add_tail
      (2 / 3 + c0) (-2 / 3 + c2) c4 c6 r hr hlocal hlow,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246_add_tail
      c0 c2 c4 c6 r hr hlocal hlow,
    hsp, hcapacity]
  ring

/-- Exact fixed-row normal form on the cutoff-eight tail.  The singular
coupled core has collapsed to the one capacity row, while the signed
mass/regular row remains coupled rather than being bounded separately. -/
theorem fourCellEvenEndpointSeedRow_tail_eq_capacity_sub_signed
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (heven : Function.Even r)
    (hzero : fourCellPositiveCoshMoment r
      (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow r =
      fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        fourCellEvenSignedMassRegularPolarization
          fourCellEvenEndpointCoshSeed r := by
  rw [fourCellEvenEndpointSeedRow_eq_core_sub_signed r hr hlocal heven hzero,
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_tail_eq_capacity
      r hr hlocal hlow]

/-- On the cutoff-eight tail the complete fixed row contains exactly two
opposing terms: the endpoint-capacity row and the smooth regular-kernel row.
Both singular raw energy and scalar mass vanish by Legendre orthogonality. -/
theorem fourCellEvenEndpointSeedRow_tail_eq_capacity_sub_regular
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (heven : Function.Even r)
    (hzero : fourCellPositiveCoshMoment r
      (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow r =
      fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed r t) := by
  rw [fourCellEvenEndpointSeedRow_tail_eq_capacity_sub_signed
      r hr hlocal heven hzero hlow,
    fourCellEvenSignedMassRegularPolarization_endpointSeed_tail_eq_regular
      r hr hlow]

/-- Full fixed-row normal form after the canonical cutoff-eight split.  This
is the exact outer determinant row: one finite `P0246` core entry, one
endpoint-capacity tail entry, and the still-coupled signed mass/regular row. -/
theorem fourCellEvenEndpointSeedRow_P0246_add_tail_eq
    (c0 c2 c4 c6 : ℝ) (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hre : Function.Even r)
    (hzero : fourCellPositiveCoshMoment
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r)
        (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) =
      fourCellEvenZeroCoshCoupledCorePolarization
          fourCellEvenEndpointCoshSeed
          (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        fourCellEvenSignedMassRegularPolarization
          fourCellEvenEndpointCoshSeed
          (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) := by
  let p : ℝ → ℝ :=
    factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  have hp : Continuous p := by
    simpa only [p] using
      continuous_factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  have hpPoly : p = fun x : ℝ ↦
      c0 + c2 * ((3 * x ^ 2 - 1) / 2) +
        c4 * ((35 * x ^ 4 - 30 * x ^ 2 + 3) / 8) +
          c6 * ((231 * x ^ 6 - 315 * x ^ 4 + 105 * x ^ 2 - 5) / 16) := by
    funext x
    dsimp only [p]
    unfold factorTwoIntrinsicEvenP0246Profile
      factorTwoIntrinsicEvenP024Profile
      factorTwoEvenStructuralLowProfile
      factorTwoIntrinsicSixEvenTail centeredEvenP0 centeredEvenP2
      factorTwoCenteredP4
    simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
    rw [factorTwoCenteredP6_eq]
    ring
  have hpDiff : ContDiff ℝ 1 p := by
    rw [hpPoly]
    fun_prop
  have hpLocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) p :=
    hpDiff.contDiffOn.locallyLipschitzOn (convex_Icc (-1 : ℝ) 1)
  have hpe : Function.Even p := by
    simpa only [p] using
      even_factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  have hrow := fourCellEvenEndpointSeedRow_eq_core_sub_signed
    (p + r) (hp.add hr) (hpLocal.add hlocal) (hpe.add hre)
      (by simpa only [p] using hzero)
  rw [fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_P0246_add_tail
    c0 c2 c4 c6 r hr hlocal hlow] at hrow
  simpa only [p] using hrow

/-- Coordinate form of the complete fixed endpoint-seed row.  The entire
finite contribution is the explicit four-vector above. -/
theorem fourCellEvenEndpointSeedRow_P0246_add_tail_eq_explicit
    (c0 c2 c4 c6 : ℝ) (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hre : Function.Even r)
    (hzero : fourCellPositiveCoshMoment
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r)
        (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) =
      fourCellEvenEndpointSeedP0246CoreRow c0 c2 c4 c6 +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        fourCellEvenSignedMassRegularPolarization
          fourCellEvenEndpointCoshSeed
          (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) := by
  rw [fourCellEvenEndpointSeedRow_P0246_add_tail_eq
    c0 c2 c4 c6 r hr hlocal hre hzero hlow,
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_P0246_eq]

/-- Fully separated outer row for the cutoff-eight split.  The first summand
is a fixed four-dimensional row.  The tail contributes only its endpoint
capacity row minus the smooth regular-kernel row; no scalar mass or raw-log
cross term remains. -/
theorem fourCellEvenEndpointSeedRow_P0246_add_tail_eq_low_add_tail
    (c0 c2 c4 c6 : ℝ) (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hre : Function.Even r)
    (hzero : fourCellPositiveCoshMoment
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r)
        (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) =
      fourCellEvenEndpointSeedP0246CompleteLowRow c0 c2 c4 c6 +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed r t) := by
  have hp : Continuous
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) :=
    continuous_factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  rw [fourCellEvenEndpointSeedRow_P0246_add_tail_eq_explicit
      c0 c2 c4 c6 r hr hlocal hre hzero hlow,
    fourCellEvenSignedMassRegularPolarization_add_right
      fourCellEvenEndpointCoshSeed
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) r
      fourCellEvenEndpointCoshSeed_continuous hp hr,
    fourCellEvenSignedMassRegularPolarization_endpointSeed_tail_eq_regular
      r hr hlow]
  unfold fourCellEvenEndpointSeedP0246CompleteLowRow
  ring

/-- Canonical cutoff-eight normal form of the endpoint-seed row for an
arbitrary even zero-cosh profile. -/
theorem fourCellEvenEndpointSeedRow_eq_canonicalCutoffEightLow_add_tail
    (w : ℝ → ℝ) (hw : Continuous w)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) w)
    (heven : Function.Even w)
    (hzero : fourCellPositiveCoshMoment w
      (fourCellOperatorHalfWidth / 2) = 0) :
    fourCellEvenEndpointSeedRow w =
      fourCellEvenEndpointSeedP0246CompleteLowRow
          (factorTwoCanonicalLegendreCoefficient w hw 0)
          (factorTwoCanonicalLegendreCoefficient w hw 2)
          (factorTwoCanonicalLegendreCoefficient w hw 4)
          (factorTwoCanonicalLegendreCoefficient w hw 6) +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed
          (centeredLegendreHigherResidual w hw 8) -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed
                (centeredLegendreHigherResidual w hw 8) t) := by
  let c0 : ℝ := factorTwoCanonicalLegendreCoefficient w hw 0
  let c2 : ℝ := factorTwoCanonicalLegendreCoefficient w hw 2
  let c4 : ℝ := factorTwoCanonicalLegendreCoefficient w hw 4
  let c6 : ℝ := factorTwoCanonicalLegendreCoefficient w hw 6
  let p : ℝ → ℝ := factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  let r : ℝ → ℝ := centeredLegendreHigherResidual w hw 8
  have hpEq : centeredLegendreLowProjection w hw 8 = p := by
    simpa only [c0, c2, c4, c6, p] using
      centeredLegendreLowProjection_eight_eq_intrinsicEvenP0246Profile
        w hw heven
  have hsum : p + r = w := by
    rw [← hpEq]
    simpa only [r] using
      centeredLegendreLowProjection_add_higherResidual w hw 8
  have hr : Continuous r := by
    simpa only [r] using continuous_centeredLegendreHigherResidual w hw 8
  have hrLocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r := by
    simpa only [r] using
      locallyLipschitzOn_centeredLegendreHigherResidual w hw hlocal 8
  have hrEven : Function.Even r := by
    simpa only [r] using
      centeredLegendreHigherResidual_even w hw heven 8
  have hrGap : centeredLegendreMomentsVanishBelow r 8 := by
    simpa only [r] using
      centeredLegendreHigherResidual_momentsVanishBelow w hw 8
  have hzeroSplit : fourCellPositiveCoshMoment (p + r)
      (fourCellOperatorHalfWidth / 2) = 0 := by
    rw [hsum]
    exact hzero
  have hrow :=
    fourCellEvenEndpointSeedRow_P0246_add_tail_eq_low_add_tail
      c0 c2 c4 c6 r hr hrLocal hrEven hzeroSplit hrGap
  rw [hsum] at hrow
  simpa only [c0, c2, c4, c6, r] using hrow

end

end ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedCutoffEightBridgeStructural
