/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 059; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks058

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row103_001_le :
    evenSparseDominanceBlockContribution (103 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (103 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row103_002_le :
    evenSparseDominanceBlockContribution (103 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (103 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row104_000_le :
    evenSparseDominanceBlockContribution (104 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (104 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row104_001_le :
    evenSparseDominanceBlockContribution (104 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (104 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row104_002_le :
    evenSparseDominanceBlockContribution (104 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (104 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row105_000_le :
    evenSparseDominanceBlockContribution (105 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (105 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row105_001_le :
    evenSparseDominanceBlockContribution (105 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (105 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row105_002_le :
    evenSparseDominanceBlockContribution (105 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (105 : YoshidaEvenIndex) 2 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
