/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 036; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks035

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row053_000_le :
    evenSparseDominanceBlockContribution (53 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (53 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row053_001_le :
    evenSparseDominanceBlockContribution (53 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (53 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row053_002_le :
    evenSparseDominanceBlockContribution (53 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (53 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row053_003_le :
    evenSparseDominanceBlockContribution (53 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (53 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row054_000_le :
    evenSparseDominanceBlockContribution (54 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (54 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row054_001_le :
    evenSparseDominanceBlockContribution (54 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (54 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row054_002_le :
    evenSparseDominanceBlockContribution (54 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (54 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row054_003_le :
    evenSparseDominanceBlockContribution (54 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (54 : YoshidaEvenIndex) 3 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
