/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 028; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks027

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row037_004_le :
    evenSparseDominanceBlockContribution (37 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (37 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row038_000_le :
    evenSparseDominanceBlockContribution (38 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (38 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row038_001_le :
    evenSparseDominanceBlockContribution (38 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (38 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row038_002_le :
    evenSparseDominanceBlockContribution (38 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (38 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row038_003_le :
    evenSparseDominanceBlockContribution (38 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (38 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row038_004_le :
    evenSparseDominanceBlockContribution (38 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (38 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row039_000_le :
    evenSparseDominanceBlockContribution (39 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (39 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row039_001_le :
    evenSparseDominanceBlockContribution (39 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (39 : YoshidaEvenIndex) 1 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
