import ArithmeticHodge.Analysis.YoshidaFourCellOddStripCapacityClosureStructural

set_option autoImplicit false

open MeasureTheory Real Set

namespace ArithmeticHodge.Analysis.YoshidaFourCellOddP11EndpointFormDualClosureStructural

noncomputable section

open YoshidaFactorTwoContinuousLagRepresenterStructural
open YoshidaFactorTwoEndpointBilinear
open YoshidaFactorTwoIntegrableLagRepresenterStructural
open CenteredOddOneThreeEnergy
open YoshidaEndpointOddResidualRegularity
open YoshidaEndpointOcticPotential
open YoshidaEndpointPotentialBound
open YoshidaFourCellOddEndpointStripCoercivityStructural
open YoshidaFourCellOddStripCapacityClosureStructural
open YoshidaFourCellParityOperatorStructural
open YoshidaFourCellRegularKernelWideEnvelope
open YoshidaRegularKernelBound

/-!
# The one-variable regular representer on the odd `P11+` frontier

The exact five-mode/`P11+` mixed row has no global logarithmic cross and no
scalar-mass cross.  Its remaining smooth correlation is written here as a
one-variable Riesz representer.  This is an equality, not a separate norm
estimate, so the regular row can still cancel against the endpoint-strip,
prime, and potential rows in the final dual certificate.
-/

/-- The symmetric wide-regular representer generated by the retained odd
`P1/P3/P5/P7/P9` profile. -/
def fourCellOddFiveModeRegularRepresenter
    (c d e f g : ℝ) (x : ℝ) : ℝ :=
  factorTwoContinuousLagK
    (fun t : ℝ ↦
      yoshidaRegularKernel (fourCellOperatorHalfWidth * t))
    (fourCellOddOneThreeFiveSevenNineLowProfile c d e f g) x

/-- The strip-even prime row generated by `P1` is just the physical mean
of the residual on the positive endpoint strip. -/
theorem fourCellOddEndpointStripEvenMassBilinear_P1_eq
    (r : ℝ → ℝ) (hr : Continuous r) :
    fourCellOddEndpointStripEvenMassBilinear centeredP1 r =
      (4 / 5 : ℝ) * ∫ x : ℝ in 3 / 5..1, r x := by
  have hplus := intervalIntegral.integral_comp_add_mul
    (a := (-1 : ℝ)) (b := 1) (f := r)
      (by norm_num : (1 / 5 : ℝ) ≠ 0) (4 / 5)
  have hminus := intervalIntegral.integral_comp_sub_mul
    (a := (-1 : ℝ)) (b := 1) (f := r)
      (by norm_num : (1 / 5 : ℝ) ≠ 0) (4 / 5)
  unfold fourCellOddEndpointStripEvenMassBilinear
    fourCellOddEndpointStripEven fourCellOddEndpointStripPullback
    centeredP1
  rw [show (fun z : ℝ ↦
      ((4 / 5 + z / 5 + (4 / 5 + -z / 5)) / 2) *
        ((r (4 / 5 + z / 5) + r (4 / 5 + -z / 5)) / 2)) =
      fun z ↦ (2 / 5 : ℝ) * r (4 / 5 + (1 / 5) * z) +
        (2 / 5 : ℝ) * r (4 / 5 - (1 / 5) * z) by
    funext z
    ring,
    intervalIntegral.integral_add
      (Continuous.intervalIntegrable (by fun_prop) (-1) 1)
      (Continuous.intervalIntegrable (by fun_prop) (-1) 1),
    intervalIntegral.integral_const_mul,
    intervalIntegral.integral_const_mul,
    hplus, hminus]
  simp only [smul_eq_mul]
  norm_num
  ring

/-- The strip-odd prime row generated by `P1` is the centered affine
coordinate on the same endpoint strip. -/
theorem fourCellOddEndpointStripOddMassBilinear_P1_eq
    (r : ℝ → ℝ) (hr : Continuous r) :
    fourCellOddEndpointStripOddMassBilinear centeredP1 r =
      ∫ x : ℝ in 3 / 5..1, (x - 4 / 5) * r x := by
  let F : ℝ → ℝ := fun x ↦ (x - 4 / 5) * r x
  have hplus := intervalIntegral.integral_comp_add_mul
    (a := (-1 : ℝ)) (b := 1) (f := F)
      (by norm_num : (1 / 5 : ℝ) ≠ 0) (4 / 5)
  have hminus := intervalIntegral.integral_comp_sub_mul
    (a := (-1 : ℝ)) (b := 1) (f := F)
      (by norm_num : (1 / 5 : ℝ) ≠ 0) (4 / 5)
  unfold fourCellOddEndpointStripOddMassBilinear
    fourCellOddEndpointStripOdd fourCellOddEndpointStripPullback
    centeredP1
  rw [show (fun z : ℝ ↦
      ((4 / 5 + z / 5 - (4 / 5 + -z / 5)) / 2) *
        ((r (4 / 5 + z / 5) - r (4 / 5 + -z / 5)) / 2)) =
      fun z ↦ (z / 10 : ℝ) * r (4 / 5 + (1 / 5) * z) +
        (-z / 10 : ℝ) * r (4 / 5 - (1 / 5) * z) by
    funext z
    ring,
    intervalIntegral.integral_add
      (Continuous.intervalIntegrable (by fun_prop) (-1) 1)
      (Continuous.intervalIntegrable (by fun_prop) (-1) 1)]
  rw [show (fun z : ℝ ↦
      (z / 10 : ℝ) * r (4 / 5 + (1 / 5) * z)) =
      fun z ↦ (1 / 2 : ℝ) * F (4 / 5 + (1 / 5) * z) by
        funext z
        dsimp only [F]
        ring,
    show (fun z : ℝ ↦
      (-z / 10 : ℝ) * r (4 / 5 - (1 / 5) * z)) =
      fun z ↦ (1 / 2 : ℝ) * F (4 / 5 - (1 / 5) * z) by
        funext z
        dsimp only [F]
        ring,
    intervalIntegral.integral_const_mul,
    intervalIntegral.integral_const_mul,
    hplus, hminus]
  simp only [smul_eq_mul]
  norm_num
  dsimp only [F]
  ring

/-- On the degree-one row the adverse strip logarithmic polarization is
exactly four times the strip-odd physical polarization. -/
theorem fourCellOddEndpointStripOddRawPolarization_P1_eq_four_mul_mass
    (r : ℝ → ℝ) (hr : ContDiff ℝ 1 r) :
    fourCellOddEndpointStripOddRawPolarization centeredP1 r =
      4 * fourCellOddEndpointStripOddMassBilinear centeredP1 r := by
  have hraw :=
    fourCellOddEndpointStripOddRawPolarization_oneThreeFive_eq_moments
      r hr 1 0 0
  have hp : fourCellOddOneThreeFiveLowProfile 1 0 0 = centeredP1 := by
    funext x
    unfold fourCellOddOneThreeFiveLowProfile
      factorTwoOddStructuralLowProfile
    simp
  rw [hp] at hraw
  norm_num at hraw
  have hstripP1 : fourCellOddEndpointStripOdd centeredP1 =
      fun z : ℝ ↦ z / 5 := by
    funext z
    unfold fourCellOddEndpointStripOdd fourCellOddEndpointStripPullback
      centeredP1
    ring
  rw [hraw]
  unfold fourCellOddEndpointStripOddMassBilinear
  rw [hstripP1]
  unfold centeredP1 at hraw ⊢
  rw [show (fun z : ℝ ↦
      z / 5 * fourCellOddEndpointStripOdd r z) =
      fun z ↦ (1 / 5 : ℝ) *
        (fourCellOddEndpointStripOdd r z * z) by
    funext z
    ring,
    intervalIntegral.integral_const_mul]
  ring

private theorem fourCellRegularLag_abs_le_quarter
    (t : ℝ) (ht : t ∈ Icc (0 : ℝ) 2) :
    |yoshidaRegularKernel (fourCellOperatorHalfWidth * t)| ≤ 1 / 4 := by
  have ha0 : 0 ≤ fourCellOperatorHalfWidth := by
    unfold fourCellOperatorHalfWidth
    positivity
  have harg0 : 0 ≤ fourCellOperatorHalfWidth * t :=
    mul_nonneg ha0 ht.1
  have harg4 : fourCellOperatorHalfWidth * t ≤
      5 * Real.log 2 / 4 := by
    calc
      fourCellOperatorHalfWidth * t ≤ fourCellOperatorHalfWidth * 2 :=
        mul_le_mul_of_nonneg_left ht.2 ha0
      _ = 5 * Real.log 2 / 4 := by
        unfold fourCellOperatorHalfWidth
        ring
  have hk0 := yoshidaRegularKernel_nonneg_fourCellRange harg0 harg4
  rw [abs_of_nonneg hk0]
  exact yoshidaRegularKernel_le_quarter harg0

/-- Fubini turns the complete smooth five-mode/tail correlation into the
pairing with `fourCellOddFiveModeRegularRepresenter`. -/
theorem two_mul_width_mul_regularCorrelation_fiveMode_eq_representer
    (r : ℝ → ℝ) (hr : Continuous r) (c d e f g : ℝ) :
    2 * fourCellOperatorHalfWidth *
        (∫ t : ℝ in 0..2,
          yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
            factorTwoCenteredCorrelationBilinear
              (fourCellOddOneThreeFiveSevenNineLowProfile c d e f g) r t) =
      fourCellOperatorHalfWidth *
        (∫ x : ℝ in -1..1,
          r x * fourCellOddFiveModeRegularRepresenter c d e f g x) := by
  let k : ℝ → ℝ := fun t ↦
    yoshidaRegularKernel (fourCellOperatorHalfWidth * t)
  let p : ℝ → ℝ :=
    fourCellOddOneThreeFiveSevenNineLowProfile c d e f g
  have hk : Measurable k := by
    dsimp only [k]
    exact measurable_yoshidaRegularKernel.comp
      (measurable_const.mul measurable_id)
  have hp : Continuous p := by
    dsimp only [p]
    exact (contDiff_fourCellOddOneThreeFiveSevenNineLowProfile
      c d e f g).continuous
  have hkbound : ∀ t ∈ Icc (0 : ℝ) 2, |k t| ≤ 1 / 4 := by
    intro t ht
    simpa only [k] using fourCellRegularLag_abs_le_quarter t ht
  have hregular := integral_boundedLag_mul_correlationBilinear_eq_K
    k p r hk hp hr (1 / 4) hkbound
  change 2 * fourCellOperatorHalfWidth *
      (∫ t : ℝ in 0..2,
        k t * factorTwoCenteredCorrelationBilinear p r t) =
    fourCellOperatorHalfWidth *
      (∫ x : ℝ in -1..1,
        r x * fourCellOddFiveModeRegularRepresenter c d e f g x)
  rw [hregular]
  dsimp only [fourCellOddFiveModeRegularRepresenter, k, p]
  ring

/-- Exact one-variable normal form of the unresolved mixed row.  The two
singular/endpoint terms are kept intact, while the smooth lag integral is
now in the same Riesz coordinate as them. -/
theorem fourCellOddCoreLocalBilinear_fiveMode_P11Plus_eq_regularRepresenter
    (r : ℝ → ℝ) (hr : ContDiff ℝ 1 r) (hodd : Function.Odd r)
    (hone : centeredOddP1Coefficient r = 0)
    (hthree : centeredOddP3Coefficient r = 0)
    (hfive : centeredOddP5Coefficient r = 0)
    (hseven : centeredOddP7Coefficient r = 0)
    (hnine : centeredOddP9Coefficient r = 0)
    (c d e f g : ℝ) :
    fourCellOddCoreLocalBilinear
        (fourCellOddOneThreeFiveSevenNineLowProfile c d e f g) r =
      -(1 / 2 : ℝ) * fourCellOddEndpointStripOddRawPolarization
          (fourCellOddOneThreeFiveSevenNineLowProfile c d e f g) r +
        fourCellOddRetainedPrimePotentialBilinear
          (fourCellOddOneThreeFiveSevenNineLowProfile c d e f g) r -
        fourCellOperatorHalfWidth *
          (∫ x : ℝ in -1..1,
            r x * fourCellOddFiveModeRegularRepresenter c d e f g x) := by
  rw [fourCellOddCoreLocalBilinear_fiveMode_P11Plus_fullyReduced
      r hr hodd hone hthree hfive hseven hnine c d e f g,
    two_mul_width_mul_regularCorrelation_fiveMode_eq_representer
      r hr.continuous c d e f g]

/-- The sole extension row left after restricting the quadratic form to the
`P1`-orthogonal odd subspace.  On this row the adverse raw strip and the two
prime channels collapse exactly to the affine endpoint density
`sqrt 2 * log 2 * (8/5 - x)`; the potential and smooth representer remain
uncollapsed for the final weighted dual estimate. -/
theorem fourCellOddCoreLocalBilinear_P1_P11Plus_eq_affineEndpointRepresenter
    (r : ℝ → ℝ) (hr : ContDiff ℝ 1 r) (hodd : Function.Odd r)
    (hone : centeredOddP1Coefficient r = 0)
    (hthree : centeredOddP3Coefficient r = 0)
    (hfive : centeredOddP5Coefficient r = 0)
    (hseven : centeredOddP7Coefficient r = 0)
    (hnine : centeredOddP9Coefficient r = 0) :
    fourCellOddCoreLocalBilinear centeredP1 r =
      Real.sqrt 2 * Real.log 2 *
          (∫ x : ℝ in 3 / 5..1, (8 / 5 - x) * r x) +
        (93 / 50 : ℝ) *
          (∫ x : ℝ in 0..1,
            yoshidaEndpointPotential x * x * r x) -
        fourCellOperatorHalfWidth *
          (∫ x : ℝ in -1..1,
            r x * fourCellOddFiveModeRegularRepresenter 1 0 0 0 0 x) := by
  have hp :
      fourCellOddOneThreeFiveSevenNineLowProfile 1 0 0 0 0 = centeredP1 := by
    funext x
    unfold fourCellOddOneThreeFiveSevenNineLowProfile
      fourCellOddOneThreeFiveLowProfile factorTwoOddStructuralLowProfile
    simp
  have hrow :=
    fourCellOddCoreLocalBilinear_fiveMode_P11Plus_eq_regularRepresenter
      r hr hodd hone hthree hfive hseven hnine 1 0 0 0 0
  rw [hp] at hrow
  have hraw :=
    fourCellOddEndpointStripOddRawPolarization_P1_eq_four_mul_mass r hr
  have heven :=
    fourCellOddEndpointStripEvenMassBilinear_P1_eq r hr.continuous
  have hstripOdd :=
    fourCellOddEndpointStripOddMassBilinear_P1_eq r hr.continuous
  have hfirst : IntervalIntegrable
      (fun x : ℝ ↦ (4 / 5 : ℝ) * r x) volume (3 / 5) 1 :=
    (hr.continuous.const_mul (4 / 5 : ℝ)).intervalIntegrable _ _
  have hsecond : IntervalIntegrable
      (fun x : ℝ ↦ (x - 4 / 5) * r x) volume (3 / 5) 1 :=
    ((continuous_id.sub continuous_const).mul hr.continuous)
      |>.intervalIntegrable _ _
  have hstrip :
      (4 / 5 : ℝ) * (∫ x : ℝ in 3 / 5..1, r x) -
          (∫ x : ℝ in 3 / 5..1, (x - 4 / 5) * r x) =
        ∫ x : ℝ in 3 / 5..1, (8 / 5 - x) * r x := by
    rw [← intervalIntegral.integral_const_mul,
      ← intervalIntegral.integral_sub hfirst hsecond]
    apply intervalIntegral.integral_congr
    intro x _hx
    ring
  calc
    fourCellOddCoreLocalBilinear centeredP1 r =
        -(1 / 2 : ℝ) *
            fourCellOddEndpointStripOddRawPolarization centeredP1 r +
          fourCellOddRetainedPrimePotentialBilinear centeredP1 r -
          fourCellOperatorHalfWidth *
            (∫ x : ℝ in -1..1,
              r x *
                fourCellOddFiveModeRegularRepresenter 1 0 0 0 0 x) := hrow
    _ = Real.sqrt 2 * Real.log 2 *
          ((4 / 5 : ℝ) * (∫ x : ℝ in 3 / 5..1, r x) -
            ∫ x : ℝ in 3 / 5..1, (x - 4 / 5) * r x) +
        (93 / 50 : ℝ) *
          (∫ x : ℝ in 0..1,
            yoshidaEndpointPotential x * x * r x) -
        fourCellOperatorHalfWidth *
          (∫ x : ℝ in -1..1,
            r x * fourCellOddFiveModeRegularRepresenter 1 0 0 0 0 x) := by
      rw [hraw]
      unfold fourCellOddRetainedPrimePotentialBilinear
      rw [heven, hstripOdd]
      unfold centeredP1
      ring
    _ = _ := by rw [hstrip]

end

end ArithmeticHodge.Analysis.YoshidaFourCellOddP11EndpointFormDualClosureStructural
