import ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024Structural
import ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedSelectorHomogeneityStructural

set_option autoImplicit false

open Polynomial Real Set

namespace ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorStructural

open ThreeByThreeRankOneSchur
open ShiftedLegendreLogEnergyOrthogonalProjection
open ShiftedLegendreOrthogonality
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedConstrainedWeightedDualStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024Structural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedRepresentersStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedSelectorHomogeneityStructural
open YoshidaFactorTwoPhaseIntrinsicFourP45MixedExpansion
open YoshidaFactorTwoPhaseIntrinsicSixP4EndpointProfile
open YoshidaFactorTwoPhaseIntrinsicSixP4Schur
open YoshidaFactorTwoPhaseFullProfile
open YoshidaFactorTwoPhaseLowSchur
open YoshidaFactorTwoPhaseSingularWeightedCauchyStructural

noncomputable section

/-!
# The sharp retained selector target on the `P₀/P₂/P₄` core

The saturated singular Schur split charges `1 / 8192` of the full singular
energy to the low block.  This file records the resulting exact symmetric
quadratic and connects finite selector Gram pivots directly to the production
retained-selector obligation.
-/

/-- The `(0,0)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow00 (a : ℝ) : ℝ :=
  factorTwoStructuralPhaseLow00 a - (1 / 4096 : ℝ) * (2 - a)

/-- The `(0,2)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow02 (a : ℝ) : ℝ :=
  factorTwoStructuralPhaseLow02 a - (1 / 4096 : ℝ) * ((2 - a) / 6)

/-- The `(0,4)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow04 (a : ℝ) : ℝ :=
  factorTwoIntrinsicFourP45Cross04 a - (1 / 4096 : ℝ) * ((2 - a) / 20)

/-- The `(2,2)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow22 (a : ℝ) : ℝ :=
  factorTwoStructuralPhaseLow22 a -
    (1 / 4096 : ℝ) * ((172 - 11 * a) / 150)

/-- The `(2,4)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow24 (a : ℝ) : ℝ :=
  factorTwoIntrinsicFourP45Cross24 a -
    (1 / 4096 : ℝ) * ((15 - 4 * a) / 105)

/-- The `(4,4)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow44 (a : ℝ) : ℝ :=
  factorTwoIntrinsicP4PhaseDiagonal a -
    (1 / 4096 : ℝ) * ((8728 - 269 * a) / 11340)

/-- Exact low budget left by the saturated retained singular Schur split.
The alternating coordinate does not enter because the production low profile
is even and its odd low polynomial is zero. -/
theorem retainedP024SharpLowComplement_eq_symmetricQuadratic
    (c0 c2 c4 a b : ℝ) :
    factorTwoEndpointChannelPhase
          (factorTwoIntrinsicEvenP024Profile c0 c2 c4)
          (0 : ℝ → ℝ) a b -
        (1 / 8192 : ℝ) * factorTwoPhaseSingularWeightedEnergy
          (factorTwoIntrinsicEvenP024Profile c0 c2 c4)
          (0 : ℝ → ℝ) a b =
      symmetricQuadratic
        (retainedP024SharpLow00 a)
        (retainedP024SharpLow02 a)
        (retainedP024SharpLow04 a)
        (retainedP024SharpLow22 a)
        (retainedP024SharpLow24 a)
        (retainedP024SharpLow44 a)
        c0 c2 c4 := by
  have hscale :
      (1 / 8192 : ℝ) * factorTwoPhaseSingularWeightedEnergy
          (factorTwoIntrinsicEvenP024Profile c0 c2 c4)
          (0 : ℝ → ℝ) a b =
        (1 / 4096 : ℝ) * ((1 / 2 : ℝ) *
          factorTwoPhaseSingularWeightedEnergy
            (factorTwoIntrinsicEvenP024Profile c0 c2 c4)
            (0 : ℝ → ℝ) a b) := by
    ring
  rw [factorTwoEndpointChannelPhase_intrinsicEvenP024_eq_quadratic_disk,
    hscale, half_singularWeightedEnergy_intrinsicEvenP024]
  unfold retainedP024SharpLow00 retainedP024SharpLow02
    retainedP024SharpLow04 retainedP024SharpLow22 retainedP024SharpLow24
    retainedP024SharpLow44 symmetricQuadratic
  ring

/-! ## Production selector rows and their finite Gram -/

/-- Retained even production row generated by the shifted Legendre mode `n`
at the sharp pole-removal coefficient. -/
def retainedP024EvenRow (n : ℕ) (a b : ℝ) : ℝ → ℝ :=
  factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
    (1 / 512 : ℝ) (shiftedLegendreReal n) 0 a b

/-- Retained odd production row generated by the shifted Legendre mode `n`
at the sharp pole-removal coefficient. -/
def retainedP024OddRow (n : ℕ) (a b : ℝ) : ℝ → ℝ :=
  factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
    (1 / 512 : ℝ) (shiftedLegendreReal n) 0 a b

/-- One polarized entry of the exact two-channel selector Gram. -/
def retainedP024SelectorGramEntry
    (i j : ℕ) (a b : ℝ)
    (qEi qEj qOi qOj : ℝ[X]) : ℝ :=
  factorTwoIntrinsicElevenRetainedSelectorCrossDual
    (retainedP024EvenRow i a b) (retainedP024EvenRow j a b)
    (retainedP024OddRow i a b) (retainedP024OddRow j a b)
    qEi qEj qOi qOj

/-- Strict pivots of the exact `3 x 3` selector gap produce the two
degree-below-eleven selectors required by the sharp retained Schur handoff.
All analytic integrability obligations and all identifications with the
production `P₀/P₂/P₄` polynomial are discharged here; only the six finite
Gram entries and their three positivity pivots remain as hypotheses. -/
theorem exists_sharpRetunedP024Selector_of_strict_gap_pivots
    (a b : ℝ)
    (qE0 qE2 qE4 qO0 qO2 qO4 : ℝ[X])
    (hqE0 : qE0.natDegree < 11) (hqE2 : qE2.natDegree < 11)
    (hqE4 : qE4.natDegree < 11) (hqO0 : qO0.natDegree < 11)
    (hqO2 : qO2.natDegree < 11) (hqO4 : qO4.natDegree < 11)
    (h00 : 0 < retainedP024SharpLow00 a -
      retainedP024SelectorGramEntry 0 0 a b qE0 qE0 qO0 qO0)
    (hminor : 0 < leadingMinorTwo
      (retainedP024SharpLow00 a -
        retainedP024SelectorGramEntry 0 0 a b qE0 qE0 qO0 qO0)
      (retainedP024SharpLow02 a -
        retainedP024SelectorGramEntry 0 2 a b qE0 qE2 qO0 qO2)
      (retainedP024SharpLow22 a -
        retainedP024SelectorGramEntry 2 2 a b qE2 qE2 qO2 qO2))
    (hdet : 0 < symmetricDeterminant
      (retainedP024SharpLow00 a -
        retainedP024SelectorGramEntry 0 0 a b qE0 qE0 qO0 qO0)
      (retainedP024SharpLow02 a -
        retainedP024SelectorGramEntry 0 2 a b qE0 qE2 qO0 qO2)
      (retainedP024SharpLow04 a -
        retainedP024SelectorGramEntry 0 4 a b qE0 qE4 qO0 qO4)
      (retainedP024SharpLow22 a -
        retainedP024SelectorGramEntry 2 2 a b qE2 qE2 qO2 qO2)
      (retainedP024SharpLow24 a -
        retainedP024SelectorGramEntry 2 4 a b qE2 qE4 qO2 qO4)
      (retainedP024SharpLow44 a -
        retainedP024SelectorGramEntry 4 4 a b qE4 qE4 qO4 qO4))
    (c0 c2 c4 : ℝ) :
    ∃ qE qO : ℝ[X],
      qE.natDegree < 11 ∧ qO.natDegree < 11 ∧
      factorTwoIntrinsicElevenRetainedConstrainedSelectorDual
          (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
          (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
            (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
          qE qO ≤
        factorTwoEndpointChannelPhase
            (centeredPolynomialLift (retainedP024Polynomial c0 c2 c4))
            (centeredPolynomialLift 0) a b -
          (1 / 8192 : ℝ) * factorTwoPhaseSingularWeightedEnergy
            (centeredPolynomialLift (retainedP024Polynomial c0 c2 c4))
            (centeredPolynomialLift 0) a b := by
  have hEven := retainedEvenThreeSelectorGramIntegrable
    (1 / 512 : ℝ)
    (shiftedLegendreReal 0) (shiftedLegendreReal 2) (shiftedLegendreReal 4)
    qE0 qE2 qE4 a b
  have hOdd := retainedOddThreeSelectorGramIntegrable
    (1 / 512 : ℝ)
    (shiftedLegendreReal 0) (shiftedLegendreReal 2) (shiftedLegendreReal 4)
    qO0 qO2 qO4 a b
  obtain ⟨qE, qO, hqE, hqO, hselector⟩ :=
    exists_threeSelector_of_strict_gap_pivots
      (retainedP024EvenRow 0 a b)
      (retainedP024EvenRow 2 a b)
      (retainedP024EvenRow 4 a b)
      (retainedP024OddRow 0 a b)
      (retainedP024OddRow 2 a b)
      (retainedP024OddRow 4 a b)
      qE0 qE2 qE4 qO0 qO2 qO4
      hqE0 hqE2 hqE4 hqO0 hqO2 hqO4
      (by simpa only [retainedP024EvenRow] using hEven)
      (by simpa only [retainedP024OddRow] using hOdd)
      (retainedP024SharpLow00 a)
      (retainedP024SharpLow02 a)
      (retainedP024SharpLow04 a)
      (retainedP024SharpLow22 a)
      (retainedP024SharpLow24 a)
      (retainedP024SharpLow44 a)
      (by simpa only [retainedP024SelectorGramEntry] using h00)
      (by simpa only [retainedP024SelectorGramEntry] using hminor)
      (by simpa only [retainedP024SelectorGramEntry] using hdet)
      c0 c2 c4
  refine ⟨qE, qO, hqE, hqO, ?_⟩
  have hcongr :=
    factorTwoIntrinsicElevenRetainedConstrainedSelectorDual_congr_on_Icc
      (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
        (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
      (threeSelectorRepresenter c0 c2 c4
        (retainedP024EvenRow 0 a b)
        (retainedP024EvenRow 2 a b)
        (retainedP024EvenRow 4 a b))
      (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
        (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
      (threeSelectorRepresenter c0 c2 c4
        (retainedP024OddRow 0 a b)
        (retainedP024OddRow 2 a b)
        (retainedP024OddRow 4 a b))
      qE qO
      (fun x hx ↦ by
        rw [retainedP024Polynomial_eq_threeSelectorPolynomial]
        simpa only [retainedP024EvenRow] using
          retainedEvenMixedRepresenterAt_threeSelectorPolynomial_on_Icc
            (1 / 512 : ℝ) c0 c2 c4 a b
            (shiftedLegendreReal 0) (shiftedLegendreReal 2)
            (shiftedLegendreReal 4) x hx)
      (fun x hx ↦ by
        rw [retainedP024Polynomial_eq_threeSelectorPolynomial]
        simpa only [retainedP024OddRow] using
          retainedOddMixedRepresenterAt_threeSelectorPolynomial_on_Icc
            (1 / 512 : ℝ) c0 c2 c4 a b
            (shiftedLegendreReal 0) (shiftedLegendreReal 2)
            (shiftedLegendreReal 4) x hx)
  have hzero : centeredPolynomialLift (0 : ℝ[X]) = (0 : ℝ → ℝ) := by
    funext x
    unfold centeredPolynomialLift
    simp
  rw [hcongr, centeredPolynomialLift_retainedP024Polynomial,
    hzero,
    retainedP024SharpLowComplement_eq_symmetricQuadratic]
  exact hselector

end

end ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorStructural
