import ArithmeticHodge.Analysis.YoshidaFactorTwoEndpointParityPencil
import ArithmeticHodge.Analysis.YoshidaFourCellEvenCoshMixedStructural

set_option autoImplicit false

open MeasureTheory Real Set

namespace ArithmeticHodge.Analysis.YoshidaFourCellEvenCoshMixedRepresenterStructural

noncomputable section

open CenteredEndpointCorrelation
open YoshidaFactorTwoContinuousLagRepresenterStructural
open YoshidaFactorTwoEndpointBilinear
open YoshidaFactorTwoEndpointParityPencil
open YoshidaFactorTwoIntegrableLagRepresenterStructural
open YoshidaEndpointPotentialBound
open YoshidaFourCellEvenCoshMixedStructural
open YoshidaFourCellParityOperatorStructural
open YoshidaRegularKernelBound

/-!
# The one-variable representer of the even constant row

The exact constant/zero-cosh row has one genuinely nonlocal smooth term.
Fubini turns it into a one-variable representer, while reflection turns the
retained dyadic atom into the positive endpoint-strip mean.  This is the
coordinate form needed for a weighted Riesz estimate; no term is bounded or
scalarized here.
-/

/-- The symmetric regular-kernel row generated by the constant profile. -/
def fourCellEvenConstantRegularRepresenter (x : ℝ) : ℝ :=
  factorTwoContinuousLagK
    (fun t : ℝ ↦
      yoshidaRegularKernel (fourCellOperatorHalfWidth * t))
    (fun _ : ℝ ↦ 1) x

private theorem fourCellRegularLag_abs_le_quarter
    (t : ℝ) (ht : t ∈ Icc (0 : ℝ) 2) :
    |yoshidaRegularKernel (fourCellOperatorHalfWidth * t)| ≤ 1 / 4 := by
  have ha0 : 0 ≤ fourCellOperatorHalfWidth := by
    unfold fourCellOperatorHalfWidth
    positivity
  have harg0 : 0 ≤ fourCellOperatorHalfWidth * t :=
    mul_nonneg ha0 ht.1
  have harg4 : fourCellOperatorHalfWidth * t ≤
      5 * Real.log 2 / 4 := by
    calc
      fourCellOperatorHalfWidth * t ≤ fourCellOperatorHalfWidth * 2 :=
        mul_le_mul_of_nonneg_left ht.2 ha0
      _ = 5 * Real.log 2 / 4 := by
        unfold fourCellOperatorHalfWidth
        ring
  have hk0 := yoshidaRegularKernel_nonneg_fourCellRange harg0 harg4
  rw [abs_of_nonneg hk0]
  exact yoshidaRegularKernel_le_quarter harg0

/-- On an even profile, the constant-profile dyadic polarization is exactly
the positive endpoint-strip mean. -/
theorem factorTwoCenteredCorrelationBilinear_one_even_prime
    (v : ℝ → ℝ) (heven : Function.Even v) :
    factorTwoCenteredCorrelationBilinear
        (fun _ : ℝ ↦ 1) v (8 / 5) =
      ∫ x : ℝ in 3 / 5..1, v x := by
  have hswap := factorTwoCenteredCrossCorrelation_swap_of_reflection_sign
    (fun _ : ℝ ↦ 1) v 1 1 (by intro x; norm_num)
      (by intro x; simpa using heven x) (8 / 5)
  norm_num at hswap
  have hreflect :
      (∫ x : ℝ in -1..-(3 / 5), v x) =
        ∫ x : ℝ in 3 / 5..1, v x := by
    have h := intervalIntegral.integral_comp_neg
      (f := v) (a := (-1 : ℝ)) (b := (-3 / 5 : ℝ))
    rw [show (fun x : ℝ ↦ v (-x)) = v by
      funext x
      exact heven x] at h
    convert h using 1 <;> norm_num
  unfold factorTwoCenteredCorrelationBilinear at ⊢
  rw [hswap]
  unfold factorTwoCenteredCrossCorrelation
  norm_num
  rw [hreflect]

/-- Exact one-variable coordinates of the full constant row.  The endpoint
potential and scalar rows remain untouched, the smooth correlation is its
Fubini representer, and the prime atom is the reflected endpoint-strip row. -/
theorem fourCellEvenZeroCoshConstantRow_eq_representer
    (v : ℝ → ℝ) (hv : Continuous v) (heven : Function.Even v) :
    fourCellEvenZeroCoshConstantRow v =
      (∫ x : ℝ in -1..1, yoshidaEndpointPotential x * v x) -
        (Real.log (2 * fourCellOperatorHalfWidth) +
            Real.eulerMascheroniConstant + Real.log Real.pi) *
          (∫ x : ℝ in -1..1, v x) -
        fourCellOperatorHalfWidth *
          (∫ x : ℝ in -1..1,
            v x * fourCellEvenConstantRegularRepresenter x) -
        Real.sqrt 2 * Real.log 2 *
          (∫ x : ℝ in 3 / 5..1, v x) := by
  let q : ℝ → ℝ := fun t ↦
    yoshidaRegularKernel (fourCellOperatorHalfWidth * t)
  have hq : Measurable q := by
    dsimp only [q]
    exact measurable_yoshidaRegularKernel.comp
      (measurable_const.mul measurable_id)
  have hregular := integral_boundedLag_mul_correlationBilinear_eq_K
    q (fun _ : ℝ ↦ 1) v hq continuous_const hv (1 / 4)
      (by intro t ht; exact fourCellRegularLag_abs_le_quarter t ht)
  have hprime := factorTwoCenteredCorrelationBilinear_one_even_prime
    v heven
  unfold fourCellEvenZeroCoshConstantRow
  change _ - _ - 2 * fourCellOperatorHalfWidth *
      (∫ t : ℝ in 0..2,
        q t * factorTwoCenteredCorrelationBilinear
          (fun _ : ℝ ↦ 1) v t) - _ = _
  rw [hregular, hprime]
  unfold fourCellEvenConstantRegularRepresenter
  dsimp only [q]
  ring

end

end ArithmeticHodge.Analysis.YoshidaFourCellEvenCoshMixedRepresenterStructural
