/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 053; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks052

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row087_001_le :
    evenSparseDominanceBlockContribution (87 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (87 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row087_002_le :
    evenSparseDominanceBlockContribution (87 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (87 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row088_000_le :
    evenSparseDominanceBlockContribution (88 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (88 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row088_001_le :
    evenSparseDominanceBlockContribution (88 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (88 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row088_002_le :
    evenSparseDominanceBlockContribution (88 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (88 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row089_000_le :
    evenSparseDominanceBlockContribution (89 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (89 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row089_001_le :
    evenSparseDominanceBlockContribution (89 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (89 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row089_002_le :
    evenSparseDominanceBlockContribution (89 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (89 : YoshidaEvenIndex) 2 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
