/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 031; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks030

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row043_000_le :
    evenSparseDominanceBlockContribution (43 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (43 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row043_001_le :
    evenSparseDominanceBlockContribution (43 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (43 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row043_002_le :
    evenSparseDominanceBlockContribution (43 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (43 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row043_003_le :
    evenSparseDominanceBlockContribution (43 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (43 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row044_000_le :
    evenSparseDominanceBlockContribution (44 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (44 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row044_001_le :
    evenSparseDominanceBlockContribution (44 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (44 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row044_002_le :
    evenSparseDominanceBlockContribution (44 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (44 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row044_003_le :
    evenSparseDominanceBlockContribution (44 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (44 : YoshidaEvenIndex) 3 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
