/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 061; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks060

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row108_002_le :
    evenSparseDominanceBlockContribution (108 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (108 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row109_000_le :
    evenSparseDominanceBlockContribution (109 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (109 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row109_001_le :
    evenSparseDominanceBlockContribution (109 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (109 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row109_002_le :
    evenSparseDominanceBlockContribution (109 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (109 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row110_000_le :
    evenSparseDominanceBlockContribution (110 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (110 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row110_001_le :
    evenSparseDominanceBlockContribution (110 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (110 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row110_002_le :
    evenSparseDominanceBlockContribution (110 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (110 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row111_000_le :
    evenSparseDominanceBlockContribution (111 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (111 : YoshidaEvenIndex) 0 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
