/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 005; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks004

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row008_004_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row008_005_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 5 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 5 := by
  decide +kernel

theorem evenSparseDominanceBlock_row008_006_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 6 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 6 := by
  decide +kernel

theorem evenSparseDominanceBlock_row008_007_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 7 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 7 := by
  decide +kernel

theorem evenSparseDominanceBlock_row008_008_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 8 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 8 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_000_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_001_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_002_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 2 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
