import ArithmeticHodge.Analysis.FiniteWeightedSelectorProjection
import ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorRemainderGramStructural

set_option autoImplicit false

open Matrix MeasureTheory Polynomial Real Set

namespace ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorOddProjectionStructural

open FiniteWeightedSelectorProjection
open ShiftedLegendreLogEnergyOrthogonalProjection
open ShiftedLegendreOrthogonality
open YoshidaFactorTwoPhaseIntrinsicElevenConstrainedWeightedDualStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedConstrainedWeightedDualStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedSelectorHomogeneityStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedSingularSchurStructural
open YoshidaFactorTwoPhaseIntrinsicElevenSelectorGramStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorQuotientStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorRemainderGramStructural

noncomputable section

/-!
# Inverse-free odd projection for the retained P024 selector

The favorable alternating shifted-remainder Gram is bounded below by
subtracting an arbitrary exact finite combination of centered shifted-Legendre
modes.  The coefficient matrix remains a parameter so a later rational choice
can be optimized without changing the sound analytic argument.
-/

/-- Weighted comparison row associated with a centered shifted-Legendre mode. -/
def retainedP024OddProjectionWeightedRow
    {κ : Type*} (ν : κ → ℕ) (k : κ) (x : ℝ) : ℝ :=
  factorTwoIntrinsicElevenRetainedOddWeight x *
    centeredPolynomialLift (shiftedLegendreReal (ν k)) x

/-- Cross pairings from the three alternating shifted remainders to the
chosen weighted modes. -/
def retainedP024OddProjectionCrossGram
    {κ : Type*} [Fintype κ] (ν : κ → ℕ) : Matrix (Fin 3) κ ℝ :=
  finiteWeightedCrossGram
    factorTwoIntrinsicElevenRetainedOddWeight
    retainedP024SelectorAlternatingShiftedRemainder
    (retainedP024OddProjectionWeightedRow ν)

/-- Retained-weight Gram of the chosen comparison modes. -/
def retainedP024OddProjectionModeGram
    {κ : Type*} [Fintype κ] (ν : κ → ℕ) : Matrix κ κ ℝ :=
  finiteWeightedGram
    factorTwoIntrinsicElevenRetainedOddWeight
    (retainedP024OddProjectionWeightedRow ν)

/-- Full Gram joining the three favorable remainders to the chosen comparison
modes. -/
def retainedP024OddProjectionCombinedGram
    {κ : Type*} [Fintype κ] (ν : κ → ℕ) :
    Matrix (Fin 3 ⊕ κ) (Fin 3 ⊕ κ) ℝ :=
  finiteWeightedGram
    factorTwoIntrinsicElevenRetainedOddWeight
    (Sum.elim retainedP024SelectorAlternatingShiftedRemainder
      (retainedP024OddProjectionWeightedRow ν))

theorem retainedP024OddProjectionCombinedGram_eq_fromBlocks
    {κ : Type*} [Fintype κ] (ν : κ → ℕ) :
    retainedP024OddProjectionCombinedGram ν =
      Matrix.fromBlocks
        retainedP024SelectorAlternatingShiftedRemainderGram
        (retainedP024OddProjectionCrossGram ν)
        (retainedP024OddProjectionCrossGram ν)ᴴ
        (retainedP024OddProjectionModeGram ν) := by
  change finiteWeightedGram
      factorTwoIntrinsicElevenRetainedOddWeight
      (Sum.elim retainedP024SelectorAlternatingShiftedRemainder
        (retainedP024OddProjectionWeightedRow ν)) =
    Matrix.fromBlocks
      (finiteWeightedGram factorTwoIntrinsicElevenRetainedOddWeight
        retainedP024SelectorAlternatingShiftedRemainder)
      (finiteWeightedCrossGram factorTwoIntrinsicElevenRetainedOddWeight
        retainedP024SelectorAlternatingShiftedRemainder
        (retainedP024OddProjectionWeightedRow ν))
      (finiteWeightedCrossGram factorTwoIntrinsicElevenRetainedOddWeight
        retainedP024SelectorAlternatingShiftedRemainder
        (retainedP024OddProjectionWeightedRow ν))ᴴ
      (finiteWeightedGram factorTwoIntrinsicElevenRetainedOddWeight
        (retainedP024OddProjectionWeightedRow ν))
  exact finiteWeightedGram_sum_eq_fromBlocks
    factorTwoIntrinsicElevenRetainedOddWeight
    retainedP024SelectorAlternatingShiftedRemainder
    (retainedP024OddProjectionWeightedRow ν)

/-- The inverse-free lower Gram generated by an exact coefficient matrix. -/
def retainedP024OddProjectionLowerGram
    {κ : Type*} [Fintype κ]
    (ν : κ → ℕ) (C : Matrix (Fin 3) κ ℝ) : Matrix (Fin 3) (Fin 3) ℝ :=
  retainedP024OddProjectionCrossGram ν * Cᴴ +
    C * (retainedP024OddProjectionCrossGram ν)ᴴ -
    C * retainedP024OddProjectionModeGram ν * Cᴴ

theorem retainedP024OddProjectionWeightedRow_div_sqrt_memLp_two
    {κ : Type*} (ν : κ → ℕ) (k : κ) :
    MemLp (fun x ↦
      retainedP024OddProjectionWeightedRow ν k x /
        Real.sqrt (factorTwoIntrinsicElevenRetainedOddWeight x)) 2
      (volume.restrict (Ioc (-1 : ℝ) 1)) := by
  let φ : ℝ → ℝ :=
    centeredPolynomialLift (shiftedLegendreReal (ν k))
  have hφ : Continuous φ := by
    exact continuous_centeredPolynomialLift _
  have hbase := sqrt_retainedOddWeight_mul_memLp_two φ hφ
  apply (memLp_congr_ae (μ := volume.restrict (Ioc (-1 : ℝ) 1)) ?_).mpr
    hbase
  filter_upwards [ae_restrict_mem measurableSet_Ioc] with x hx
  have hW := factorTwoIntrinsicElevenRetainedOddWeight_pos_on_Icc
    ⟨hx.1.le, hx.2⟩
  have hsqrt : 0 < Real.sqrt
      (factorTwoIntrinsicElevenRetainedOddWeight x) := Real.sqrt_pos.2 hW
  change factorTwoIntrinsicElevenRetainedOddWeight x * φ x /
      Real.sqrt (factorTwoIntrinsicElevenRetainedOddWeight x) =
    Real.sqrt (factorTwoIntrinsicElevenRetainedOddWeight x) * φ x
  field_simp [ne_of_gt hsqrt]
  rw [Real.sq_sqrt hW.le]
  ring

theorem retainedP024OddProjectionCombinedGram_posSemidef
    {κ : Type*} [Fintype κ] (ν : κ → ℕ) :
    (retainedP024OddProjectionCombinedGram ν).PosSemidef := by
  unfold retainedP024OddProjectionCombinedGram
  apply finiteWeightedGram_posSemidef_of_memLp
    factorTwoIntrinsicElevenRetainedOddWeight
    (Sum.elim retainedP024SelectorAlternatingShiftedRemainder
      (retainedP024OddProjectionWeightedRow ν))
    (fun x hx ↦ factorTwoIntrinsicElevenRetainedOddWeight_pos_on_Icc hx)
  intro i
  rcases i with i | k
  · exact retainedP024SelectorAlternatingShiftedRemainder_div_sqrt_memLp_two i
  · exact retainedP024OddProjectionWeightedRow_div_sqrt_memLp_two ν k

theorem retainedP024OddProjectionBlockGram_posSemidef
    {κ : Type*} [Fintype κ] (ν : κ → ℕ) :
    (Matrix.fromBlocks
      retainedP024SelectorAlternatingShiftedRemainderGram
      (retainedP024OddProjectionCrossGram ν)
      (retainedP024OddProjectionCrossGram ν)ᴴ
      (retainedP024OddProjectionModeGram ν)).PosSemidef := by
  rw [← retainedP024OddProjectionCombinedGram_eq_fromBlocks]
  exact retainedP024OddProjectionCombinedGram_posSemidef ν

/-- The rectangular projection matrix is the unweighted pairing against the
centered comparison mode. -/
theorem retainedP024OddProjectionCrossGram_apply
    {κ : Type*} [Fintype κ] (ν : κ → ℕ) (i : Fin 3) (k : κ) :
    retainedP024OddProjectionCrossGram ν i k =
      ∫ x : ℝ in -1..1,
        retainedP024SelectorAlternatingShiftedRemainder i x *
          centeredPolynomialLift (shiftedLegendreReal (ν k)) x := by
  unfold retainedP024OddProjectionCrossGram finiteWeightedCrossGram
    retainedP024OddProjectionWeightedRow
    factorTwoIntrinsicElevenSelectorCrossDual
  apply intervalIntegral.integral_congr
  intro x hx
  rw [uIcc_of_le (by norm_num : (-1 : ℝ) ≤ 1)] at hx
  have hW := factorTwoIntrinsicElevenRetainedOddWeight_pos_on_Icc hx
  simp only [factorTwoIntrinsicElevenSelectorResidual,
    centeredPolynomialLift, Polynomial.eval_zero, sub_zero]
  field_simp [hW.ne']

/-- The comparison-mode Gram is the retained-weighted polynomial Gram. -/
theorem retainedP024OddProjectionModeGram_apply
    {κ : Type*} [Fintype κ] (ν : κ → ℕ) (k l : κ) :
    retainedP024OddProjectionModeGram ν k l =
      ∫ x : ℝ in -1..1,
        factorTwoIntrinsicElevenRetainedOddWeight x *
          centeredPolynomialLift (shiftedLegendreReal (ν k)) x *
          centeredPolynomialLift (shiftedLegendreReal (ν l)) x := by
  unfold retainedP024OddProjectionModeGram finiteWeightedGram
    factorTwoIntrinsicElevenSelectorGram
    retainedP024OddProjectionWeightedRow
    factorTwoIntrinsicElevenSelectorCrossDual
  apply intervalIntegral.integral_congr
  intro x hx
  rw [uIcc_of_le (by norm_num : (-1 : ℝ) ≤ 1)] at hx
  have hW := factorTwoIntrinsicElevenRetainedOddWeight_pos_on_Icc hx
  simp only [factorTwoIntrinsicElevenSelectorResidual,
    centeredPolynomialLift, Polynomial.eval_zero, sub_zero]
  field_simp [hW.ne']

/-- Any exact finite projection supplies a sound Loewner lower bound for the
favorable alternating shifted-remainder Gram. -/
theorem retainedP024OddProjectionLowerGram_le
    {κ : Type*} [Fintype κ]
    (ν : κ → ℕ) (C : Matrix (Fin 3) κ ℝ) :
    (retainedP024SelectorAlternatingShiftedRemainderGram -
      retainedP024OddProjectionLowerGram ν C).PosSemidef := by
  simpa [retainedP024SelectorAlternatingShiftedRemainderGram,
    retainedP024OddProjectionLowerGram,
    retainedP024OddProjectionCrossGram,
    retainedP024OddProjectionModeGram,
    finiteWeightedGram] using
    finiteWeightedProjectionResidual_posSemidef
      factorTwoIntrinsicElevenRetainedOddWeight
      retainedP024SelectorAlternatingShiftedRemainder
      (retainedP024OddProjectionWeightedRow ν)
      (fun x hx ↦ factorTwoIntrinsicElevenRetainedOddWeight_pos_on_Icc hx)
      retainedP024SelectorAlternatingShiftedRemainder_div_sqrt_memLp_two
      (retainedP024OddProjectionWeightedRow_div_sqrt_memLp_two ν) C

end

end ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorOddProjectionStructural
