/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 054; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks053

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row090_000_le :
    evenSparseDominanceBlockContribution (90 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (90 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row090_001_le :
    evenSparseDominanceBlockContribution (90 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (90 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row090_002_le :
    evenSparseDominanceBlockContribution (90 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (90 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row091_000_le :
    evenSparseDominanceBlockContribution (91 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (91 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row091_001_le :
    evenSparseDominanceBlockContribution (91 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (91 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row091_002_le :
    evenSparseDominanceBlockContribution (91 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (91 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row092_000_le :
    evenSparseDominanceBlockContribution (92 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (92 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row092_001_le :
    evenSparseDominanceBlockContribution (92 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (92 : YoshidaEvenIndex) 1 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
