/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 039; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks038

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row059_000_le :
    evenSparseDominanceBlockContribution (59 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (59 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row059_001_le :
    evenSparseDominanceBlockContribution (59 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (59 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row059_002_le :
    evenSparseDominanceBlockContribution (59 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (59 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row059_003_le :
    evenSparseDominanceBlockContribution (59 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (59 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row060_000_le :
    evenSparseDominanceBlockContribution (60 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (60 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row060_001_le :
    evenSparseDominanceBlockContribution (60 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (60 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row060_002_le :
    evenSparseDominanceBlockContribution (60 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (60 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row060_003_le :
    evenSparseDominanceBlockContribution (60 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (60 : YoshidaEvenIndex) 3 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
