/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 060; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks059

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row106_000_le :
    evenSparseDominanceBlockContribution (106 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (106 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row106_001_le :
    evenSparseDominanceBlockContribution (106 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (106 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row106_002_le :
    evenSparseDominanceBlockContribution (106 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (106 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row107_000_le :
    evenSparseDominanceBlockContribution (107 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (107 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row107_001_le :
    evenSparseDominanceBlockContribution (107 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (107 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row107_002_le :
    evenSparseDominanceBlockContribution (107 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (107 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row108_000_le :
    evenSparseDominanceBlockContribution (108 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (108 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row108_001_le :
    evenSparseDominanceBlockContribution (108 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (108 : YoshidaEvenIndex) 1 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
