/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 058; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks057

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row100_002_le :
    evenSparseDominanceBlockContribution (100 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (100 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row101_000_le :
    evenSparseDominanceBlockContribution (101 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (101 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row101_001_le :
    evenSparseDominanceBlockContribution (101 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (101 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row101_002_le :
    evenSparseDominanceBlockContribution (101 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (101 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row102_000_le :
    evenSparseDominanceBlockContribution (102 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (102 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row102_001_le :
    evenSparseDominanceBlockContribution (102 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (102 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row102_002_le :
    evenSparseDominanceBlockContribution (102 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (102 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row103_000_le :
    evenSparseDominanceBlockContribution (103 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (103 : YoshidaEvenIndex) 0 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
