/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 017; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks016

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row021_001_le :
    evenSparseDominanceBlockContribution (21 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (21 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row021_002_le :
    evenSparseDominanceBlockContribution (21 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (21 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row021_003_le :
    evenSparseDominanceBlockContribution (21 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (21 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row021_004_le :
    evenSparseDominanceBlockContribution (21 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (21 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row021_005_le :
    evenSparseDominanceBlockContribution (21 : YoshidaEvenIndex) 5 ≤
      evenSparseDominanceBlockBudget (21 : YoshidaEvenIndex) 5 := by
  decide +kernel

theorem evenSparseDominanceBlock_row022_000_le :
    evenSparseDominanceBlockContribution (22 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (22 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row022_001_le :
    evenSparseDominanceBlockContribution (22 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (22 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row022_002_le :
    evenSparseDominanceBlockContribution (22 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (22 : YoshidaEvenIndex) 2 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
