import ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedCutoffEightBridgeStructural
import ArithmeticHodge.Analysis.YoshidaFourCellOddStripCapacityClosureStructural

set_option autoImplicit false

open MeasureTheory Polynomial Real Set
open scoped Interval

namespace ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedRegularRemainderStructural

noncomputable section

open YoshidaConstantBounds
open YoshidaEndpointEvenProjectedRemainderEnvelopeKernel
open YoshidaFactorTwoContinuousLagRepresenterStructural
open YoshidaFactorTwoIntegrableLagRepresenterStructural
open YoshidaFourCellEvenPolarSchurStructural
open YoshidaFourCellEvenEndpointCoshSchurStructural
open YoshidaFourCellEvenEndpointSeedCutoffEightBridgeStructural
open YoshidaFourCellOddStripCapacityClosureStructural
open YoshidaFourCellParityOperatorStructural
open YoshidaRegularKernelBound

/-!
# The analytic remainder in the endpoint-seed regular row

The degree-four regular-kernel model has already been removed exactly from
every genuine `P8+` tail.  This file bounds the remaining analytic kernel
uniformly, using the proved sixth-order envelope on the whole four-cell
range.  The result is a small genuine operator remainder, not a retained
finite-mode computation.
-/

/-- On the endpoint-seed lag range, replacing the regular kernel by its
degree-four model costs less than `1/1400` pointwise. -/
theorem abs_yoshidaRegularKernel_sub_fourCellRegularKernelPolynomial4_lt
    {t : ℝ} (ht0 : 0 ≤ t) (ht : t ≤ 5 * Real.log 2 / 4) :
    |yoshidaRegularKernel t - fourCellRegularKernelPolynomial4 t| <
      (1 / 1400 : ℝ) := by
  have htlog : t ≤ 2 * Real.log 2 := by
    have hlog0 : 0 ≤ Real.log 2 := (Real.log_pos (by norm_num)).le
    nlinarith
  have henv := fourCell_yoshidaRegularKernelPolynomial6_wide_envelope
    ht0 htlog
  have htNine : t ≤ (9 / 10 : ℝ) := by
    have hlog := strict_log_two_bounds.2
    nlinarith
  have ht5 : t ^ 5 ≤ (9 / 10 : ℝ) ^ 5 :=
    pow_le_pow_left₀ ht0 htNine 5
  have ht6 : t ^ 6 ≤ (9 / 10 : ℝ) ^ 6 :=
    pow_le_pow_left₀ ht0 htNine 6
  have ht5nonneg : 0 ≤ t ^ 5 := pow_nonneg ht0 5
  have ht6nonneg : 0 ≤ t ^ 6 := pow_nonneg ht0 6
  have htail :
      31 * t ^ 5 / 1935360 + 61 * t ^ 6 / 184320 <
        (1 / 1400 : ℝ) := by
    norm_num at ht5 ht6 ⊢
    nlinarith
  rw [abs_lt]
  constructor
  · unfold yoshidaRegularKernelPolynomial6 at henv
    unfold fourCellRegularKernelPolynomial4
    nlinarith
  · unfold yoshidaRegularKernelPolynomial6 at henv
    unfold fourCellRegularKernelPolynomial4
    nlinarith

/-- The normalized lag kernel left after the exact polynomial selector is
removed. -/
def fourCellEndpointSeedRegularKernelRemainder (t : ℝ) : ℝ :=
  yoshidaRegularKernel (fourCellOperatorHalfWidth * t) -
    fourCellRegularKernelPolynomial4 (fourCellOperatorHalfWidth * t)

theorem measurable_fourCellEndpointSeedRegularKernelRemainder :
    Measurable fourCellEndpointSeedRegularKernelRemainder := by
  unfold fourCellEndpointSeedRegularKernelRemainder
  have hp : Continuous (fun t : ℝ ↦
      fourCellRegularKernelPolynomial4 (fourCellOperatorHalfWidth * t)) := by
    unfold fourCellRegularKernelPolynomial4
    fun_prop
  exact
    (measurable_yoshidaRegularKernel.comp
      (measurable_const.mul measurable_id)).sub
        hp.measurable

theorem abs_fourCellEndpointSeedRegularKernelRemainder_le
    {t : ℝ} (ht : t ∈ Icc (0 : ℝ) 2) :
    |fourCellEndpointSeedRegularKernelRemainder t| ≤ (1 / 1400 : ℝ) := by
  apply le_of_lt
  unfold fourCellEndpointSeedRegularKernelRemainder
  apply abs_yoshidaRegularKernel_sub_fourCellRegularKernelPolynomial4_lt
  · exact mul_nonneg
      (by unfold fourCellOperatorHalfWidth; positivity) ht.1
  · have hw : 0 ≤ fourCellOperatorHalfWidth := by
      unfold fourCellOperatorHalfWidth
      positivity
    calc
      fourCellOperatorHalfWidth * t ≤
          fourCellOperatorHalfWidth * 2 :=
        mul_le_mul_of_nonneg_left ht.2 hw
      _ = 5 * Real.log 2 / 4 := by
        unfold fourCellOperatorHalfWidth
        ring

/-- The genuine one-variable remainder representer generated by the
endpoint-zero seed. -/
def fourCellEndpointSeedRegularRemainderRepresenter (x : ℝ) : ℝ :=
  factorTwoContinuousLagK fourCellEndpointSeedRegularKernelRemainder
    fourCellEvenEndpointCoshSeed x

private theorem abs_fourCellEvenEndpointCoshSeed_le_one
    {x : ℝ} (hx : x ∈ Icc (-1 : ℝ) 1) :
    |fourCellEvenEndpointCoshSeed x| ≤ 1 := by
  have hprod : 0 ≤ (x + 1) * (1 - x) :=
    mul_nonneg (by linarith [hx.1]) (by linarith [hx.2])
  have hnonneg : 0 ≤ 1 - x ^ 2 := by
    nlinarith only [hprod]
  unfold fourCellEvenEndpointCoshSeed
  rw [abs_of_nonneg hnonneg]
  nlinarith only [sq_nonneg x]

/-- The two triangular pieces have total length exactly two, so the
`1/1400` kernel error becomes a `1/700` pointwise representer error. -/
theorem norm_fourCellEndpointSeedRegularRemainderRepresenter_le
    {x : ℝ} (hx : x ∈ Icc (-1 : ℝ) 1) :
    ‖fourCellEndpointSeedRegularRemainderRepresenter x‖ ≤
      (1 / 700 : ℝ) := by
  let E := fourCellEndpointSeedRegularKernelRemainder
  have hrightPoint : ∀ y ∈ Ι x 1,
      ‖E (y - x) * fourCellEvenEndpointCoshSeed y‖ ≤
        (1 / 1400 : ℝ) := by
    intro y hy
    rw [uIoc_of_le hx.2] at hy
    have hyIcc : y ∈ Icc (-1 : ℝ) 1 :=
      ⟨by linarith [hx.1, hy.1], hy.2⟩
    have hlag : y - x ∈ Icc (0 : ℝ) 2 :=
      ⟨by linarith [hy.1], by linarith [hx.1, hy.2]⟩
    have hE := abs_fourCellEndpointSeedRegularKernelRemainder_le hlag
    have hs := abs_fourCellEvenEndpointCoshSeed_le_one hyIcc
    rw [Real.norm_eq_abs, abs_mul]
    exact (mul_le_mul hE hs (abs_nonneg _) (by norm_num)).trans_eq (by norm_num)
  have hleftPoint : ∀ y ∈ Ι (-1) x,
      ‖E (x - y) * fourCellEvenEndpointCoshSeed y‖ ≤
        (1 / 1400 : ℝ) := by
    intro y hy
    rw [uIoc_of_le hx.1] at hy
    have hyIcc : y ∈ Icc (-1 : ℝ) 1 :=
      ⟨hy.1.le, by linarith [hy.2, hx.2]⟩
    have hlag : x - y ∈ Icc (0 : ℝ) 2 :=
      ⟨by linarith [hy.2], by linarith [hy.1, hx.2]⟩
    have hE := abs_fourCellEndpointSeedRegularKernelRemainder_le hlag
    have hs := abs_fourCellEvenEndpointCoshSeed_le_one hyIcc
    rw [Real.norm_eq_abs, abs_mul]
    exact (mul_le_mul hE hs (abs_nonneg _) (by norm_num)).trans_eq (by norm_num)
  have hright := intervalIntegral.norm_integral_le_of_norm_le_const hrightPoint
  have hleft := intervalIntegral.norm_integral_le_of_norm_le_const hleftPoint
  have hright' :
      ‖factorTwoContinuousLagRightRepresenter E
          fourCellEvenEndpointCoshSeed x‖ ≤
        (1 / 1400 : ℝ) * (1 - x) := by
    change ‖∫ y : ℝ in x..1,
      E (y - x) * fourCellEvenEndpointCoshSeed y‖ ≤ _
    simpa only [abs_of_nonneg (sub_nonneg.mpr hx.2)] using hright
  have hleft' :
      ‖factorTwoContinuousLagLeftRepresenter E
          fourCellEvenEndpointCoshSeed x‖ ≤
        (1 / 1400 : ℝ) * (x + 1) := by
    change ‖∫ y : ℝ in -1..x,
      E (x - y) * fourCellEvenEndpointCoshSeed y‖ ≤ _
    rw [abs_of_nonneg (by linarith [hx.1])] at hleft
    simpa only [sub_neg_eq_add] using hleft
  unfold fourCellEndpointSeedRegularRemainderRepresenter
    factorTwoContinuousLagK
  dsimp only [E] at hright' hleft' ⊢
  exact (norm_add_le _ _).trans (by linarith)

/-- The analytic regular-row remainder is square-integrable with its sharp
uniform pointwise reserve. -/
theorem memLp_fourCellEndpointSeedRegularRemainderRepresenter :
    MemLp fourCellEndpointSeedRegularRemainderRepresenter 2
      (volume.restrict (Ioc (-1 : ℝ) 1)) := by
  let E := fourCellEndpointSeedRegularKernelRemainder
  have hright :=
    intervalIntegrable_mul_factorTwoContinuousLagRightRepresenter_of_bounded
      E fourCellEvenEndpointCoshSeed (fun _ : ℝ ↦ 1)
        measurable_fourCellEndpointSeedRegularKernelRemainder
        fourCellEvenEndpointCoshSeed_continuous continuous_const
        (1 / 1400) (fun t ht ↦
          abs_fourCellEndpointSeedRegularKernelRemainder_le ht)
  have hleft :=
    intervalIntegrable_mul_factorTwoContinuousLagLeftRepresenter_of_bounded
      E (fun _ : ℝ ↦ 1) fourCellEvenEndpointCoshSeed
        measurable_fourCellEndpointSeedRegularKernelRemainder
        continuous_const fourCellEvenEndpointCoshSeed_continuous
        (1 / 1400) (fun t ht ↦
          abs_fourCellEndpointSeedRegularKernelRemainder_le ht)
  have hK : IntervalIntegrable
      fourCellEndpointSeedRegularRemainderRepresenter volume (-1) 1 := by
    apply (hright.add hleft).congr
    intro x _hx
    unfold fourCellEndpointSeedRegularRemainderRepresenter
      factorTwoContinuousLagK
    dsimp only [E]
    ring
  have hmeas : AEStronglyMeasurable
      fourCellEndpointSeedRegularRemainderRepresenter
      (volume.restrict (Ioc (-1 : ℝ) 1)) :=
    hK.1.aestronglyMeasurable
  apply MemLp.of_bound hmeas (1 / 700)
  filter_upwards [ae_restrict_mem measurableSet_Ioc] with x hx
  exact norm_fourCellEndpointSeedRegularRemainderRepresenter_le
    ⟨hx.1.le, hx.2⟩

private theorem intervalIntegrable_sq_of_memLp_two_restrict
    (f : ℝ → ℝ)
    (hf : MemLp f 2 (volume.restrict (Ioc (-1 : ℝ) 1))) :
    IntervalIntegrable (fun x : ℝ ↦ f x ^ 2) volume (-1) 1 := by
  rw [intervalIntegrable_iff_integrableOn_Ioc_of_le (by norm_num)]
  apply (hf.integrable_norm_pow (by norm_num)).congr
  filter_upwards with x
  rw [Real.norm_eq_abs, sq_abs]

/-- The squared analytic remainder consumes at most `1/245000` of the
endpoint-row determinant budget. -/
theorem integral_fourCellEndpointSeedRegularRemainderRepresenter_sq_le :
    (∫ x : ℝ in -1..1,
      fourCellEndpointSeedRegularRemainderRepresenter x ^ 2) ≤
        (1 / 245000 : ℝ) := by
  have hleft : IntervalIntegrable
      (fun x : ℝ ↦ fourCellEndpointSeedRegularRemainderRepresenter x ^ 2)
      volume (-1) 1 :=
    intervalIntegrable_sq_of_memLp_two_restrict _
      memLp_fourCellEndpointSeedRegularRemainderRepresenter
  have hright : IntervalIntegrable (fun _x : ℝ ↦ (1 / 700 : ℝ) ^ 2)
      volume (-1) 1 := continuous_const.intervalIntegrable _ _
  calc
    (∫ x : ℝ in -1..1,
        fourCellEndpointSeedRegularRemainderRepresenter x ^ 2) ≤
        ∫ _x : ℝ in -1..1, (1 / 700 : ℝ) ^ 2 := by
      apply intervalIntegral.integral_mono_on (by norm_num) hleft hright
      intro x hx
      have hn :=
        norm_fourCellEndpointSeedRegularRemainderRepresenter_le hx
      rw [Real.norm_eq_abs] at hn
      have hs := (sq_le_sq₀ (abs_nonneg _) (by norm_num)).2 hn
      simpa only [sq_abs] using hs
    _ = (1 / 245000 : ℝ) := by
      simp only [intervalIntegral.integral_const, sub_neg_eq_add,
        smul_eq_mul]
      norm_num

end

end ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedRegularRemainderStructural
