/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 055; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks054

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row092_002_le :
    evenSparseDominanceBlockContribution (92 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (92 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row093_000_le :
    evenSparseDominanceBlockContribution (93 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (93 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row093_001_le :
    evenSparseDominanceBlockContribution (93 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (93 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row093_002_le :
    evenSparseDominanceBlockContribution (93 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (93 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row094_000_le :
    evenSparseDominanceBlockContribution (94 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (94 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row094_001_le :
    evenSparseDominanceBlockContribution (94 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (94 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row094_002_le :
    evenSparseDominanceBlockContribution (94 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (94 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row095_000_le :
    evenSparseDominanceBlockContribution (95 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (95 : YoshidaEvenIndex) 0 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
