/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 004; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks003

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row007_004_le :
    evenSparseDominanceBlockContribution (7 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (7 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row007_005_le :
    evenSparseDominanceBlockContribution (7 : YoshidaEvenIndex) 5 ≤
      evenSparseDominanceBlockBudget (7 : YoshidaEvenIndex) 5 := by
  decide +kernel

theorem evenSparseDominanceBlock_row007_006_le :
    evenSparseDominanceBlockContribution (7 : YoshidaEvenIndex) 6 ≤
      evenSparseDominanceBlockBudget (7 : YoshidaEvenIndex) 6 := by
  decide +kernel

theorem evenSparseDominanceBlock_row007_007_le :
    evenSparseDominanceBlockContribution (7 : YoshidaEvenIndex) 7 ≤
      evenSparseDominanceBlockBudget (7 : YoshidaEvenIndex) 7 := by
  decide +kernel

theorem evenSparseDominanceBlock_row008_000_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row008_001_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row008_002_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row008_003_le :
    evenSparseDominanceBlockContribution (8 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (8 : YoshidaEvenIndex) 3 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
