/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 016; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks015

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row019_005_le :
    evenSparseDominanceBlockContribution (19 : YoshidaEvenIndex) 5 ≤
      evenSparseDominanceBlockBudget (19 : YoshidaEvenIndex) 5 := by
  decide +kernel

theorem evenSparseDominanceBlock_row020_000_le :
    evenSparseDominanceBlockContribution (20 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (20 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row020_001_le :
    evenSparseDominanceBlockContribution (20 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (20 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row020_002_le :
    evenSparseDominanceBlockContribution (20 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (20 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row020_003_le :
    evenSparseDominanceBlockContribution (20 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (20 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row020_004_le :
    evenSparseDominanceBlockContribution (20 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (20 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row020_005_le :
    evenSparseDominanceBlockContribution (20 : YoshidaEvenIndex) 5 ≤
      evenSparseDominanceBlockBudget (20 : YoshidaEvenIndex) 5 := by
  decide +kernel

theorem evenSparseDominanceBlock_row021_000_le :
    evenSparseDominanceBlockContribution (21 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (21 : YoshidaEvenIndex) 0 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
