/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 046; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks045

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row073_000_le :
    evenSparseDominanceBlockContribution (73 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (73 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row073_001_le :
    evenSparseDominanceBlockContribution (73 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (73 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row073_002_le :
    evenSparseDominanceBlockContribution (73 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (73 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row073_003_le :
    evenSparseDominanceBlockContribution (73 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (73 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row074_000_le :
    evenSparseDominanceBlockContribution (74 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (74 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row074_001_le :
    evenSparseDominanceBlockContribution (74 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (74 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row074_002_le :
    evenSparseDominanceBlockContribution (74 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (74 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row074_003_le :
    evenSparseDominanceBlockContribution (74 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (74 : YoshidaEvenIndex) 3 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
