import ArithmeticHodge.Analysis.YoshidaFourCellOddP11SchurResidualProfilesStructural
import ArithmeticHodge.Analysis.YoshidaFourCellOddP11FormDualProbeStructural

set_option autoImplicit false

open MeasureTheory Real Set

namespace ArithmeticHodge.Analysis.YoshidaFourCellOddP11UniversalCoreCauchyStructural

noncomputable section

open CenteredOddOneThreeEnergy
open YoshidaEndpointOcticPotential
open YoshidaEndpointOcticTwoModeSchurData
open YoshidaEndpointOddResidualRegularity
open YoshidaFactorTwoEndpointBilinear
open YoshidaFactorTwoPhaseCenteredP9Structural
open YoshidaFactorTwoPhaseLegendreFourFiveStructural
open YoshidaFactorTwoPhaseLegendreSixSevenStructuralPositive
open YoshidaFourCellOddFiveModeCoreExpressionBridgeStructural
open YoshidaFourCellOddFiveModeStrictCoercivityStructural
open YoshidaFourCellOddP11ConcreteWeightedDualClosureStructural
open YoshidaFourCellOddP11CoupledRieszDefectClosureStructural
open YoshidaFourCellOddP11DirectCorrectedCauchyStructural
open YoshidaFourCellOddP11FormDualProbeStructural
open YoshidaFourCellOddP11SchurResidualProfilesStructural
open YoshidaFourCellOddP11SelectorConstructionStructural
open YoshidaFourCellOddStripCapacityClosureStructural

/-!
# The universal core pencil at the odd `P₁₁+` frontier

The existing coercivity theorem is positive on the *Legendre* `P₁`-zero
subspace.  The two inverse-free Schur residuals instead lie in the
*core-form* orthogonal complement of `P₁`.  This file keeps that distinction
explicit.

The full mixed problem is exactly nonnegativity of the two-parameter core
pencil generated by the finite and tail Schur residuals.  Every direction of
that pencil is core-orthogonal to `P₁`, but its Legendre `P₁` coefficient
is generally nonzero.  In particular, the finite `P₃` Schur residual is a
formal counterexample to applying the existing `P₁`-zero coercivity theorem
to the whole pencil.
-/

/-- An arbitrary direction in the plane generated by the finite and tail
inverse-free `P₁` Schur residuals. -/
def fourCellOddP11UniversalCorePencilProfile
    (d e f g s t : ℝ) (r : ℝ → ℝ) : ℝ → ℝ := fun x ↦
  s * fourCellOddP11FiniteSchurResidualProfile d e f g x +
    t * fourCellOddP11TailSchurResidualProfile r x

theorem contDiff_fourCellOddP11UniversalCorePencilProfile
    (d e f g s t : ℝ) (r : ℝ → ℝ) (hr : ContDiff ℝ 1 r) :
    ContDiff ℝ 1
      (fourCellOddP11UniversalCorePencilProfile d e f g s t r) := by
  unfold fourCellOddP11UniversalCorePencilProfile
  exact
    (contDiff_const.mul
      (contDiff_fourCellOddP11FiniteSchurResidualProfile d e f g)).add
        (contDiff_const.mul
          (contDiff_fourCellOddP11TailSchurResidualProfile r hr))

theorem odd_fourCellOddP11UniversalCorePencilProfile
    (d e f g s t : ℝ) (r : ℝ → ℝ) (hodd : Function.Odd r) :
    Function.Odd
      (fourCellOddP11UniversalCorePencilProfile d e f g s t r) := by
  intro x
  unfold fourCellOddP11UniversalCorePencilProfile
  rw [odd_fourCellOddP11FiniteSchurResidualProfile d e f g,
    odd_fourCellOddP11TailSchurResidualProfile r hodd]
  ring

/-- Every direction of the mixed pencil is orthogonal to `P₁` for the
complete core bilinear form. -/
theorem fourCellOddCoreLocalBilinear_centeredP1_universalCorePencilProfile_eq_zero
    (d e f g s t : ℝ) (r : ℝ → ℝ)
    (hr : ContDiff ℝ 1 r) (hodd : Function.Odd r) :
    fourCellOddCoreLocalBilinear centeredP1
      (fourCellOddP11UniversalCorePencilProfile d e f g s t r) = 0 := by
  let h := fourCellOddP11FiniteSchurResidualProfile d e f g
  let q := fourCellOddP11TailSchurResidualProfile r
  let u : ℝ → ℝ := fun x ↦ s * h x
  let v : ℝ → ℝ := fun x ↦ t * q x
  have hh : ContDiff ℝ 1 h := by
    dsimp only [h]
    exact contDiff_fourCellOddP11FiniteSchurResidualProfile d e f g
  have hq : ContDiff ℝ 1 q := by
    dsimp only [q]
    exact contDiff_fourCellOddP11TailSchurResidualProfile r hr
  have hhodd : Function.Odd h := by
    dsimp only [h]
    exact odd_fourCellOddP11FiniteSchurResidualProfile d e f g
  have hqodd : Function.Odd q := by
    dsimp only [q]
    exact odd_fourCellOddP11TailSchurResidualProfile r hodd
  have hu : ContDiff ℝ 1 u := contDiff_const.mul hh
  have hv : ContDiff ℝ 1 v := contDiff_const.mul hq
  have huodd : Function.Odd u := by
    intro x
    dsimp only [u]
    rw [hhodd]
    ring
  have hvodd : Function.Odd v := by
    intro x
    dsimp only [v]
    rw [hqodd]
    ring
  have hP1 : ContDiff ℝ 1 centeredP1 := by
    unfold centeredP1
    fun_prop
  have hP1odd : Function.Odd centeredP1 := by
    intro x
    unfold centeredP1
    ring
  have hprofile :
      fourCellOddP11UniversalCorePencilProfile d e f g s t r = u + v := by
    funext x
    unfold fourCellOddP11UniversalCorePencilProfile
    dsimp only [u, v, h, q]
    simp only [Pi.add_apply]
  calc
    fourCellOddCoreLocalBilinear centeredP1
        (fourCellOddP11UniversalCorePencilProfile d e f g s t r) =
        fourCellOddCoreLocalBilinear (u + v) centeredP1 := by
      rw [hprofile]
      exact fourCellOddCoreLocalBilinear_comm
        centeredP1 (u + v) hP1.continuous (hu.add hv).continuous
    _ = fourCellOddCoreLocalBilinear u centeredP1 +
          fourCellOddCoreLocalBilinear v centeredP1 :=
      fourCellOddCoreLocalBilinear_add_left
        u v centeredP1 hu hv hP1 huodd hvodd hP1odd
    _ = s * fourCellOddCoreLocalBilinear h centeredP1 +
          t * fourCellOddCoreLocalBilinear q centeredP1 := by
      rw [show u = (fun x ↦ s * h x) by rfl,
        show v = (fun x ↦ t * q x) by rfl,
        fourCellOddCoreLocalBilinear_const_mul_left
          h centeredP1 hh hP1 hhodd hP1odd s,
        fourCellOddCoreLocalBilinear_const_mul_left
          q centeredP1 hq hP1 hqodd hP1odd t]
    _ = s * 0 + t * 0 := by
      rw [fourCellOddCoreLocalBilinear_comm h centeredP1
          hh.continuous hP1.continuous,
        fourCellOddCoreLocalBilinear_comm q centeredP1
          hq.continuous hP1.continuous]
      dsimp only [h, q]
      rw [fourCellOddCoreLocalBilinear_centeredP1_finiteSchurResidualProfile_eq_zero,
        fourCellOddCoreLocalBilinear_centeredP1_tailSchurResidualProfile_eq_zero
          r hr hodd]
    _ = 0 := by ring

/-- Exact quadratic expansion of the mixed residual plane. -/
theorem fourCellOddCoreLocalQuadratic_universalCorePencilProfile
    (d e f g s t : ℝ) (r : ℝ → ℝ)
    (hr : ContDiff ℝ 1 r) (hodd : Function.Odd r) :
    fourCellOddCoreLocalQuadratic
        (fourCellOddP11UniversalCorePencilProfile d e f g s t r) =
      fourCellOddCoreLocalQuadratic
          (fourCellOddP11FiniteSchurResidualProfile d e f g) * s ^ 2 +
        2 * fourCellOddCoreLocalBilinear
            (fourCellOddP11FiniteSchurResidualProfile d e f g)
            (fourCellOddP11TailSchurResidualProfile r) * s * t +
          fourCellOddCoreLocalQuadratic
              (fourCellOddP11TailSchurResidualProfile r) * t ^ 2 := by
  let h := fourCellOddP11FiniteSchurResidualProfile d e f g
  let q := fourCellOddP11TailSchurResidualProfile r
  let u : ℝ → ℝ := fun x ↦ s * h x
  let v : ℝ → ℝ := fun x ↦ t * q x
  have hh : ContDiff ℝ 1 h := by
    dsimp only [h]
    exact contDiff_fourCellOddP11FiniteSchurResidualProfile d e f g
  have hq : ContDiff ℝ 1 q := by
    dsimp only [q]
    exact contDiff_fourCellOddP11TailSchurResidualProfile r hr
  have hhodd : Function.Odd h := by
    dsimp only [h]
    exact odd_fourCellOddP11FiniteSchurResidualProfile d e f g
  have hqodd : Function.Odd q := by
    dsimp only [q]
    exact odd_fourCellOddP11TailSchurResidualProfile r hodd
  have hu : ContDiff ℝ 1 u := contDiff_const.mul hh
  have hv : ContDiff ℝ 1 v := contDiff_const.mul hq
  have huodd : Function.Odd u := by
    intro x
    dsimp only [u]
    rw [hhodd]
    ring
  have hvodd : Function.Odd v := by
    intro x
    dsimp only [v]
    rw [hqodd]
    ring
  have hprofile :
      fourCellOddP11UniversalCorePencilProfile d e f g s t r = u + v := by
    funext x
    unfold fourCellOddP11UniversalCorePencilProfile
    dsimp only [u, v, h, q]
    simp only [Pi.add_apply]
  have hqu := fourCellOddCoreLocalQuadratic_const_mul h hh hhodd s
  have hqv := fourCellOddCoreLocalQuadratic_const_mul q hq hqodd t
  have huv := fourCellOddCoreLocalBilinear_const_mul_right
    u q hu hq huodd hqodd t
  have hleft := fourCellOddCoreLocalBilinear_const_mul_left
    h q hh hq hhodd hqodd s
  rw [hprofile,
    fourCellOddCoreLocalQuadratic_add u v hu.continuous hv.continuous]
  dsimp only [u, v] at hqu hqv huv
  rw [hqu, hqv, huv, hleft]
  dsimp only [h, q]
  ring

/-- Universal nonnegativity of the actual two-dimensional residual plane. -/
def FourCellOddP11UniversalCorePencilNonnegative : Prop :=
  ∀ (d e f g : ℝ) (r : ℝ → ℝ),
    ContDiff ℝ 1 r → Function.Odd r →
    centeredOddP1Coefficient r = 0 →
    centeredOddP3Coefficient r = 0 →
    centeredOddP5Coefficient r = 0 →
    centeredOddP7Coefficient r = 0 →
    centeredOddP9Coefficient r = 0 →
    ∀ s t : ℝ,
      0 ≤ fourCellOddCoreLocalQuadratic
        (fourCellOddP11UniversalCorePencilProfile d e f g s t r)

/-- The direct corrected Cauchy frontier is exactly positivity of the full
core residual plane.  Thus a proof by quadratic nonnegativity loses no
correlation and introduces no scalar matched-weight surrogate. -/
theorem fourCellOddP11UniversalCorePencilNonnegative_iff_schurResidualCoreCauchy :
    FourCellOddP11UniversalCorePencilNonnegative ↔
      FourCellOddP11SchurResidualCoreCauchy := by
  constructor
  · intro hpencil d e f g r hr hodd h1 h3 h5 h7 h9
    let h := fourCellOddP11FiniteSchurResidualProfile d e f g
    let q := fourCellOddP11TailSchurResidualProfile r
    have hquad : ∀ s t : ℝ,
        0 ≤ fourCellOddCoreLocalQuadratic h * s ^ 2 +
          2 * fourCellOddCoreLocalBilinear h q * s * t +
            fourCellOddCoreLocalQuadratic q * t ^ 2 := by
      intro s t
      have hp := hpencil d e f g r hr hodd h1 h3 h5 h7 h9 s t
      rw [fourCellOddCoreLocalQuadratic_universalCorePencilProfile
        d e f g s t r hr hodd] at hp
      simpa only [h, q] using hp
    rcases (real_quadratic_pencil_nonneg_iff
      (fourCellOddCoreLocalQuadratic h)
      (fourCellOddCoreLocalQuadratic q)
      (fourCellOddCoreLocalBilinear h q)).mp hquad with
      ⟨_hfinite, htail, hcross⟩
    exact ⟨htail, hcross⟩
  · intro hcauchy d e f g r hr hodd h1 h3 h5 h7 h9 s t
    let h := fourCellOddP11FiniteSchurResidualProfile d e f g
    let q := fourCellOddP11TailSchurResidualProfile r
    rcases hcauchy d e f g r hr hodd h1 h3 h5 h7 h9 with
      ⟨htail, hcross⟩
    have hfiniteReserve :
        0 ≤ fourCellOddP11FiniteCorrectedReserve d e f g :=
      fourCellOddP11FiniteCorrectedReserve_nonnegative d e f g
    have hpivot : 0 ≤ fourCellOddCoreLocalQuadratic centeredP1 :=
      fourCellOddCoreLocalQuadratic_centeredP1_pos.le
    have hfinite : 0 ≤ fourCellOddCoreLocalQuadratic h := by
      dsimp only [h]
      rw [fourCellOddCoreLocalQuadratic_finiteSchurResidualProfile]
      exact mul_nonneg hpivot hfiniteReserve
    have hquad := (real_quadratic_pencil_nonneg_iff
      (fourCellOddCoreLocalQuadratic h)
      (fourCellOddCoreLocalQuadratic q)
      (fourCellOddCoreLocalBilinear h q)).2
        ⟨hfinite, htail, hcross⟩
    rw [fourCellOddCoreLocalQuadratic_universalCorePencilProfile
      d e f g s t r hr hodd]
    simpa only [h, q] using hquad s t

/-- Equivalently, positivity of this explicit core plane is exactly the
production direct-corrected frontier. -/
theorem fourCellOddP11UniversalCorePencilNonnegative_iff_directCorrectedCauchy :
    FourCellOddP11UniversalCorePencilNonnegative ↔
      FourCellOddP11DirectCorrectedCauchy :=
  fourCellOddP11UniversalCorePencilNonnegative_iff_schurResidualCoreCauchy.trans
    fourCellOddP11DirectCorrectedCauchy_iff_schurResidualCoreCauchy.symm

private theorem centeredOddP1Coefficient_add
    (u v : ℝ → ℝ) (hu : Continuous u) (hv : Continuous v) :
    centeredOddP1Coefficient (u + v) =
      centeredOddP1Coefficient u + centeredOddP1Coefficient v := by
  unfold centeredOddP1Coefficient
  have huI : IntervalIntegrable (fun x : ℝ ↦ u x * centeredP1 x)
      volume (-1) 1 :=
    (hu.mul (by unfold centeredP1; fun_prop)).intervalIntegrable _ _
  have hvI : IntervalIntegrable (fun x : ℝ ↦ v x * centeredP1 x)
      volume (-1) 1 :=
    (hv.mul (by unfold centeredP1; fun_prop)).intervalIntegrable _ _
  rw [show (fun x : ℝ ↦ (u + v) x * centeredP1 x) =
      fun x ↦ u x * centeredP1 x + v x * centeredP1 x by
    funext x
    simp only [Pi.add_apply]
    ring,
    intervalIntegral.integral_add huI hvI]
  ring

private theorem centeredOddP1Coefficient_const_mul
    (v : ℝ → ℝ) (a : ℝ) :
    centeredOddP1Coefficient (fun x ↦ a * v x) =
      a * centeredOddP1Coefficient v := by
  unfold centeredOddP1Coefficient
  rw [show (fun x : ℝ ↦ a * v x * centeredP1 x) =
      fun x ↦ a * (v x * centeredP1 x) by
    funext x
    ring,
    intervalIntegral.integral_const_mul]
  ring

private theorem centeredOddP1Coefficient_centeredP1_eq_one :
    centeredOddP1Coefficient centeredP1 = 1 := by
  unfold centeredOddP1Coefficient
  rw [show (fun x : ℝ ↦ centeredP1 x * centeredP1 x) =
      fun x ↦ centeredP1 x ^ 2 by
    funext x
    ring,
    integral_centeredP1_sq]
  norm_num

/-- The Legendre `P₁` coefficient of a canonical retained five-mode
profile is exactly its first coordinate. -/
theorem centeredOddP1Coefficient_fiveModeLowProfile
    (c d e f g : ℝ) :
    centeredOddP1Coefficient
      (fourCellOddOneThreeFiveSevenNineLowProfile c d e f g) = c := by
  unfold fourCellOddOneThreeFiveSevenNineLowProfile
    fourCellOddOneThreeFiveLowProfile factorTwoOddStructuralLowProfile
  rw [show factorTwoCenteredP7 = fun x ↦
      (429 * x ^ 7 - 693 * x ^ 5 + 315 * x ^ 3 - 35 * x) / 16 by
    funext x
    exact factorTwoCenteredP7_eq x,
    show factorTwoCenteredP9 = fun x ↦
      (12155 * x ^ 9 - 25740 * x ^ 7 + 18018 * x ^ 5 -
        4620 * x ^ 3 + 315 * x) / 128 by
      funext x
      exact factorTwoCenteredP9_eq x]
  unfold centeredOddP1Coefficient centeredP1 centeredP3 factorTwoCenteredP5
  ring_nf
  repeat rw [intervalIntegral.integral_add
    (Continuous.intervalIntegrable (by fun_prop) (-1) 1)
    (Continuous.intervalIntegrable (by fun_prop) (-1) 1)]
  norm_num
  ring

/-- The finite core-Schur residual is not generally Legendre-orthogonal to
`P₁`: its coefficient is the negative finite extension row. -/
theorem centeredOddP1Coefficient_finiteSchurResidualProfile
    (d e f g : ℝ) :
    centeredOddP1Coefficient
        (fourCellOddP11FiniteSchurResidualProfile d e f g) =
      -fourCellOddCoreLocalBilinear centeredP1
        (fourCellOddOneThreeFiveSevenNineLowProfile 0 d e f g) := by
  unfold fourCellOddP11FiniteSchurResidualProfile
  rw [centeredOddP1Coefficient_fiveModeLowProfile]

/-- For a genuine `P₁`-zero tail, the tail core-Schur residual likewise
has coefficient equal to the negative tail extension row. -/
theorem centeredOddP1Coefficient_tailSchurResidualProfile
    (r : ℝ → ℝ) (hr : ContDiff ℝ 1 r)
    (h1 : centeredOddP1Coefficient r = 0) :
    centeredOddP1Coefficient (fourCellOddP11TailSchurResidualProfile r) =
      -fourCellOddCoreLocalBilinear centeredP1 r := by
  let A := fourCellOddCoreLocalQuadratic centeredP1
  let b := fourCellOddCoreLocalBilinear centeredP1 r
  let u : ℝ → ℝ := fun x ↦ A * r x
  let v : ℝ → ℝ := fun x ↦ (-b) * centeredP1 x
  have hu : Continuous u := (contDiff_const.mul hr).continuous
  have hv : Continuous v := by
    dsimp only [v]
    unfold centeredP1
    fun_prop
  have hprofile : fourCellOddP11TailSchurResidualProfile r = u + v := by
    funext x
    unfold fourCellOddP11TailSchurResidualProfile
    dsimp only [A, b, u, v]
    simp only [Pi.add_apply]
    ring
  rw [hprofile, centeredOddP1Coefficient_add u v hu hv]
  dsimp only [u, v]
  rw [centeredOddP1Coefficient_const_mul,
    centeredOddP1Coefficient_const_mul, h1,
    centeredOddP1Coefficient_centeredP1_eq_one]
  dsimp only [b]
  ring

/-- Exact Legendre coefficient of an arbitrary mixed core-Schur direction.
The existing `P₁`-zero coercivity theorem therefore covers only the single
line where the displayed extension-row combination vanishes. -/
theorem centeredOddP1Coefficient_universalCorePencilProfile
    (d e f g s t : ℝ) (r : ℝ → ℝ)
    (hr : ContDiff ℝ 1 r) (h1 : centeredOddP1Coefficient r = 0) :
    centeredOddP1Coefficient
        (fourCellOddP11UniversalCorePencilProfile d e f g s t r) =
      -(s * fourCellOddCoreLocalBilinear centeredP1
          (fourCellOddOneThreeFiveSevenNineLowProfile 0 d e f g) +
        t * fourCellOddCoreLocalBilinear centeredP1 r) := by
  let h := fourCellOddP11FiniteSchurResidualProfile d e f g
  let q := fourCellOddP11TailSchurResidualProfile r
  let u : ℝ → ℝ := fun x ↦ s * h x
  let v : ℝ → ℝ := fun x ↦ t * q x
  have hh : ContDiff ℝ 1 h := by
    dsimp only [h]
    exact contDiff_fourCellOddP11FiniteSchurResidualProfile d e f g
  have hq : ContDiff ℝ 1 q := by
    dsimp only [q]
    exact contDiff_fourCellOddP11TailSchurResidualProfile r hr
  have hu : Continuous u := (contDiff_const.mul hh).continuous
  have hv : Continuous v := (contDiff_const.mul hq).continuous
  have hprofile :
      fourCellOddP11UniversalCorePencilProfile d e f g s t r = u + v := by
    funext x
    unfold fourCellOddP11UniversalCorePencilProfile
    dsimp only [u, v, h, q]
    simp only [Pi.add_apply]
  rw [hprofile, centeredOddP1Coefficient_add u v hu hv]
  dsimp only [u, v]
  rw [centeredOddP1Coefficient_const_mul,
    centeredOddP1Coefficient_const_mul]
  dsimp only [h, q]
  rw [centeredOddP1Coefficient_finiteSchurResidualProfile,
    centeredOddP1Coefficient_tailSchurResidualProfile r hr h1]
  ring

/-- The available `P₁`-zero coercivity proves precisely those pencil
directions whose extension-row combination vanishes. -/
theorem fourCellOddCoreLocalQuadratic_universalCorePencilProfile_nonneg_of_row_zero
    (d e f g s t : ℝ) (r : ℝ → ℝ)
    (hr : ContDiff ℝ 1 r) (hodd : Function.Odd r)
    (h1 : centeredOddP1Coefficient r = 0)
    (hrow :
      s * fourCellOddCoreLocalBilinear centeredP1
          (fourCellOddOneThreeFiveSevenNineLowProfile 0 d e f g) +
        t * fourCellOddCoreLocalBilinear centeredP1 r = 0) :
    0 ≤ fourCellOddCoreLocalQuadratic
      (fourCellOddP11UniversalCorePencilProfile d e f g s t r) := by
  apply fourCellOddCoreLocalQuadratic_nonneg_of_P1_zero
    (fourCellOddP11UniversalCorePencilProfile d e f g s t r)
    (contDiff_fourCellOddP11UniversalCorePencilProfile d e f g s t r hr)
    (odd_fourCellOddP11UniversalCorePencilProfile d e f g s t r hodd)
  rw [centeredOddP1Coefficient_universalCorePencilProfile
    d e f g s t r hr h1, hrow]
  ring

private theorem fourCellOddCoreLocalBilinear_centeredP1_centeredP3_eq_perturbed13 :
    fourCellOddCoreLocalBilinear centeredP1 centeredP3 =
      fourCellOddOneThreeFivePerturbed13 := by
  have hsum :=
    fourCellOddCoreLocalQuadratic_oneThreeFiveLowProfile_eq_perturbed 1 1 0
  have hP1 :=
    fourCellOddCoreLocalQuadratic_oneThreeFiveLowProfile_eq_perturbed 1 0 0
  have hP3 :=
    fourCellOddCoreLocalQuadratic_oneThreeFiveLowProfile_eq_perturbed 0 1 0
  have hpSum : fourCellOddOneThreeFiveLowProfile 1 1 0 =
      centeredP1 + centeredP3 := by
    funext x
    unfold fourCellOddOneThreeFiveLowProfile factorTwoOddStructuralLowProfile
    simp only [Pi.add_apply]
    ring
  have hp1 : fourCellOddOneThreeFiveLowProfile 1 0 0 = centeredP1 := by
    funext x
    unfold fourCellOddOneThreeFiveLowProfile factorTwoOddStructuralLowProfile
    simp
  have hp3 : fourCellOddOneThreeFiveLowProfile 0 1 0 = centeredP3 := by
    funext x
    unfold fourCellOddOneThreeFiveLowProfile factorTwoOddStructuralLowProfile
    simp
  rw [hpSum] at hsum
  rw [hp1] at hP1
  rw [hp3] at hP3
  have hadd := fourCellOddCoreLocalQuadratic_add centeredP1 centeredP3
    (by unfold centeredP1; fun_prop) (by unfold centeredP3; fun_prop)
  rw [hsum, hP1, hP3] at hadd
  unfold fourCellOddOneThreeFivePerturbedQuadratic at hadd
  norm_num at hadd
  linarith

/-- Formal obstruction to using the existing Legendre-`P₁` coercivity on
the whole Schur plane: already the retained `P₃` Schur residual has a
strictly nonzero `P₁` coefficient, despite being core-orthogonal to `P₁`. -/
theorem centeredOddP1Coefficient_finiteSchurResidualProfile_P3_ne_zero :
    centeredOddP1Coefficient
      (fourCellOddP11FiniteSchurResidualProfile 1 0 0 0) ≠ 0 := by
  rw [centeredOddP1Coefficient_finiteSchurResidualProfile]
  have hp : fourCellOddOneThreeFiveSevenNineLowProfile 0 1 0 0 0 =
      centeredP3 := by
    funext x
    unfold fourCellOddOneThreeFiveSevenNineLowProfile
      fourCellOddOneThreeFiveLowProfile factorTwoOddStructuralLowProfile
    simp
  rw [hp, fourCellOddCoreLocalBilinear_centeredP1_centeredP3_eq_perturbed13]
  rcases fourCellOddOneThreeFivePerturbed_entry_bounds with
    ⟨_h11lo, _h11hi, h13lo, _⟩
  intro hzero
  rw [neg_eq_zero] at hzero
  rw [hzero] at h13lo
  norm_num at h13lo

end

end ArithmeticHodge.Analysis.YoshidaFourCellOddP11UniversalCoreCauchyStructural
