/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 000; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceData

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row000_000_le :
    evenSparseDominanceBlockContribution (0 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (0 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row001_000_le :
    evenSparseDominanceBlockContribution (1 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (1 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row001_001_le :
    evenSparseDominanceBlockContribution (1 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (1 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row002_000_le :
    evenSparseDominanceBlockContribution (2 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (2 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row002_001_le :
    evenSparseDominanceBlockContribution (2 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (2 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row002_002_le :
    evenSparseDominanceBlockContribution (2 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (2 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row003_000_le :
    evenSparseDominanceBlockContribution (3 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (3 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row003_001_le :
    evenSparseDominanceBlockContribution (3 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (3 : YoshidaEvenIndex) 1 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
