/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 019; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks018

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row023_005_le :
    evenSparseDominanceBlockContribution (23 : YoshidaEvenIndex) 5 ≤
      evenSparseDominanceBlockBudget (23 : YoshidaEvenIndex) 5 := by
  decide +kernel

theorem evenSparseDominanceBlock_row024_000_le :
    evenSparseDominanceBlockContribution (24 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (24 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row024_001_le :
    evenSparseDominanceBlockContribution (24 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (24 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row024_002_le :
    evenSparseDominanceBlockContribution (24 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (24 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row024_003_le :
    evenSparseDominanceBlockContribution (24 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (24 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row024_004_le :
    evenSparseDominanceBlockContribution (24 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (24 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row024_005_le :
    evenSparseDominanceBlockContribution (24 : YoshidaEvenIndex) 5 ≤
      evenSparseDominanceBlockBudget (24 : YoshidaEvenIndex) 5 := by
  decide +kernel

theorem evenSparseDominanceBlock_row025_000_le :
    evenSparseDominanceBlockContribution (25 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (25 : YoshidaEvenIndex) 0 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
