/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 042; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks041

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row065_000_le :
    evenSparseDominanceBlockContribution (65 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (65 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row065_001_le :
    evenSparseDominanceBlockContribution (65 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (65 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row065_002_le :
    evenSparseDominanceBlockContribution (65 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (65 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row065_003_le :
    evenSparseDominanceBlockContribution (65 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (65 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row066_000_le :
    evenSparseDominanceBlockContribution (66 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (66 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row066_001_le :
    evenSparseDominanceBlockContribution (66 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (66 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row066_002_le :
    evenSparseDominanceBlockContribution (66 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (66 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row066_003_le :
    evenSparseDominanceBlockContribution (66 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (66 : YoshidaEvenIndex) 3 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
