import ArithmeticHodge.Analysis.YoshidaEndpointPotentialIntegrable
import Mathlib.Analysis.SpecialFunctions.Log.NegMulLog

set_option autoImplicit false

open MeasureTheory Real Set

namespace ArithmeticHodge.Analysis.YoshidaEndpointPotentialPrefixMomentStructural

open YoshidaEndpointPotentialBound
open YoshidaEndpointPotentialIntegrable

noncomputable section

/-!
# Structural prefix moments of the endpoint potential

All endpoint-truncated polynomial moments of the logarithmic potential are
generated by one two-step recurrence.  Its antiderivative is continuous at
both singular endpoints through `Real.negMulLog`, so the statement is valid
on the entire closed interval without endpoint cutoffs.
-/

/-- The degree-`n` endpoint-potential moment truncated at `u`. -/
def endpointPotentialPrefixMoment (n : ℕ) (u : ℝ) : ℝ :=
  ∫ x : ℝ in -1..u, yoshidaEndpointPotential x * x ^ n

/-- Exact all-degree recurrence for truncated endpoint-potential moments. -/
theorem endpointPotentialPrefixMoment_recurrence
    (n : ℕ) {u : ℝ} (hu : u ∈ Icc (-1 : ℝ) 1) :
    (n + 3 : ℝ) * endpointPotentialPrefixMoment (n + 2) u -
        (n + 1 : ℝ) * endpointPotentialPrefixMoment n u =
      -(1 / 2 : ℝ) * u ^ (n + 1) * Real.negMulLog (1 - u ^ 2) +
        u ^ (n + 3) / (n + 3 : ℝ) -
          (-1 : ℝ) ^ (n + 3) / (n + 3 : ℝ) := by
  let F : ℝ → ℝ := fun x ↦
    -(1 / 2 : ℝ) * x ^ (n + 1) * Real.negMulLog (1 - x ^ 2) +
      x ^ (n + 3) / (n + 3 : ℝ)
  let f : ℝ → ℝ := fun x ↦
    yoshidaEndpointPotential x *
      ((n + 3 : ℝ) * x ^ (n + 2) - (n + 1 : ℝ) * x ^ n)
  have hFcont : Continuous F := by
    dsimp only [F]
    fun_prop
  have hderiv (x : ℝ) (hx : x ∈ Ioo (-1 : ℝ) u) :
      HasDerivAt F (f x) x := by
    have hxInside : x ∈ Ioo (-1 : ℝ) 1 := ⟨hx.1, hx.2.trans_le hu.2⟩
    have hy : 1 - x ^ 2 ≠ 0 := by
      have habs : |x| < 1 := (abs_lt).2 hxInside
      nlinarith [(sq_lt_one_iff_abs_lt_one x).2 habs]
    have hinner : HasDerivAt (fun y : ℝ ↦ 1 - y ^ 2) (-2 * x) x := by
      convert (hasDerivAt_const x (1 : ℝ)).sub ((hasDerivAt_id x).pow 2) using 1
      all_goals simp
    have hnegMulLog := (Real.hasDerivAt_negMulLog hy).comp x hinner
    have hleft :=
      (((hasDerivAt_id x).pow (n + 1)).mul hnegMulLog).const_mul
        (-(1 / 2 : ℝ))
    have hright :=
      ((hasDerivAt_id x).pow (n + 3)).div_const (n + 3 : ℝ)
    convert hleft.add hright using 1
    · funext y
      dsimp only [F]
      simp only [Pi.add_apply, Pi.mul_apply, Pi.pow_apply,
        Function.comp_apply, id_eq]
      ring
    · dsimp only [f, yoshidaEndpointPotential, Real.negMulLog]
      have hden : (n + 3 : ℝ) ≠ 0 := by positivity
      have hn1 : n + 1 - 1 = n := by omega
      have hn3 : n + 3 - 1 = n + 2 := by omega
      simp only [Real.negMulLog_def, Function.comp_apply, Pi.pow_apply,
        id_eq, hn1, hn3, Nat.cast_add, Nat.cast_ofNat]
      field_simp [hy, hden]
      ring
  have hmoment (k : ℕ) : IntervalIntegrable
      (fun x : ℝ ↦ yoshidaEndpointPotential x * x ^ k)
      volume (-1) u := by
    exact (intervalIntegrable_endpointPotential_mul
      (fun x : ℝ ↦ x ^ k) (continuous_id.pow k)).mono_set
        (uIcc_subset_uIcc_left (by
          simpa [uIcc_of_le (by norm_num : (-1 : ℝ) ≤ 1)] using hu))
  have hf : IntervalIntegrable f volume (-1) u := by
    have h :=
      ((hmoment (n + 2)).const_mul (n + 3 : ℝ)).sub
        ((hmoment n).const_mul (n + 1 : ℝ))
    apply h.congr
    intro x _hx
    dsimp only [f]
    ring
  have hFTC :
      (∫ x : ℝ in -1..u, f x) =
        -(1 / 2 : ℝ) * u ^ (n + 1) * Real.negMulLog (1 - u ^ 2) +
          u ^ (n + 3) / (n + 3 : ℝ) -
            (-1 : ℝ) ^ (n + 3) / (n + 3 : ℝ) := by
    rw [intervalIntegral.integral_eq_sub_of_hasDerivAt_of_le
      hu.1 hFcont.continuousOn hderiv hf]
    dsimp only [F]
    simp only [Real.negMulLog_zero, neg_one_sq, sub_self, mul_zero,
      zero_add]
  have hsplit :
      (∫ x : ℝ in -1..u, f x) =
        (n + 3 : ℝ) *
            (∫ x : ℝ in -1..u,
              yoshidaEndpointPotential x * x ^ (n + 2)) -
          (n + 1 : ℝ) *
            (∫ x : ℝ in -1..u,
              yoshidaEndpointPotential x * x ^ n) := by
    rw [show f = fun x : ℝ ↦
        (n + 3 : ℝ) * (yoshidaEndpointPotential x * x ^ (n + 2)) -
          (n + 1 : ℝ) * (yoshidaEndpointPotential x * x ^ n) by
      funext x
      dsimp only [f]
      ring]
    rw [intervalIntegral.integral_sub
        ((hmoment (n + 2)).const_mul (n + 3 : ℝ))
        ((hmoment n).const_mul (n + 1 : ℝ)),
      intervalIntegral.integral_const_mul,
      intervalIntegral.integral_const_mul]
  rw [hsplit] at hFTC
  simpa only [endpointPotentialPrefixMoment] using hFTC

end

end ArithmeticHodge.Analysis.YoshidaEndpointPotentialPrefixMomentStructural
