/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 023; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks022

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row029_004_le :
    evenSparseDominanceBlockContribution (29 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (29 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row030_000_le :
    evenSparseDominanceBlockContribution (30 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (30 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row030_001_le :
    evenSparseDominanceBlockContribution (30 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (30 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row030_002_le :
    evenSparseDominanceBlockContribution (30 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (30 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row030_003_le :
    evenSparseDominanceBlockContribution (30 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (30 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row030_004_le :
    evenSparseDominanceBlockContribution (30 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (30 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row031_000_le :
    evenSparseDominanceBlockContribution (31 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (31 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row031_001_le :
    evenSparseDominanceBlockContribution (31 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (31 : YoshidaEvenIndex) 1 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
