/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 062; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks061

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row111_001_le :
    evenSparseDominanceBlockContribution (111 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (111 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row111_002_le :
    evenSparseDominanceBlockContribution (111 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (111 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row112_000_le :
    evenSparseDominanceBlockContribution (112 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (112 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row112_001_le :
    evenSparseDominanceBlockContribution (112 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (112 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row112_002_le :
    evenSparseDominanceBlockContribution (112 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (112 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row113_000_le :
    evenSparseDominanceBlockContribution (113 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (113 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row113_001_le :
    evenSparseDominanceBlockContribution (113 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (113 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row113_002_le :
    evenSparseDominanceBlockContribution (113 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (113 : YoshidaEvenIndex) 2 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
