import ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedRowStructural
import ArithmeticHodge.Analysis.YoshidaFourCellEvenZeroCoshCoupledCoreStructural

set_option autoImplicit false

open MeasureTheory Polynomial Real Set
open scoped Interval

namespace ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedCutoffEightBridgeStructural

noncomputable section

open MultiplicativeWeilFourCellRealRescaleStructural
open ShiftedLegendreOrthogonality
open ShiftedLegendreLogEnergyOrthogonalProjection
open YoshidaEndpointEvenStructuralReduction
open YoshidaEndpointPotentialBound
open YoshidaFactorTwoEndpointBilinear
open YoshidaFactorTwoContinuousLagRepresenterStructural
open YoshidaFactorTwoIntegrableLagRepresenterStructural
open YoshidaFactorTwoPhaseIntrinsicNineP6EvenProfileCorrelationStructural
open YoshidaFactorTwoPhaseIntrinsicNineP6EvenCleanPolynomialGramStructural
open YoshidaFactorTwoPhaseIntrinsicNineCanonicalProjectionStructural
open YoshidaFactorTwoPhaseIntrinsicHigherResidual
open YoshidaFactorTwoPhaseIntrinsicSixP4EndpointProfile
open YoshidaFactorTwoPhaseIntrinsicSixSchurReduction
open YoshidaFactorTwoPhaseLegendreFourFiveStructural
open YoshidaFactorTwoPhaseLegendreSixSevenStructuralPositive
open YoshidaFactorTwoPhaseHigherLegendreDecomposition
open YoshidaFactorTwoPhaseLowSchur
open YoshidaFourCellEvenEndpointCapacityCauchyStructural
open YoshidaFourCellEvenEndpointCoshSchurStructural
open YoshidaFourCellEvenEndpointSeedRowStructural
open YoshidaFourCellEvenPolarSchurStructural
open YoshidaFourCellParityHalfFoldStructural
open YoshidaFourCellParityOperatorStructural
open YoshidaFourCellEvenZeroCoshCoupledCoreStructural
open YoshidaFourCellEvenZeroCoshRegularStructural
open YoshidaRegularKernelBound

/-!
# The endpoint seed in the cutoff-eight coordinates

The fixed outer Schur row uses the endpoint-zero seed `1 - x^2`.  The
cutoff-eight core proof uses the first four even Legendre coordinates.  This
file identifies the seed with its exact `P0/P2/P4/P6` vector and shows that
its mixed coupled-core row against a `P8+` residual is precisely the retained
endpoint-capacity row.  Thus no raw-log tail term survives in the outer
determinant.
-/

/-- The endpoint-zero seed is the exact low vector
`(2/3, -2/3, 0, 0)` in the cutoff-eight even Legendre basis. -/
theorem fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile :
    fourCellEvenEndpointCoshSeed =
      factorTwoIntrinsicEvenP0246Profile (2 / 3) (-2 / 3) 0 0 := by
  funext x
  unfold fourCellEvenEndpointCoshSeed
    factorTwoIntrinsicEvenP0246Profile
    factorTwoIntrinsicEvenP024Profile
    factorTwoEvenStructuralLowProfile
    factorTwoIntrinsicSixEvenTail centeredEvenP0 centeredEvenP2
  simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
  ring

/-- Symmetry of the retained endpoint-capacity polarization. -/
theorem fourCellEvenEndpointCapacityPolarization_comm
    (u v : ℝ → ℝ) :
    fourCellEvenEndpointCapacityPolarization u v =
      fourCellEvenEndpointCapacityPolarization v u := by
  have hpotential :
      (∫ x : ℝ in -1..1, yoshidaEndpointPotential x * u x * v x) =
        ∫ x : ℝ in -1..1,
          yoshidaEndpointPotential x * v x * u x := by
    apply intervalIntegral.integral_congr
    intro x _hx
    ring
  unfold fourCellEvenEndpointCapacityPolarization
  rw [hpotential, factorTwoCenteredCorrelationBilinear_comm]

/-- The one-variable Riesz representer of the smooth regular-kernel row
generated by the endpoint-zero seed. -/
def fourCellEvenEndpointSeedRegularTailRepresenter (x : ℝ) : ℝ :=
  factorTwoContinuousLagK
    (fun t : ℝ ↦ yoshidaRegularKernel (fourCellOperatorHalfWidth * t))
    fourCellEvenEndpointCoshSeed x

/-- A projected representer of the complete surviving endpoint-seed tail
row.  The capacity and smooth regular pieces stay combined pointwise. -/
def fourCellEvenEndpointSeedProjectedTailRowRepresenter
    (q : ℝ[X]) (x : ℝ) : ℝ :=
  fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
      (2 / 3) (-2 / 3) 0 0 q x -
    fourCellOperatorHalfWidth *
      fourCellEvenEndpointSeedRegularTailRepresenter x

private theorem fourCellRegularLag_abs_le_quarter
    (t : ℝ) (ht : t ∈ Icc (0 : ℝ) 2) :
    |yoshidaRegularKernel (fourCellOperatorHalfWidth * t)| ≤ 1 / 4 := by
  have ha0 : 0 ≤ fourCellOperatorHalfWidth := by
    unfold fourCellOperatorHalfWidth
    positivity
  have harg0 : 0 ≤ fourCellOperatorHalfWidth * t :=
    mul_nonneg ha0 ht.1
  have harg4 : fourCellOperatorHalfWidth * t ≤
      5 * Real.log 2 / 4 := by
    calc
      fourCellOperatorHalfWidth * t ≤ fourCellOperatorHalfWidth * 2 :=
        mul_le_mul_of_nonneg_left ht.2 ha0
      _ = 5 * Real.log 2 / 4 := by
        unfold fourCellOperatorHalfWidth
        ring
  have hk0 := yoshidaRegularKernel_nonneg_fourCellRange harg0 harg4
  rw [abs_of_nonneg hk0]
  exact yoshidaRegularKernel_le_quarter harg0

private theorem abs_fourCellEvenEndpointCoshSeed_le_one
    {x : ℝ} (hx : x ∈ Icc (-1 : ℝ) 1) :
    |fourCellEvenEndpointCoshSeed x| ≤ 1 := by
  have hprod : 0 ≤ (x + 1) * (1 - x) :=
    mul_nonneg (by linarith [hx.1]) (by linarith [hx.2])
  have hnonneg : 0 ≤ 1 - x ^ 2 := by
    nlinarith only [hprod]
  unfold fourCellEvenEndpointCoshSeed
  rw [abs_of_nonneg hnonneg]
  nlinarith only [sq_nonneg x]

private theorem norm_fourCellEvenEndpointSeedRegularTailRepresenter_le_one
    {x : ℝ} (hx : x ∈ Ioc (-1 : ℝ) 1) :
    ‖fourCellEvenEndpointSeedRegularTailRepresenter x‖ ≤ 1 := by
  let k : ℝ → ℝ := fun t ↦
    yoshidaRegularKernel (fourCellOperatorHalfWidth * t)
  have hrightPoint : ∀ y ∈ Ι x 1,
      ‖k (y - x) * fourCellEvenEndpointCoshSeed y‖ ≤ (1 / 4 : ℝ) := by
    intro y hy
    rw [uIoc_of_le hx.2] at hy
    have hyIcc : y ∈ Icc (-1 : ℝ) 1 :=
      ⟨by linarith [hx.1, hy.1], hy.2⟩
    have hlag : y - x ∈ Icc (0 : ℝ) 2 :=
      ⟨by linarith [hy.1], by linarith [hx.1, hy.2]⟩
    have hk := fourCellRegularLag_abs_le_quarter (y - x) hlag
    have hs := abs_fourCellEvenEndpointCoshSeed_le_one hyIcc
    rw [Real.norm_eq_abs, abs_mul]
    exact (mul_le_mul hk hs (abs_nonneg _) (by norm_num)).trans_eq (by norm_num)
  have hleftPoint : ∀ y ∈ Ι (-1) x,
      ‖k (x - y) * fourCellEvenEndpointCoshSeed y‖ ≤ (1 / 4 : ℝ) := by
    intro y hy
    rw [uIoc_of_le hx.1.le] at hy
    have hyIcc : y ∈ Icc (-1 : ℝ) 1 :=
      ⟨hy.1.le, by linarith [hy.2, hx.2]⟩
    have hlag : x - y ∈ Icc (0 : ℝ) 2 :=
      ⟨by linarith [hy.2], by linarith [hy.1, hx.2]⟩
    have hk := fourCellRegularLag_abs_le_quarter (x - y) hlag
    have hs := abs_fourCellEvenEndpointCoshSeed_le_one hyIcc
    rw [Real.norm_eq_abs, abs_mul]
    exact (mul_le_mul hk hs (abs_nonneg _) (by norm_num)).trans_eq (by norm_num)
  have hright := intervalIntegral.norm_integral_le_of_norm_le_const hrightPoint
  have hleft := intervalIntegral.norm_integral_le_of_norm_le_const hleftPoint
  have hrightHalf :
      ‖factorTwoContinuousLagRightRepresenter
          k fourCellEvenEndpointCoshSeed x‖ ≤ 1 / 2 := by
    have habs : |1 - x| ≤ 2 := by
      rw [abs_of_nonneg (by linarith [hx.2])]
      linarith [hx.1]
    change ‖∫ y : ℝ in x..1,
      k (y - x) * fourCellEvenEndpointCoshSeed y‖ ≤ 1 / 2
    calc
      _ ≤ (1 / 4 : ℝ) * |1 - x| := hright
      _ ≤ 1 / 2 := by nlinarith only [habs]
  have hleftHalf :
      ‖factorTwoContinuousLagLeftRepresenter
          k fourCellEvenEndpointCoshSeed x‖ ≤ 1 / 2 := by
    have habs : |x - (-1)| ≤ 2 := by
      rw [abs_of_nonneg (by linarith [hx.1])]
      linarith [hx.2]
    change ‖∫ y : ℝ in -1..x,
      k (x - y) * fourCellEvenEndpointCoshSeed y‖ ≤ 1 / 2
    calc
      _ ≤ (1 / 4 : ℝ) * |x - (-1)| := hleft
      _ ≤ 1 / 2 := by nlinarith only [habs]
  unfold fourCellEvenEndpointSeedRegularTailRepresenter
    factorTwoContinuousLagK
  dsimp only [k] at hrightHalf hleftHalf ⊢
  exact (norm_add_le _ _).trans (by linarith)

/-- The smooth endpoint-seed lag representer is square-integrable on the
centered interval. -/
theorem memLp_fourCellEvenEndpointSeedRegularTailRepresenter :
    MemLp fourCellEvenEndpointSeedRegularTailRepresenter 2
      (volume.restrict (Ioc (-1 : ℝ) 1)) := by
  let k : ℝ → ℝ := fun t ↦
    yoshidaRegularKernel (fourCellOperatorHalfWidth * t)
  have hk : Measurable k := by
    dsimp only [k]
    exact measurable_yoshidaRegularKernel.comp
      (measurable_const.mul measurable_id)
  have hkbound : ∀ t ∈ Icc (0 : ℝ) 2, |k t| ≤ 1 / 4 := by
    intro t ht
    simpa only [k] using fourCellRegularLag_abs_le_quarter t ht
  have hright :=
    intervalIntegrable_mul_factorTwoContinuousLagRightRepresenter_of_bounded
      k fourCellEvenEndpointCoshSeed (fun _ : ℝ ↦ 1) hk
        fourCellEvenEndpointCoshSeed_continuous continuous_const
        (1 / 4) hkbound
  have hleft :=
    intervalIntegrable_mul_factorTwoContinuousLagLeftRepresenter_of_bounded
      k (fun _ : ℝ ↦ 1) fourCellEvenEndpointCoshSeed hk continuous_const
        fourCellEvenEndpointCoshSeed_continuous (1 / 4) hkbound
  have hK : IntervalIntegrable fourCellEvenEndpointSeedRegularTailRepresenter
      volume (-1) 1 := by
    apply (hright.add hleft).congr
    intro x _hx
    unfold fourCellEvenEndpointSeedRegularTailRepresenter
      factorTwoContinuousLagK
    dsimp only [k]
    ring
  have hmeas : AEStronglyMeasurable
      fourCellEvenEndpointSeedRegularTailRepresenter
      (volume.restrict (Ioc (-1 : ℝ) 1)) := hK.1.aestronglyMeasurable
  apply MemLp.of_bound hmeas 1
  filter_upwards [ae_restrict_mem measurableSet_Ioc] with x hx
  exact norm_fourCellEvenEndpointSeedRegularTailRepresenter_le_one hx

/-- Every polynomially projected complete endpoint-seed tail representer is
square-integrable. -/
theorem memLp_fourCellEvenEndpointSeedProjectedTailRowRepresenter
    (q : ℝ[X]) :
    MemLp (fourCellEvenEndpointSeedProjectedTailRowRepresenter q) 2
      (volume.restrict (Ioc (-1 : ℝ) 1)) := by
  have hcapacity :=
    memLp_fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
      (2 / 3) (-2 / 3) 0 0 q
  have hregular :=
    memLp_fourCellEvenEndpointSeedRegularTailRepresenter.const_mul
      fourCellOperatorHalfWidth
  simpa only [fourCellEvenEndpointSeedProjectedTailRowRepresenter] using
    hcapacity.sub hregular

private theorem endpointSeedProfile_add_intrinsicEvenP0246
    (c0 c2 c4 c6 : ℝ) :
    factorTwoIntrinsicEvenP0246Profile (2 / 3) (-2 / 3) 0 0 +
        factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 =
      factorTwoIntrinsicEvenP0246Profile
        (2 / 3 + c0) (-2 / 3 + c2) c4 c6 := by
  funext x
  unfold factorTwoIntrinsicEvenP0246Profile
    factorTwoIntrinsicEvenP024Profile
    factorTwoEvenStructuralLowProfile
    factorTwoIntrinsicSixEvenTail centeredEvenP0 centeredEvenP2
  simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
  ring

/-- The exact four-coordinate coupled-core row of the endpoint seed on the
finite cutoff-eight block. -/
def fourCellEvenEndpointSeedP0246CoreRow
    (c0 c2 c4 c6 : ℝ) : ℝ :=
  ((10 / 9 : ℝ) - (4 / 3) * Real.log 2 -
      (52 / 375) * Real.sqrt 2 * Real.log 2) * c0 +
    (-(122 / 225 : ℝ) + (4 / 15) * Real.log 2 -
      (4076 / 46875) * Real.sqrt 2 * Real.log 2) * c2 +
    (-(1 / 35 : ℝ) -
      (4544 / 234375) * Real.sqrt 2 * Real.log 2) * c4 +
    (-(1 / 189 : ℝ) +
      (16576 / 1953125) * Real.sqrt 2 * Real.log 2) * c6

/-- The complete finite endpoint-seed row on the `P0/P2/P4/P6` block. -/
def fourCellEvenEndpointSeedP0246CompleteLowRow
    (c0 c2 c4 c6 : ℝ) : ℝ :=
  fourCellEvenEndpointSeedP0246CoreRow c0 c2 c4 c6 -
    fourCellEvenSignedMassRegularPolarization
      fourCellEvenEndpointCoshSeed
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6)

/-- Exact evaluation of the finite endpoint-seed coupled-core row.  This
turns the outer low block into one explicit four-vector; no interval or
analytic estimate enters the identity. -/
theorem fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_P0246_eq
    (c0 c2 c4 c6 : ℝ) :
    fourCellEvenZeroCoshCoupledCorePolarization
        fourCellEvenEndpointCoshSeed
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) =
      fourCellEvenEndpointSeedP0246CoreRow c0 c2 c4 c6 := by
  rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
  unfold fourCellEvenZeroCoshCoupledCorePolarization
  rw [endpointSeedProfile_add_intrinsicEvenP0246,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246Profile_eq_gram,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246Profile_eq_gram,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246Profile_eq_gram]
  unfold fourCellEvenEndpointSeedP0246CoreRow
    factorTwoP6EvenRawLogGram factorTwoP6EvenPotentialGram
  ring

/-- Against a genuine `P8+` tail, the endpoint seed has no raw-log mixed
entry.  Its complete coupled-core polarization is exactly the retained
endpoint-potential/prime capacity polarization. -/
theorem
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_tail_eq_capacity
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenZeroCoshCoupledCorePolarization
        fourCellEvenEndpointCoshSeed r =
      fourCellEvenEndpointCapacityPolarization
        fourCellEvenEndpointCoshSeed r := by
  rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
  unfold fourCellEvenZeroCoshCoupledCorePolarization
  rw [fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246_add_tail
    (2 / 3) (-2 / 3) 0 0 r hr hlocal hlow]
  ring

/-- Orthogonality removes the scalar-mass part of the signed endpoint-seed
row on a `P8+` tail.  Only the smooth regular-kernel row survives. -/
theorem fourCellEvenSignedMassRegularPolarization_endpointSeed_tail_eq_regular
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenSignedMassRegularPolarization
        fourCellEvenEndpointCoshSeed r =
      2 * fourCellOperatorHalfWidth *
        (∫ t : ℝ in 0..2,
          yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
            factorTwoCenteredCorrelationBilinear
              fourCellEvenEndpointCoshSeed r t) := by
  rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
  have hmass := intervalIntegral_intrinsicEvenP0246_mul_tail_eq_zero
    (2 / 3) (-2 / 3) 0 0 r hr hlow
  unfold fourCellEvenSignedMassRegularPolarization
  rw [hmass]
  ring

/-- Exact projected-representer identity for the complete endpoint-seed tail
row.  The arbitrary selector has degree below eight, so the tail annihilates
it; the remaining smooth correlation is converted by Fubini to its symmetric
one-variable lag representer. -/
theorem fourCellEvenEndpointSeedTailRow_eq_projectedRepresenterPairing
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlow : centeredLegendreMomentsVanishBelow r 8)
    (q : ℝ[X]) (hq : q.natDegree < 8) :
    fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed r t) =
      ∫ x : ℝ in -1..1,
        fourCellEvenEndpointSeedProjectedTailRowRepresenter q x * r x := by
  let k : ℝ → ℝ := fun t ↦
    yoshidaRegularKernel (fourCellOperatorHalfWidth * t)
  have hk : Measurable k := by
    dsimp only [k]
    exact measurable_yoshidaRegularKernel.comp
      (measurable_const.mul measurable_id)
  have hkbound : ∀ t ∈ Icc (0 : ℝ) 2, |k t| ≤ 1 / 4 := by
    intro t ht
    simpa only [k] using fourCellRegularLag_abs_le_quarter t ht
  have hcap :
      fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r =
        ∫ x : ℝ in -1..1,
          fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
            (2 / 3) (-2 / 3) 0 0 q x * r x := by
    rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
    exact
      fourCellEvenEndpointCapacityPolarization_P0246_eq_projectedRepresenterPairing
        (2 / 3) (-2 / 3) 0 0 r hr hlow q hq
  have hregular := integral_boundedLag_mul_correlationBilinear_eq_K
    k fourCellEvenEndpointCoshSeed r hk
      fourCellEvenEndpointCoshSeed_continuous hr (1 / 4) hkbound
  have hcapBase :=
    intervalIntegrable_fourCellEvenP0246CutoffEightCapacityRepresenter_mul
      (2 / 3) (-2 / 3) 0 0 r hr
  have hpoly : IntervalIntegrable
      (fun x : ℝ ↦ centeredPolynomialLift q x * r x) volume (-1) 1 :=
    ((by
      unfold centeredPolynomialLift
      fun_prop : Continuous (centeredPolynomialLift q)).mul hr).intervalIntegrable
        (-1) 1
  have hcapInt : IntervalIntegrable
      (fun x : ℝ ↦
        fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
          (2 / 3) (-2 / 3) 0 0 q x * r x) volume (-1) 1 := by
    apply (hcapBase.sub hpoly).congr
    intro x _hx
    unfold fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
    ring
  have hright :=
    intervalIntegrable_mul_factorTwoContinuousLagRightRepresenter_of_bounded
      k fourCellEvenEndpointCoshSeed r hk
        fourCellEvenEndpointCoshSeed_continuous hr (1 / 4) hkbound
  have hleft :=
    intervalIntegrable_mul_factorTwoContinuousLagLeftRepresenter_of_bounded
      k r fourCellEvenEndpointCoshSeed hk hr
        fourCellEvenEndpointCoshSeed_continuous (1 / 4) hkbound
  have hK : IntervalIntegrable
      (fun x : ℝ ↦ r x *
        factorTwoContinuousLagK k fourCellEvenEndpointCoshSeed x)
      volume (-1) 1 := by
    apply (hright.add hleft).congr
    intro x _hx
    unfold factorTwoContinuousLagK
    ring
  rw [hcap, hregular]
  rw [show (fun x : ℝ ↦
      fourCellEvenEndpointSeedProjectedTailRowRepresenter q x * r x) =
      fun x ↦
        fourCellEvenP0246CutoffEightProjectedCapacityRepresenter
            (2 / 3) (-2 / 3) 0 0 q x * r x -
          fourCellOperatorHalfWidth *
            (r x * factorTwoContinuousLagK
              k fourCellEvenEndpointCoshSeed x) by
    funext x
    unfold fourCellEvenEndpointSeedProjectedTailRowRepresenter
      fourCellEvenEndpointSeedRegularTailRepresenter
    dsimp only [k]
    ring,
    intervalIntegral.integral_sub hcapInt
      (hK.const_mul fourCellOperatorHalfWidth),
    intervalIntegral.integral_const_mul]
  ring

/-- Cauchy handoff for the complete projected endpoint-seed tail row.  Unlike
the capacity-only estimate, the dual density already contains the opposing
smooth regular row. -/
theorem fourCellEvenEndpointSeedTailRow_sq_le_mass_of_projectedRepresenterNorm
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlow : centeredLegendreMomentsVanishBelow r 8)
    (q : ℝ[X]) (hq : q.natDegree < 8)
    (hG : MemLp
      (fourCellEvenEndpointSeedProjectedTailRowRepresenter q) 2
      (volume.restrict (Ioc (-1 : ℝ) 1)))
    (C : ℝ)
    (hdual :
      (∫ x : ℝ in -1..1,
        fourCellEvenEndpointSeedProjectedTailRowRepresenter q x ^ 2) ≤ C) :
    (fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed r t)) ^ 2 ≤
      C * (∫ x : ℝ in -1..1, r x ^ 2) := by
  let μ : Measure ℝ := volume.restrict (Ioc (-1 : ℝ) 1)
  let G : ℝ → ℝ := fourCellEvenEndpointSeedProjectedTailRowRepresenter q
  have hrMeas : AEStronglyMeasurable r μ :=
    hr.aestronglyMeasurable.restrict
  have hrLp : MemLp r 2 μ := by
    rw [memLp_two_iff_integrable_sq_norm hrMeas]
    have hcompact : IntegrableOn (fun x : ℝ ↦ ‖r x‖ ^ 2)
        (Icc (-1 : ℝ) 1) :=
      (hr.norm.pow 2).continuousOn.integrableOn_compact isCompact_Icc
    exact hcompact.mono_set Ioc_subset_Icc_self
  have hcauchy :=
    YoshidaEndpointWeightedCauchy.sq_integral_mul_le_weighted
      μ (fun _ : ℝ ↦ 1) G r (by simp)
        (by simpa only [G, div_one, Real.sqrt_one] using hG)
        (by simpa only [Real.sqrt_one, one_mul] using hrLp)
  have hcauchy' :
      (∫ x : ℝ in -1..1, G x * r x) ^ 2 ≤
        (∫ x : ℝ in -1..1, G x ^ 2) *
          (∫ x : ℝ in -1..1, r x ^ 2) := by
    repeat rw [intervalIntegral.integral_of_le (by norm_num)]
    simpa only [μ, div_one, one_mul] using hcauchy
  have hR : 0 ≤ ∫ x : ℝ in -1..1, r x ^ 2 :=
    intervalIntegral.integral_nonneg (by norm_num) (fun _ _ ↦ sq_nonneg _)
  have hscaled := mul_le_mul_of_nonneg_right hdual hR
  rw [fourCellEvenEndpointSeedTailRow_eq_projectedRepresenterPairing
    r hr hlow q hq]
  change (∫ x : ℝ in -1..1, G x * r x) ^ 2 ≤ _
  exact hcauchy'.trans hscaled

/-- The single combined-representer norm which closes the endpoint-seed
Schur determinant on a genuine `P8+` tail.  The tail diagonal uses the exact
`553 / 20000` reserve left by the coupled-core estimate. -/
theorem fourCellEvenEndpointSeedRow_tail_sq_le_seed_mul_polarFree_of_norm
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (heven : Function.Even r)
    (hzero : fourCellPositiveCoshMoment r
      (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8)
    (hcore : (33 / 20 : ℝ) * (∫ x : ℝ in -1..1, r x ^ 2) ≤
      fourCellEvenZeroCoshCoupledCore r)
    (q : ℝ[X]) (hq : q.natDegree < 8)
    (hdual :
      (∫ x : ℝ in -1..1,
          fourCellEvenEndpointSeedProjectedTailRowRepresenter q x ^ 2) ≤
        fourCellEvenExactBracket fourCellEvenEndpointCoshSeed *
          (553 / 20000 : ℝ)) :
    fourCellEvenEndpointSeedRow r ^ 2 ≤
      fourCellEvenExactBracket fourCellEvenEndpointCoshSeed *
        fourCellEvenPolarFreeOperator r := by
  have hrow :=
    fourCellEvenEndpointSeedTailRow_sq_le_mass_of_projectedRepresenterNorm
      r hr hlow q hq
        (memLp_fourCellEvenEndpointSeedProjectedTailRowRepresenter q)
        (fourCellEvenExactBracket fourCellEvenEndpointCoshSeed *
          (553 / 20000 : ℝ)) hdual
  have hreserve :=
    fiveHundredFiftyThree_div_twentyThousand_mass_le_polarFree_of_coupledCore
      r hr hlocal heven hzero hcore
  have hseed : 0 ≤ fourCellEvenExactBracket fourCellEvenEndpointCoshSeed :=
    fourCellEvenExactBracket_endpointCoshSeed_pos.le
  have hscaled := mul_le_mul_of_nonneg_left hreserve hseed
  rw [fourCellEvenEndpointSeedRow_eq_core_sub_signed
      r hr hlocal heven hzero,
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_tail_eq_capacity
      r hr hlocal hlow,
    fourCellEvenSignedMassRegularPolarization_endpointSeed_tail_eq_regular
      r hr hlow]
  calc
    (fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed r t)) ^ 2 ≤
        (fourCellEvenExactBracket fourCellEvenEndpointCoshSeed *
          (553 / 20000 : ℝ)) *
            (∫ x : ℝ in -1..1, r x ^ 2) := hrow
    _ = fourCellEvenExactBracket fourCellEvenEndpointCoshSeed *
          ((553 / 20000 : ℝ) *
            (∫ x : ℝ in -1..1, r x ^ 2)) := by ring
    _ ≤ fourCellEvenExactBracket fourCellEvenEndpointCoshSeed *
          fourCellEvenPolarFreeOperator r := hscaled

/-- Exact mixed-row decomposition for the complete cutoff-eight split.  The
seed-to-low term is finite-dimensional, while the seed-to-tail term is the
single retained endpoint-capacity row. -/
theorem
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_P0246_add_tail
    (c0 c2 c4 c6 : ℝ) (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenZeroCoshCoupledCorePolarization
        fourCellEvenEndpointCoshSeed
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) =
      fourCellEvenZeroCoshCoupledCorePolarization
          fourCellEvenEndpointCoshSeed
          (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r := by
  let s : ℝ → ℝ :=
    factorTwoIntrinsicEvenP0246Profile (2 / 3) (-2 / 3) 0 0
  let p : ℝ → ℝ :=
    factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  let q : ℝ → ℝ :=
    factorTwoIntrinsicEvenP0246Profile
      (2 / 3 + c0) (-2 / 3 + c2) c4 c6
  have hs : Continuous s := by
    simpa only [s] using
      continuous_factorTwoIntrinsicEvenP0246Profile
        (2 / 3) (-2 / 3) 0 0
  have hp : Continuous p := by
    simpa only [p] using
      continuous_factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  have hsp : s + p = q := by
    simpa only [s, p, q] using
      endpointSeedProfile_add_intrinsicEvenP0246 c0 c2 c4 c6
  have hsall : s + (p + r) = q + r := by
    rw [← hsp]
    exact (add_assoc s p r).symm
  have hcapacity :
      fourCellEvenEndpointCapacityPolarization q r =
        fourCellEvenEndpointCapacityPolarization s r +
          fourCellEvenEndpointCapacityPolarization p r := by
    rw [← hsp,
      fourCellEvenEndpointCapacityPolarization_comm (s + p) r,
      fourCellEvenEndpointCapacityPolarization_add_right r s p hr hs hp,
      fourCellEvenEndpointCapacityPolarization_comm r s,
      fourCellEvenEndpointCapacityPolarization_comm r p]
  rw [fourCellEvenEndpointCoshSeed_eq_intrinsicEvenP0246Profile]
  change fourCellEvenZeroCoshCoupledCorePolarization s (p + r) =
    fourCellEvenZeroCoshCoupledCorePolarization s p +
      fourCellEvenEndpointCapacityPolarization s r
  unfold fourCellEvenZeroCoshCoupledCorePolarization
  rw [hsall,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246_add_tail
      (2 / 3 + c0) (-2 / 3 + c2) c4 c6 r hr hlocal hlow,
    fourCellEvenZeroCoshCoupledCore_intrinsicEvenP0246_add_tail
      c0 c2 c4 c6 r hr hlocal hlow,
    hsp, hcapacity]
  ring

/-- Exact fixed-row normal form on the cutoff-eight tail.  The singular
coupled core has collapsed to the one capacity row, while the signed
mass/regular row remains coupled rather than being bounded separately. -/
theorem fourCellEvenEndpointSeedRow_tail_eq_capacity_sub_signed
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (heven : Function.Even r)
    (hzero : fourCellPositiveCoshMoment r
      (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow r =
      fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        fourCellEvenSignedMassRegularPolarization
          fourCellEvenEndpointCoshSeed r := by
  rw [fourCellEvenEndpointSeedRow_eq_core_sub_signed r hr hlocal heven hzero,
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_tail_eq_capacity
      r hr hlocal hlow]

/-- On the cutoff-eight tail the complete fixed row contains exactly two
opposing terms: the endpoint-capacity row and the smooth regular-kernel row.
Both singular raw energy and scalar mass vanish by Legendre orthogonality. -/
theorem fourCellEvenEndpointSeedRow_tail_eq_capacity_sub_regular
    (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (heven : Function.Even r)
    (hzero : fourCellPositiveCoshMoment r
      (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow r =
      fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed r t) := by
  rw [fourCellEvenEndpointSeedRow_tail_eq_capacity_sub_signed
      r hr hlocal heven hzero hlow,
    fourCellEvenSignedMassRegularPolarization_endpointSeed_tail_eq_regular
      r hr hlow]

/-- Full fixed-row normal form after the canonical cutoff-eight split.  This
is the exact outer determinant row: one finite `P0246` core entry, one
endpoint-capacity tail entry, and the still-coupled signed mass/regular row. -/
theorem fourCellEvenEndpointSeedRow_P0246_add_tail_eq
    (c0 c2 c4 c6 : ℝ) (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hre : Function.Even r)
    (hzero : fourCellPositiveCoshMoment
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r)
        (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) =
      fourCellEvenZeroCoshCoupledCorePolarization
          fourCellEvenEndpointCoshSeed
          (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        fourCellEvenSignedMassRegularPolarization
          fourCellEvenEndpointCoshSeed
          (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) := by
  let p : ℝ → ℝ :=
    factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  have hp : Continuous p := by
    simpa only [p] using
      continuous_factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  have hpPoly : p = fun x : ℝ ↦
      c0 + c2 * ((3 * x ^ 2 - 1) / 2) +
        c4 * ((35 * x ^ 4 - 30 * x ^ 2 + 3) / 8) +
          c6 * ((231 * x ^ 6 - 315 * x ^ 4 + 105 * x ^ 2 - 5) / 16) := by
    funext x
    dsimp only [p]
    unfold factorTwoIntrinsicEvenP0246Profile
      factorTwoIntrinsicEvenP024Profile
      factorTwoEvenStructuralLowProfile
      factorTwoIntrinsicSixEvenTail centeredEvenP0 centeredEvenP2
      factorTwoCenteredP4
    simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
    rw [factorTwoCenteredP6_eq]
    ring
  have hpDiff : ContDiff ℝ 1 p := by
    rw [hpPoly]
    fun_prop
  have hpLocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) p :=
    hpDiff.contDiffOn.locallyLipschitzOn (convex_Icc (-1 : ℝ) 1)
  have hpe : Function.Even p := by
    simpa only [p] using
      even_factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  have hrow := fourCellEvenEndpointSeedRow_eq_core_sub_signed
    (p + r) (hp.add hr) (hpLocal.add hlocal) (hpe.add hre)
      (by simpa only [p] using hzero)
  rw [fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_P0246_add_tail
    c0 c2 c4 c6 r hr hlocal hlow] at hrow
  simpa only [p] using hrow

/-- Coordinate form of the complete fixed endpoint-seed row.  The entire
finite contribution is the explicit four-vector above. -/
theorem fourCellEvenEndpointSeedRow_P0246_add_tail_eq_explicit
    (c0 c2 c4 c6 : ℝ) (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hre : Function.Even r)
    (hzero : fourCellPositiveCoshMoment
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r)
        (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) =
      fourCellEvenEndpointSeedP0246CoreRow c0 c2 c4 c6 +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        fourCellEvenSignedMassRegularPolarization
          fourCellEvenEndpointCoshSeed
          (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) := by
  rw [fourCellEvenEndpointSeedRow_P0246_add_tail_eq
    c0 c2 c4 c6 r hr hlocal hre hzero hlow,
    fourCellEvenZeroCoshCoupledCorePolarization_endpointSeed_P0246_eq]

/-- Fully separated outer row for the cutoff-eight split.  The first summand
is a fixed four-dimensional row.  The tail contributes only its endpoint
capacity row minus the smooth regular-kernel row; no scalar mass or raw-log
cross term remains. -/
theorem fourCellEvenEndpointSeedRow_P0246_add_tail_eq_low_add_tail
    (c0 c2 c4 c6 : ℝ) (r : ℝ → ℝ) (hr : Continuous r)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r)
    (hre : Function.Even r)
    (hzero : fourCellPositiveCoshMoment
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r)
        (fourCellOperatorHalfWidth / 2) = 0)
    (hlow : centeredLegendreMomentsVanishBelow r 8) :
    fourCellEvenEndpointSeedRow
        (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6 + r) =
      fourCellEvenEndpointSeedP0246CompleteLowRow c0 c2 c4 c6 +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed r -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed r t) := by
  have hp : Continuous
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) :=
    continuous_factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  rw [fourCellEvenEndpointSeedRow_P0246_add_tail_eq_explicit
      c0 c2 c4 c6 r hr hlocal hre hzero hlow,
    fourCellEvenSignedMassRegularPolarization_add_right
      fourCellEvenEndpointCoshSeed
      (factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6) r
      fourCellEvenEndpointCoshSeed_continuous hp hr,
    fourCellEvenSignedMassRegularPolarization_endpointSeed_tail_eq_regular
      r hr hlow]
  unfold fourCellEvenEndpointSeedP0246CompleteLowRow
  ring

/-- Canonical cutoff-eight normal form of the endpoint-seed row for an
arbitrary even zero-cosh profile. -/
theorem fourCellEvenEndpointSeedRow_eq_canonicalCutoffEightLow_add_tail
    (w : ℝ → ℝ) (hw : Continuous w)
    (hlocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) w)
    (heven : Function.Even w)
    (hzero : fourCellPositiveCoshMoment w
      (fourCellOperatorHalfWidth / 2) = 0) :
    fourCellEvenEndpointSeedRow w =
      fourCellEvenEndpointSeedP0246CompleteLowRow
          (factorTwoCanonicalLegendreCoefficient w hw 0)
          (factorTwoCanonicalLegendreCoefficient w hw 2)
          (factorTwoCanonicalLegendreCoefficient w hw 4)
          (factorTwoCanonicalLegendreCoefficient w hw 6) +
        fourCellEvenEndpointCapacityPolarization
          fourCellEvenEndpointCoshSeed
          (centeredLegendreHigherResidual w hw 8) -
        2 * fourCellOperatorHalfWidth *
          (∫ t : ℝ in 0..2,
            yoshidaRegularKernel (fourCellOperatorHalfWidth * t) *
              factorTwoCenteredCorrelationBilinear
                fourCellEvenEndpointCoshSeed
                (centeredLegendreHigherResidual w hw 8) t) := by
  let c0 : ℝ := factorTwoCanonicalLegendreCoefficient w hw 0
  let c2 : ℝ := factorTwoCanonicalLegendreCoefficient w hw 2
  let c4 : ℝ := factorTwoCanonicalLegendreCoefficient w hw 4
  let c6 : ℝ := factorTwoCanonicalLegendreCoefficient w hw 6
  let p : ℝ → ℝ := factorTwoIntrinsicEvenP0246Profile c0 c2 c4 c6
  let r : ℝ → ℝ := centeredLegendreHigherResidual w hw 8
  have hpEq : centeredLegendreLowProjection w hw 8 = p := by
    simpa only [c0, c2, c4, c6, p] using
      centeredLegendreLowProjection_eight_eq_intrinsicEvenP0246Profile
        w hw heven
  have hsum : p + r = w := by
    rw [← hpEq]
    simpa only [r] using
      centeredLegendreLowProjection_add_higherResidual w hw 8
  have hr : Continuous r := by
    simpa only [r] using continuous_centeredLegendreHigherResidual w hw 8
  have hrLocal : LocallyLipschitzOn (Icc (-1 : ℝ) 1) r := by
    simpa only [r] using
      locallyLipschitzOn_centeredLegendreHigherResidual w hw hlocal 8
  have hrEven : Function.Even r := by
    simpa only [r] using
      centeredLegendreHigherResidual_even w hw heven 8
  have hrGap : centeredLegendreMomentsVanishBelow r 8 := by
    simpa only [r] using
      centeredLegendreHigherResidual_momentsVanishBelow w hw 8
  have hzeroSplit : fourCellPositiveCoshMoment (p + r)
      (fourCellOperatorHalfWidth / 2) = 0 := by
    rw [hsum]
    exact hzero
  have hrow :=
    fourCellEvenEndpointSeedRow_P0246_add_tail_eq_low_add_tail
      c0 c2 c4 c6 r hr hrLocal hrEven hzeroSplit hrGap
  rw [hsum] at hrow
  simpa only [c0, c2, c4, c6, r] using hrow

end

end ArithmeticHodge.Analysis.YoshidaFourCellEvenEndpointSeedCutoffEightBridgeStructural
