import ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024Structural
import ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedSelectorHomogeneityStructural

set_option autoImplicit false

open MeasureTheory Polynomial Real Set

namespace ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorStructural

open ThreeByThreeRankOneSchur
open ShiftedLegendreLogEnergyOrthogonalProjection
open ShiftedLegendreOrthogonality
open YoshidaFactorTwoPhaseIntrinsicElevenConcreteSelectorsStructural
open YoshidaFactorTwoPhaseIntrinsicElevenConstrainedWeightedDualStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedConstrainedWeightedDualStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024Structural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedRepresentersStructural
open YoshidaFactorTwoPhaseIntrinsicElevenRetainedSelectorHomogeneityStructural
open YoshidaFactorTwoPhaseIntrinsicFourP45MixedExpansion
open YoshidaFactorTwoPhaseIntrinsicSixP4EndpointProfile
open YoshidaFactorTwoPhaseIntrinsicSixP4Schur
open YoshidaFactorTwoPhaseFullProfile
open YoshidaFactorTwoPhaseLowSchur
open YoshidaFactorTwoPhaseSingularWeightedCauchyStructural

noncomputable section

/-!
# The sharp retained selector target on the `P₀/P₂/P₄` core

The saturated singular Schur split charges `1 / 8192` of the full singular
energy to the low block.  This file records the resulting exact symmetric
quadratic and connects finite selector Gram pivots directly to the production
retained-selector obligation.
-/

/-- The `(0,0)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow00 (a : ℝ) : ℝ :=
  factorTwoStructuralPhaseLow00 a - (1 / 4096 : ℝ) * (2 - a)

/-- The `(0,2)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow02 (a : ℝ) : ℝ :=
  factorTwoStructuralPhaseLow02 a - (1 / 4096 : ℝ) * ((2 - a) / 6)

/-- The `(0,4)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow04 (a : ℝ) : ℝ :=
  factorTwoIntrinsicFourP45Cross04 a - (1 / 4096 : ℝ) * ((2 - a) / 20)

/-- The `(2,2)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow22 (a : ℝ) : ℝ :=
  factorTwoStructuralPhaseLow22 a -
    (1 / 4096 : ℝ) * ((172 - 11 * a) / 150)

/-- The `(2,4)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow24 (a : ℝ) : ℝ :=
  factorTwoIntrinsicFourP45Cross24 a -
    (1 / 4096 : ℝ) * ((15 - 4 * a) / 105)

/-- The `(4,4)` entry of the sharp-retuned `P₀/P₂/P₄` low complement. -/
def retainedP024SharpLow44 (a : ℝ) : ℝ :=
  factorTwoIntrinsicP4PhaseDiagonal a -
    (1 / 4096 : ℝ) * ((8728 - 269 * a) / 11340)

/-- Exact low budget left by the saturated retained singular Schur split.
The alternating coordinate does not enter because the production low profile
is even and its odd low polynomial is zero. -/
theorem retainedP024SharpLowComplement_eq_symmetricQuadratic
    (c0 c2 c4 a b : ℝ) :
    factorTwoEndpointChannelPhase
          (factorTwoIntrinsicEvenP024Profile c0 c2 c4)
          (0 : ℝ → ℝ) a b -
        (1 / 8192 : ℝ) * factorTwoPhaseSingularWeightedEnergy
          (factorTwoIntrinsicEvenP024Profile c0 c2 c4)
          (0 : ℝ → ℝ) a b =
      symmetricQuadratic
        (retainedP024SharpLow00 a)
        (retainedP024SharpLow02 a)
        (retainedP024SharpLow04 a)
        (retainedP024SharpLow22 a)
        (retainedP024SharpLow24 a)
        (retainedP024SharpLow44 a)
        c0 c2 c4 := by
  have hscale :
      (1 / 8192 : ℝ) * factorTwoPhaseSingularWeightedEnergy
          (factorTwoIntrinsicEvenP024Profile c0 c2 c4)
          (0 : ℝ → ℝ) a b =
        (1 / 4096 : ℝ) * ((1 / 2 : ℝ) *
          factorTwoPhaseSingularWeightedEnergy
            (factorTwoIntrinsicEvenP024Profile c0 c2 c4)
            (0 : ℝ → ℝ) a b) := by
    ring
  rw [factorTwoEndpointChannelPhase_intrinsicEvenP024_eq_quadratic_disk,
    hscale, half_singularWeightedEnergy_intrinsicEvenP024]
  unfold retainedP024SharpLow00 retainedP024SharpLow02
    retainedP024SharpLow04 retainedP024SharpLow22 retainedP024SharpLow24
    retainedP024SharpLow44 symmetricQuadratic
  ring

/-! ## Production selector rows and their finite Gram -/

/-- Retained even production row generated by the shifted Legendre mode `n`
at the sharp pole-removal coefficient. -/
def retainedP024EvenRow (n : ℕ) (a b : ℝ) : ℝ → ℝ :=
  factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
    (1 / 512 : ℝ) (shiftedLegendreReal n) 0 a b

/-- Retained odd production row generated by the shifted Legendre mode `n`
at the sharp pole-removal coefficient. -/
def retainedP024OddRow (n : ℕ) (a b : ℝ) : ℝ → ℝ :=
  factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
    (1 / 512 : ℝ) (shiftedLegendreReal n) 0 a b

/-- One polarized entry of the exact two-channel selector Gram. -/
def retainedP024SelectorGramEntry
    (i j : ℕ) (a b : ℝ)
    (qEi qEj qOi qOj : ℝ[X]) : ℝ :=
  factorTwoIntrinsicElevenRetainedSelectorCrossDual
    (retainedP024EvenRow i a b) (retainedP024EvenRow j a b)
    (retainedP024OddRow i a b) (retainedP024OddRow j a b)
    qEi qEj qOi qOj

/-- Strict pivots of the exact `3 x 3` selector gap produce the two
degree-below-eleven selectors required by the sharp retained Schur handoff.
All analytic integrability obligations and all identifications with the
production `P₀/P₂/P₄` polynomial are discharged here; only the six finite
Gram entries and their three positivity pivots remain as hypotheses. -/
theorem exists_sharpRetunedP024Selector_of_strict_gap_pivots
    (a b : ℝ)
    (qE0 qE2 qE4 qO0 qO2 qO4 : ℝ[X])
    (hqE0 : qE0.natDegree < 11) (hqE2 : qE2.natDegree < 11)
    (hqE4 : qE4.natDegree < 11) (hqO0 : qO0.natDegree < 11)
    (hqO2 : qO2.natDegree < 11) (hqO4 : qO4.natDegree < 11)
    (h00 : 0 < retainedP024SharpLow00 a -
      retainedP024SelectorGramEntry 0 0 a b qE0 qE0 qO0 qO0)
    (hminor : 0 < leadingMinorTwo
      (retainedP024SharpLow00 a -
        retainedP024SelectorGramEntry 0 0 a b qE0 qE0 qO0 qO0)
      (retainedP024SharpLow02 a -
        retainedP024SelectorGramEntry 0 2 a b qE0 qE2 qO0 qO2)
      (retainedP024SharpLow22 a -
        retainedP024SelectorGramEntry 2 2 a b qE2 qE2 qO2 qO2))
    (hdet : 0 < symmetricDeterminant
      (retainedP024SharpLow00 a -
        retainedP024SelectorGramEntry 0 0 a b qE0 qE0 qO0 qO0)
      (retainedP024SharpLow02 a -
        retainedP024SelectorGramEntry 0 2 a b qE0 qE2 qO0 qO2)
      (retainedP024SharpLow04 a -
        retainedP024SelectorGramEntry 0 4 a b qE0 qE4 qO0 qO4)
      (retainedP024SharpLow22 a -
        retainedP024SelectorGramEntry 2 2 a b qE2 qE2 qO2 qO2)
      (retainedP024SharpLow24 a -
        retainedP024SelectorGramEntry 2 4 a b qE2 qE4 qO2 qO4)
      (retainedP024SharpLow44 a -
        retainedP024SelectorGramEntry 4 4 a b qE4 qE4 qO4 qO4))
    (c0 c2 c4 : ℝ) :
    ∃ qE qO : ℝ[X],
      qE.natDegree < 11 ∧ qO.natDegree < 11 ∧
      factorTwoIntrinsicElevenRetainedConstrainedSelectorDual
          (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
          (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
            (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
          qE qO ≤
        factorTwoEndpointChannelPhase
            (centeredPolynomialLift (retainedP024Polynomial c0 c2 c4))
            (centeredPolynomialLift 0) a b -
          (1 / 8192 : ℝ) * factorTwoPhaseSingularWeightedEnergy
            (centeredPolynomialLift (retainedP024Polynomial c0 c2 c4))
            (centeredPolynomialLift 0) a b := by
  have hEven := retainedEvenThreeSelectorGramIntegrable
    (1 / 512 : ℝ)
    (shiftedLegendreReal 0) (shiftedLegendreReal 2) (shiftedLegendreReal 4)
    qE0 qE2 qE4 a b
  have hOdd := retainedOddThreeSelectorGramIntegrable
    (1 / 512 : ℝ)
    (shiftedLegendreReal 0) (shiftedLegendreReal 2) (shiftedLegendreReal 4)
    qO0 qO2 qO4 a b
  obtain ⟨qE, qO, hqE, hqO, hselector⟩ :=
    exists_threeSelector_of_strict_gap_pivots
      (retainedP024EvenRow 0 a b)
      (retainedP024EvenRow 2 a b)
      (retainedP024EvenRow 4 a b)
      (retainedP024OddRow 0 a b)
      (retainedP024OddRow 2 a b)
      (retainedP024OddRow 4 a b)
      qE0 qE2 qE4 qO0 qO2 qO4
      hqE0 hqE2 hqE4 hqO0 hqO2 hqO4
      (by simpa only [retainedP024EvenRow] using hEven)
      (by simpa only [retainedP024OddRow] using hOdd)
      (retainedP024SharpLow00 a)
      (retainedP024SharpLow02 a)
      (retainedP024SharpLow04 a)
      (retainedP024SharpLow22 a)
      (retainedP024SharpLow24 a)
      (retainedP024SharpLow44 a)
      (by simpa only [retainedP024SelectorGramEntry] using h00)
      (by simpa only [retainedP024SelectorGramEntry] using hminor)
      (by simpa only [retainedP024SelectorGramEntry] using hdet)
      c0 c2 c4
  refine ⟨qE, qO, hqE, hqO, ?_⟩
  have hcongr :=
    factorTwoIntrinsicElevenRetainedConstrainedSelectorDual_congr_on_Icc
      (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
        (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
      (threeSelectorRepresenter c0 c2 c4
        (retainedP024EvenRow 0 a b)
        (retainedP024EvenRow 2 a b)
        (retainedP024EvenRow 4 a b))
      (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
        (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
      (threeSelectorRepresenter c0 c2 c4
        (retainedP024OddRow 0 a b)
        (retainedP024OddRow 2 a b)
        (retainedP024OddRow 4 a b))
      qE qO
      (fun x hx ↦ by
        rw [retainedP024Polynomial_eq_threeSelectorPolynomial]
        simpa only [retainedP024EvenRow] using
          retainedEvenMixedRepresenterAt_threeSelectorPolynomial_on_Icc
            (1 / 512 : ℝ) c0 c2 c4 a b
            (shiftedLegendreReal 0) (shiftedLegendreReal 2)
            (shiftedLegendreReal 4) x hx)
      (fun x hx ↦ by
        rw [retainedP024Polynomial_eq_threeSelectorPolynomial]
        simpa only [retainedP024OddRow] using
          retainedOddMixedRepresenterAt_threeSelectorPolynomial_on_Icc
            (1 / 512 : ℝ) c0 c2 c4 a b
            (shiftedLegendreReal 0) (shiftedLegendreReal 2)
            (shiftedLegendreReal 4) x hx)
  have hzero : centeredPolynomialLift (0 : ℝ[X]) = (0 : ℝ → ℝ) := by
    funext x
    unfold centeredPolynomialLift
    simp
  rw [hcongr, centeredPolynomialLift_retainedP024Polynomial,
    hzero,
    retainedP024SharpLowComplement_eq_symmetricQuadratic]
  exact hselector

/-! ## A phase chord for selector costs -/

/-- Positive-endpoint barycentric coordinate for the symmetric phase. -/
def retainedP024ChordPlus (a : ℝ) : ℝ := (1 + a) / 2

/-- Negative-endpoint barycentric coordinate for the symmetric phase. -/
def retainedP024ChordMinus (a : ℝ) : ℝ := (1 - a) / 2

/-- Affine interpolation of two endpoint even selectors. -/
def retainedP024EvenChordSelector
    (a : ℝ) (qPlus qMinus : ℝ[X]) : ℝ[X] :=
  retainedP024ChordPlus a • qPlus + retainedP024ChordMinus a • qMinus

/-- Half-difference selector paired with the symmetric phase row. -/
def retainedP024SymmetricSelector
    (qPlus qMinus : ℝ[X]) : ℝ[X] :=
  (1 / 2 : ℝ) • (qPlus - qMinus)

/-- Alternating selector scaled by the alternating disk coordinate. -/
def retainedP024OddChordSelector (b : ℝ) (qAlt : ℝ[X]) : ℝ[X] :=
  b • qAlt

private theorem retainedEvenRepresenterAt_eq_endpoint_chord
    (gamma : ℝ) (p : ℝ[X]) (a b x : ℝ) :
    factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
        gamma p 0 a b x =
      retainedP024ChordPlus a *
          factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            gamma p 0 1 0 x +
        retainedP024ChordMinus a *
          factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            gamma p 0 (-1) 0 x := by
  rw [retainedEvenRepresenterAt_zero_odd_phase_split,
    retainedEvenRepresenterAt_zero_odd_phase_split,
    retainedEvenRepresenterAt_zero_odd_phase_split]
  unfold retainedP024ChordPlus retainedP024ChordMinus
  ring

private theorem retainedEvenSymmetricRepresenterAt_eq_endpoint_half_sub
    (gamma : ℝ) (p : ℝ[X]) (x : ℝ) :
    retainedEvenSymmetricRepresenterAt gamma p x =
      (1 / 2 : ℝ) *
        (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            gamma p 0 1 0 x -
          factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            gamma p 0 (-1) 0 x) := by
  rw [retainedEvenRepresenterAt_zero_odd_phase_split,
    retainedEvenRepresenterAt_zero_odd_phase_split]
  ring

private theorem retainedEvenChordResidual_eq
    (gamma : ℝ) (p qPlus qMinus : ℝ[X]) (a b x : ℝ) :
    factorTwoIntrinsicElevenSelectorResidual
        (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
          gamma p 0 a b)
        (retainedP024EvenChordSelector a qPlus qMinus) x =
      retainedP024ChordPlus a *
          factorTwoIntrinsicElevenSelectorResidual
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 1 0) qPlus x +
        retainedP024ChordMinus a *
          factorTwoIntrinsicElevenSelectorResidual
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 (-1) 0) qMinus x := by
  unfold factorTwoIntrinsicElevenSelectorResidual
    retainedP024EvenChordSelector
  rw [retainedEvenRepresenterAt_eq_endpoint_chord,
    centeredPolynomialLift_add, centeredPolynomialLift_smul,
    centeredPolynomialLift_smul]
  ring

private theorem retainedEvenSymmetricResidual_eq_endpoint_half_sub
    (gamma : ℝ) (p qPlus qMinus : ℝ[X]) (x : ℝ) :
    factorTwoIntrinsicElevenSelectorResidual
        (retainedEvenSymmetricRepresenterAt gamma p)
        (retainedP024SymmetricSelector qPlus qMinus) x =
      (1 / 2 : ℝ) *
        (factorTwoIntrinsicElevenSelectorResidual
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 1 0) qPlus x -
          factorTwoIntrinsicElevenSelectorResidual
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 (-1) 0) qMinus x) := by
  unfold factorTwoIntrinsicElevenSelectorResidual
    retainedP024SymmetricSelector
  rw [retainedEvenSymmetricRepresenterAt_eq_endpoint_half_sub,
    centeredPolynomialLift_smul]
  have hsub : centeredPolynomialLift (qPlus - qMinus) x =
      centeredPolynomialLift qPlus x - centeredPolynomialLift qMinus x := by
    unfold centeredPolynomialLift
    rw [Polynomial.eval_sub]
  rw [hsub]
  ring

/-- Exact Hilbert-space chord identity for the retained even selector cost.
It is an algebraic polarization identity after the two endpoint residuals
have been placed in the same fixed weighted `L²` space. -/
theorem retainedEvenSelectorDual_eq_endpoint_chord
    (gamma : ℝ) (p qPlus qMinus : ℝ[X]) (a b : ℝ) :
    factorTwoIntrinsicElevenSelectorDual
        factorTwoIntrinsicElevenRetainedEvenWeight
        (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
          gamma p 0 a b)
        (retainedP024EvenChordSelector a qPlus qMinus) =
      retainedP024ChordPlus a *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 1 0) qPlus +
        retainedP024ChordMinus a *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 (-1) 0) qMinus -
        (1 - a ^ 2) *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (retainedEvenSymmetricRepresenterAt gamma p)
            (retainedP024SymmetricSelector qPlus qMinus) := by
  let FPlus := factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
    gamma p 0 1 0
  let FMinus := factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
    gamma p 0 (-1) 0
  let FS := retainedEvenSymmetricRepresenterAt gamma p
  let RPlus := factorTwoIntrinsicElevenSelectorResidual FPlus qPlus
  let RMinus := factorTwoIntrinsicElevenSelectorResidual FMinus qMinus
  let RS := factorTwoIntrinsicElevenSelectorResidual FS
    (retainedP024SymmetricSelector qPlus qMinus)
  let W := factorTwoIntrinsicElevenRetainedEvenWeight
  have hPlusLp :=
    factorTwoIntrinsicElevenRetainedEvenSelectorResidual_div_sqrt_memLp_two
      gamma p 0 qPlus 1 0
  have hMinusLp :=
    factorTwoIntrinsicElevenRetainedEvenSelectorResidual_div_sqrt_memLp_two
      gamma p 0 qMinus (-1) 0
  have hPlusInt : IntervalIntegrable (fun x ↦ RPlus x ^ 2 / W x)
      volume (-1) 1 := by
    simpa only [RPlus, W, FPlus, pow_two] using
      intervalIntegrable_selectorCross_of_memLp W FPlus FPlus qPlus qPlus
        (fun x hx ↦ factorTwoIntrinsicElevenRetainedEvenWeight_pos_on_Icc hx)
        hPlusLp hPlusLp
  have hMinusInt : IntervalIntegrable (fun x ↦ RMinus x ^ 2 / W x)
      volume (-1) 1 := by
    simpa only [RMinus, W, FMinus, pow_two] using
      intervalIntegrable_selectorCross_of_memLp W FMinus FMinus qMinus qMinus
        (fun x hx ↦ factorTwoIntrinsicElevenRetainedEvenWeight_pos_on_Icc hx)
        hMinusLp hMinusLp
  have hSLp : MemLp (fun x ↦ RS x / Real.sqrt (W x)) 2
      (volume.restrict (Ioc (-1 : ℝ) 1)) := by
    have hcomb := (hPlusLp.sub hMinusLp).const_mul (1 / 2 : ℝ)
    apply (memLp_congr_ae (μ := volume.restrict (Ioc (-1 : ℝ) 1)) ?_).mpr hcomb
    filter_upwards [] with x
    rw [show RS x = (1 / 2 : ℝ) * (RPlus x - RMinus x) by
      simpa only [RS, RPlus, RMinus, FS, FPlus, FMinus] using
        retainedEvenSymmetricResidual_eq_endpoint_half_sub
          gamma p qPlus qMinus x]
    dsimp only [Pi.sub_apply]
    ring
  have hSInt : IntervalIntegrable (fun x ↦ RS x ^ 2 / W x)
      volume (-1) 1 := by
    simpa only [RS, W, FS, pow_two] using
      intervalIntegrable_selectorCross_of_memLp W FS FS
        (retainedP024SymmetricSelector qPlus qMinus)
        (retainedP024SymmetricSelector qPlus qMinus)
        (fun x hx ↦ factorTwoIntrinsicElevenRetainedEvenWeight_pos_on_Icc hx)
        hSLp hSLp
  unfold factorTwoIntrinsicElevenSelectorDual
  rw [show (fun x : ℝ ↦
      factorTwoIntrinsicElevenSelectorResidual
          (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            gamma p 0 a b)
          (retainedP024EvenChordSelector a qPlus qMinus) x ^ 2 /
        factorTwoIntrinsicElevenRetainedEvenWeight x) =
      fun x ↦ retainedP024ChordPlus a * (RPlus x ^ 2 / W x) +
        retainedP024ChordMinus a * (RMinus x ^ 2 / W x) -
        (1 - a ^ 2) * (RS x ^ 2 / W x) by
    funext x
    rw [retainedEvenChordResidual_eq gamma p qPlus qMinus a b x,
      show RS x = (1 / 2 : ℝ) * (RPlus x - RMinus x) by
        simpa only [RS, RPlus, RMinus, FS, FPlus, FMinus] using
          retainedEvenSymmetricResidual_eq_endpoint_half_sub
            gamma p qPlus qMinus x]
    unfold retainedP024ChordPlus retainedP024ChordMinus
    dsimp only [RPlus, RMinus, W, FPlus, FMinus]
    ring]
  rw [intervalIntegral.integral_sub
      ((hPlusInt.const_mul _).add (hMinusInt.const_mul _))
      (hSInt.const_mul _),
    intervalIntegral.integral_add (hPlusInt.const_mul _)
      (hMinusInt.const_mul _)]
  repeat rw [intervalIntegral.integral_const_mul]

/-- The retained odd selector cost is exactly quadratic in the alternating
disk coordinate when the odd low polynomial vanishes. -/
theorem retainedOddSelectorDual_eq_scaled_alternating
    (gamma : ℝ) (p qAlt : ℝ[X]) (a b : ℝ) :
    factorTwoIntrinsicElevenSelectorDual
        factorTwoIntrinsicElevenRetainedOddWeight
        (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
          gamma p 0 a b)
        (retainedP024OddChordSelector b qAlt) =
      b ^ 2 * factorTwoIntrinsicElevenSelectorDual
        factorTwoIntrinsicElevenRetainedOddWeight
        (retainedOddAlternatingRepresenterAt gamma p) qAlt := by
  have hrow :
      factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
          gamma p 0 a b =
        fun x ↦ b * retainedOddAlternatingRepresenterAt gamma p x := by
    funext x
    exact retainedOddRepresenterAt_zero_odd_phase_split gamma p a b x
  rw [hrow]
  unfold retainedP024OddChordSelector
  exact factorTwoIntrinsicElevenSelectorDual_smul
    factorTwoIntrinsicElevenRetainedOddWeight
    (retainedOddAlternatingRepresenterAt gamma p) b qAlt

/-- Exact two-channel phase chord.  It reduces the full disk dependence of a
phase-affine selector to two endpoint even costs, one symmetric half-difference
cost, and one alternating cost. -/
theorem retainedConstrainedSelectorDual_eq_phase_chord
    (gamma : ℝ) (p qPlus qMinus qAlt : ℝ[X]) (a b : ℝ) :
    factorTwoIntrinsicElevenRetainedConstrainedSelectorDual
        (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
          gamma p 0 a b)
        (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
          gamma p 0 a b)
        (retainedP024EvenChordSelector a qPlus qMinus)
        (retainedP024OddChordSelector b qAlt) =
      retainedP024ChordPlus a *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 1 0) qPlus +
        retainedP024ChordMinus a *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 (-1) 0) qMinus -
        (1 - a ^ 2) *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (retainedEvenSymmetricRepresenterAt gamma p)
            (retainedP024SymmetricSelector qPlus qMinus) +
        b ^ 2 * factorTwoIntrinsicElevenSelectorDual
          factorTwoIntrinsicElevenRetainedOddWeight
          (retainedOddAlternatingRepresenterAt gamma p) qAlt := by
  unfold factorTwoIntrinsicElevenRetainedConstrainedSelectorDual
  rw [retainedEvenSelectorDual_eq_endpoint_chord,
    retainedOddSelectorDual_eq_scaled_alternating]

/-- On the closed phase disk the alternating selector cost is largest on the
boundary `b² = 1 - a²`.  This removes the second phase coordinate without a
phase subdivision. -/
theorem retainedConstrainedSelectorDual_le_boundary_chord
    (gamma : ℝ) (p qPlus qMinus qAlt : ℝ[X]) (a b : ℝ)
    (hab : a ^ 2 + b ^ 2 ≤ 1) :
    factorTwoIntrinsicElevenRetainedConstrainedSelectorDual
        (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
          gamma p 0 a b)
        (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
          gamma p 0 a b)
        (retainedP024EvenChordSelector a qPlus qMinus)
        (retainedP024OddChordSelector b qAlt) ≤
      retainedP024ChordPlus a *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 1 0) qPlus +
        retainedP024ChordMinus a *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
              gamma p 0 (-1) 0) qMinus -
        (1 - a ^ 2) *
          factorTwoIntrinsicElevenSelectorDual
            factorTwoIntrinsicElevenRetainedEvenWeight
            (retainedEvenSymmetricRepresenterAt gamma p)
            (retainedP024SymmetricSelector qPlus qMinus) +
        (1 - a ^ 2) * factorTwoIntrinsicElevenSelectorDual
          factorTwoIntrinsicElevenRetainedOddWeight
          (retainedOddAlternatingRepresenterAt gamma p) qAlt := by
  rw [retainedConstrainedSelectorDual_eq_phase_chord]
  have hAlt : 0 ≤ factorTwoIntrinsicElevenSelectorDual
      factorTwoIntrinsicElevenRetainedOddWeight
      (retainedOddAlternatingRepresenterAt gamma p) qAlt :=
    factorTwoIntrinsicElevenSelectorDual_nonneg _ _ _
      (fun x hx ↦ factorTwoIntrinsicElevenRetainedOddWeight_pos_on_Icc hx)
  have hb : b ^ 2 ≤ 1 - a ^ 2 := by
    linarith
  have hscaled := mul_le_mul_of_nonneg_right hb hAlt
  linarith

/-- The phase-boundary cost appearing on the right side of
`retainedConstrainedSelectorDual_le_boundary_chord`. -/
def retainedP024BoundaryChordCost
    (gamma : ℝ) (p qPlus qMinus qAlt : ℝ[X]) (a : ℝ) : ℝ :=
  retainedP024ChordPlus a *
      factorTwoIntrinsicElevenSelectorDual
        factorTwoIntrinsicElevenRetainedEvenWeight
        (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
          gamma p 0 1 0) qPlus +
    retainedP024ChordMinus a *
      factorTwoIntrinsicElevenSelectorDual
        factorTwoIntrinsicElevenRetainedEvenWeight
        (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
          gamma p 0 (-1) 0) qMinus -
    (1 - a ^ 2) *
      factorTwoIntrinsicElevenSelectorDual
        factorTwoIntrinsicElevenRetainedEvenWeight
        (retainedEvenSymmetricRepresenterAt gamma p)
        (retainedP024SymmetricSelector qPlus qMinus) +
    (1 - a ^ 2) * factorTwoIntrinsicElevenSelectorDual
      factorTwoIntrinsicElevenRetainedOddWeight
      (retainedOddAlternatingRepresenterAt gamma p) qAlt

/-- A single boundary-pencil inequality for three endpoint selector families
constructs the production selectors at every point of the phase disk.  This
is the structural replacement for checking phase-dependent pivots pointwise. -/
theorem exists_sharpRetunedP024Selector_of_boundary_chord
    (a b : ℝ) (hab : a ^ 2 + b ^ 2 ≤ 1)
    (qP0 qP2 qP4 qM0 qM2 qM4 qA0 qA2 qA4 : ℝ[X])
    (hqP0 : qP0.natDegree < 11) (hqP2 : qP2.natDegree < 11)
    (hqP4 : qP4.natDegree < 11) (hqM0 : qM0.natDegree < 11)
    (hqM2 : qM2.natDegree < 11) (hqM4 : qM4.natDegree < 11)
    (hqA0 : qA0.natDegree < 11) (hqA2 : qA2.natDegree < 11)
    (hqA4 : qA4.natDegree < 11)
    (hboundary : ∀ c0 c2 c4 : ℝ,
      retainedP024BoundaryChordCost (1 / 512 : ℝ)
          (retainedP024Polynomial c0 c2 c4)
          (threeSelectorPolynomial c0 c2 c4 qP0 qP2 qP4)
          (threeSelectorPolynomial c0 c2 c4 qM0 qM2 qM4)
          (threeSelectorPolynomial c0 c2 c4 qA0 qA2 qA4) a ≤
        symmetricQuadratic
          (retainedP024SharpLow00 a)
          (retainedP024SharpLow02 a)
          (retainedP024SharpLow04 a)
          (retainedP024SharpLow22 a)
          (retainedP024SharpLow24 a)
          (retainedP024SharpLow44 a)
          c0 c2 c4)
    (c0 c2 c4 : ℝ) :
    ∃ qE qO : ℝ[X],
      qE.natDegree < 11 ∧ qO.natDegree < 11 ∧
      factorTwoIntrinsicElevenRetainedConstrainedSelectorDual
          (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
          (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
            (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
          qE qO ≤
        factorTwoEndpointChannelPhase
            (centeredPolynomialLift (retainedP024Polynomial c0 c2 c4))
            (centeredPolynomialLift 0) a b -
          (1 / 8192 : ℝ) * factorTwoPhaseSingularWeightedEnergy
            (centeredPolynomialLift (retainedP024Polynomial c0 c2 c4))
            (centeredPolynomialLift 0) a b := by
  let qPlus := threeSelectorPolynomial c0 c2 c4 qP0 qP2 qP4
  let qMinus := threeSelectorPolynomial c0 c2 c4 qM0 qM2 qM4
  let qAlt := threeSelectorPolynomial c0 c2 c4 qA0 qA2 qA4
  let qE := retainedP024EvenChordSelector a qPlus qMinus
  let qO := retainedP024OddChordSelector b qAlt
  have hqPlus : qPlus.natDegree < 11 :=
    threeSelectorPolynomial_natDegree_lt
      c0 c2 c4 qP0 qP2 qP4 hqP0 hqP2 hqP4
  have hqMinus : qMinus.natDegree < 11 :=
    threeSelectorPolynomial_natDegree_lt
      c0 c2 c4 qM0 qM2 qM4 hqM0 hqM2 hqM4
  have hqAlt : qAlt.natDegree < 11 :=
    threeSelectorPolynomial_natDegree_lt
      c0 c2 c4 qA0 qA2 qA4 hqA0 hqA2 hqA4
  have hqE : qE.natDegree < 11 := by
    dsimp only [qE, retainedP024EvenChordSelector]
    exact natDegree_add_lt_eleven _ _
      (natDegree_smul_lt_eleven _ _ hqPlus)
      (natDegree_smul_lt_eleven _ _ hqMinus)
  have hqO : qO.natDegree < 11 := by
    dsimp only [qO, retainedP024OddChordSelector]
    exact natDegree_smul_lt_eleven _ _ hqAlt
  refine ⟨qE, qO, hqE, hqO, ?_⟩
  have hphase := retainedConstrainedSelectorDual_le_boundary_chord
    (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4)
      qPlus qMinus qAlt a b hab
  have hfinite :
      factorTwoIntrinsicElevenRetainedConstrainedSelectorDual
          (factorTwoIntrinsicElevenRetainedEvenMixedRepresenterAt
            (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
          (factorTwoIntrinsicElevenRetainedOddMixedRepresenterAt
            (1 / 512 : ℝ) (retainedP024Polynomial c0 c2 c4) 0 a b)
          qE qO ≤
        symmetricQuadratic
          (retainedP024SharpLow00 a)
          (retainedP024SharpLow02 a)
          (retainedP024SharpLow04 a)
          (retainedP024SharpLow22 a)
          (retainedP024SharpLow24 a)
          (retainedP024SharpLow44 a)
          c0 c2 c4 := by
    exact hphase.trans (by
      simpa only [qE, qO, qPlus, qMinus, qAlt,
        retainedP024BoundaryChordCost] using hboundary c0 c2 c4)
  have hzero : centeredPolynomialLift (0 : ℝ[X]) = (0 : ℝ → ℝ) := by
    funext x
    unfold centeredPolynomialLift
    simp
  rw [centeredPolynomialLift_retainedP024Polynomial, hzero,
    retainedP024SharpLowComplement_eq_symmetricQuadratic]
  exact hfinite

end

end ArithmeticHodge.Analysis.YoshidaFactorTwoPhaseIntrinsicElevenRetainedP024SelectorStructural
