/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 063; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks062

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row114_000_le :
    evenSparseDominanceBlockContribution (114 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (114 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row114_001_le :
    evenSparseDominanceBlockContribution (114 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (114 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row114_002_le :
    evenSparseDominanceBlockContribution (114 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (114 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row115_000_le :
    evenSparseDominanceBlockContribution (115 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (115 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row115_001_le :
    evenSparseDominanceBlockContribution (115 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (115 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row115_002_le :
    evenSparseDominanceBlockContribution (115 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (115 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row116_000_le :
    evenSparseDominanceBlockContribution (116 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (116 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row116_001_le :
    evenSparseDominanceBlockContribution (116 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (116 : YoshidaEvenIndex) 1 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
