/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 056; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks055

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row095_001_le :
    evenSparseDominanceBlockContribution (95 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (95 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row095_002_le :
    evenSparseDominanceBlockContribution (95 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (95 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row096_000_le :
    evenSparseDominanceBlockContribution (96 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (96 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row096_001_le :
    evenSparseDominanceBlockContribution (96 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (96 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row096_002_le :
    evenSparseDominanceBlockContribution (96 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (96 : YoshidaEvenIndex) 2 := by
  decide +kernel

theorem evenSparseDominanceBlock_row097_000_le :
    evenSparseDominanceBlockContribution (97 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (97 : YoshidaEvenIndex) 0 := by
  decide +kernel

theorem evenSparseDominanceBlock_row097_001_le :
    evenSparseDominanceBlockContribution (97 : YoshidaEvenIndex) 1 ≤
      evenSparseDominanceBlockBudget (97 : YoshidaEvenIndex) 1 := by
  decide +kernel

theorem evenSparseDominanceBlock_row097_002_le :
    evenSparseDominanceBlockContribution (97 : YoshidaEvenIndex) 2 ≤
      evenSparseDominanceBlockBudget (97 : YoshidaEvenIndex) 2 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
