/-
Generated by scripts/generate_yoshida_even_sparse_congruence.py
Canonical payload SHA-256: cdb37a48b2b2c28a71f266efdd84ed32bccd2d4c418037277b9bbd5a89dea9db
Dominance payload SHA-256: bcf0a4fe6a3aad2ad41d7b6edbee0b9cfbb86e52895cf36c9859916a9589b406
Residue-block check module 006; checks: 8.
-/

import ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceDominanceBlocks005

set_option autoImplicit false

namespace ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks

theorem evenSparseDominanceBlock_row009_003_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 3 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 3 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_004_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 4 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 4 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_005_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 5 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 5 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_006_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 6 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 6 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_007_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 7 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 7 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_008_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 8 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 8 := by
  decide +kernel

theorem evenSparseDominanceBlock_row009_009_le :
    evenSparseDominanceBlockContribution (9 : YoshidaEvenIndex) 9 ≤
      evenSparseDominanceBlockBudget (9 : YoshidaEvenIndex) 9 := by
  decide +kernel

theorem evenSparseDominanceBlock_row010_000_le :
    evenSparseDominanceBlockContribution (10 : YoshidaEvenIndex) 0 ≤
      evenSparseDominanceBlockBudget (10 : YoshidaEvenIndex) 0 := by
  decide +kernel

end ArithmeticHodge.Analysis.YoshidaEvenSparseCongruenceChecks
